netlify/build

- README.md
> Run Prettier

- .github/workflows/workflow.yml
This adds Coveralls so we can visualize the progress of our test coverage over time, and include changes in PRs.
> Add Coveralls

- README.md
This adds a Coveralls badge in `README`.
> Add test coverage badge in README

- README.md
- docs/creating-a-plugin.md
This runs Prettier on documentation files
> Run Prettier 

- .prettierrc.json
This improves Windows development by fixing newlines cross-platform issues with Prettier.
> Improve Windows development

- .prettierrc.json
- README.md
- examples/README.md
- examples/backwards-compat/README.md
- examples/example-two/README.md
- packages/netlify-plugin-axe/README.md
- packages/netlify-plugin-lighthouse/README.md
- packages/netlify-plugin-no-more-404/README.md
- packages/netlify-plugin-twiliosms/README.md
This improves Markdown style by letting Prettier automatically wrap long lines.
> Improve Markdown style

- CODE_OF_CONDUCT.md
This runs Prettier on the code of conduct.
> fix (docs): run Prettier

- CONTRIBUTING.md
- README.md
- scripts/docs.js
This adds `CONTRIBUTING` guidelines to help contributors.
> Add `CONTRIBUTING` guidelines

- .github/workflows/workflow.yml
- README.md
This adds a badge for the GitHub actions in the `README`.
> Add CI badge in `README`

- packages/build/tests/main.test.js
This fixes some tests due to PR rebasing.
> Fix some tests

- packages/build/src/plugins/child/validate.js
- packages/build/src/utils/list.js
This separates some listing utility into its own file.
> Separate listing utility

- packages/build/src/log/logger.js
- packages/build/src/log/redact.js
- packages/build/src/log/stream.js
This splits redacting logic to its own file.
> Split redacting logic to its own file

- packages/build/package-lock.json
- packages/build/package.json
- packages/netlify-plugin-axe/package-lock.json
- packages/netlify-plugin-axe/package.json
- packages/netlify-plugin-lighthouse/package-lock.json
- packages/netlify-plugin-lighthouse/package.json
- packages/netlify-plugin-monorepo/package-lock.json
- packages/netlify-plugin-monorepo/package.json
This upgrades Execa to the latest version.
> Upgrade Execa

- packages/build/package-lock.json
- packages/build/package.json
Fixes https://github.com/netlify/cli/issues/584
> Fix git dependency

- .github/workflows/workflow.yml
This adds support for Node 13 which was released 2 days ago.
> Add support for Node 13

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/tests/main.test.js
This allows testing that the `bin` field of `package.json`, ensuring that it points to an existing path.
> Test `package.json` `bin` field

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/tests/main.test.js
This ensures no process errors (process warnings, uncaught exceptions, unhandled promises, etc.) are emitted in our code, by making tests fail if that happens.
> Ensure no process errors are thrown

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- package.json
This runs Prettier in GitHub issue and PR templates.
> Fix Prettier in issue templates

- packages/build/src/plugins/ipc.js
Fixes #387.
This fix `yarn run` which was not working on Windows.
> Fix using `yarn run` on Windows

- packages/build/package-lock.json
- packages/build/package.json
- packages/config/package-lock.json
- packages/config/package.json
This upgrades to the latest version of `@netlify/config`.
> Upgrade `@netlify/config`

- packages/build/tests/fixtures/plugin_streams/plugin.js
This fixes a test that is currently failing.
> Fix a failing test

- CONTRIBUTING.md
- README.md
- examples/backwards-compat/README.md
- examples/example-two/README.md
- package.json
Prettier and Markdown-magic were conflicting. I fixed by simply renaming `docs` to `test:docs` (so it is run by`npm test`).
Note: one test is failing, but it's unrelated.
> Fix Prettier vs Markdown-magic conflict

- packages/build/tests/helpers/main.js
This is a small refactoring of the test helpers.
> Refactor test helpers

- packages/netlify-plugin-search-index/package-lock.json
Follow-up on #406 that fixes `package-lock.json`.
> Fix `package-lock.json`

- packages/netlify-plugin-search-index/index.js
This ensures search plugin is only using async I/O.
> Use async I/O in search plugin

- examples/example-two/package-lock.json
- packages/build/package-lock.json
`npm run example` is currently failing. This PR fixes this.
> Fix `npm run example`

- packages/build/tests/helpers/main.js
There's a `debug` flag that helps when writing tests. This PR improves it.
> Fix `debug` flag

- packages/build/tests/plugins/load/tests.js
This removes some debugging code left in a previous PR.
> Remove some debugging code

- packages/build/src/log/main.js
This is a small refactoring of the error logging logic.
> Refactor error logging

- packages/build/src/core/main.js
- packages/build/src/log/main.js
- packages/build/src/plugins/child/main.js
This documents how we have manipulating environment variables to get the colors right both in parent and child processes.
> Document how the colors logic works

- .eslintrc.json
- examples/example-one/plugins/example/index.js
- examples/example-two/plugins/plugin-one/index.js
- packages/build/scaffold/heuristics/index.js
- packages/build/scaffold/utils/execAsync.js
- packages/build/src/core/main.js
- packages/build/src/log/logger.js
- packages/build/src/log/main.js
- packages/build/src/plugins/child/constants.js
- packages/build/src/plugins/child/load.js
- packages/build/src/telemetry/plugins.js
- packages/build/src/telemetry/request.js
- packages/config/src/files.js
- packages/netlify-plugin-notifier/index.js
- packages/netlify-plugin-search-index/functionTemplate/searchIndex.js
- scripts/docs.js
This removes some variables that were not used.
> Remove unused variables

- packages/build/src/plugins/ipc.js
Fixes #462.
We set an `exit` event handler in plugins to check for early exits. However this event handler was not properly cleaned up, leading to a memory leak.
> Fix memory leak

- packages/build/src/log/stack.js
This fixes some tests that were failing in CI due to nyc internal logic.
> Fix tests failing with nyc

- packages/build/src/core/instructions.js
- packages/build/src/plugins/child/load.js
- packages/build/src/plugins/child/main.js
- packages/build/src/plugins/ipc.js
- packages/build/src/plugins/load.js
This PR improves child processes child-parent communication. 
The current implementation had some race conditions which led to some plugins hanging.
> Improve child processes IPC

- .github/workflows/workflow.yml
- packages/build/src/log/stack.js
- packages/build/tests/helpers/normalize.js
Few improvements related to Windows:
- fix stack traces printing on errors
- fix some failing tests
> Improve Windows support

- .github/workflows/workflow.yml
This adds Windows to tests on CI. :tada: :tada:
> Add Windows to CI tests

- .github/workflows/workflow.yml
This fixes some syntax errors in the GitHub action file.
> Fix GitHub action syntax

- .github/workflows/workflow.yml
This partially fixes test coverage on coveralls not being performed in parallel.
> Fix test coverage

- packages/build/src/log/stream.js
The output of commands or plugins is sometimes truncated if it's over 1MB. This is due to streams not being done flushing before the output is passed to the next command/plugin. This PR fixes it, although a more robust fix should be done eventually for this problem.
> Fix big outputs

- packages/build/tests/plugins/run/fixtures/big/netlify.yml
- packages/build/tests/plugins/run/fixtures/big/plugin.js
- packages/build/tests/plugins/run/tests.js
> Add big output test

- packages/build/package-lock.json
- packages/build/package.json
This upgrades one of our dependencies to fix a bug with multiple emissions of the same event.
> Upgrade `log-process-errors` dependency

- package-lock.json
- package.json
> Upgrade Prettier

- packages/build/tests/helpers/main.js
Small UI fix that improves the horizontal line printed by a test helper.
> Improve test helpers

- packages/build/src/core/instructions.js
This is a small refactoring that extracts a function to the top-level scope.
> Small refactoring of instructions retrieval

- packages/build/src/core/instructions.js
- packages/build/src/log/main.js
This fixes a header that was printed twice.
> Fixes duplicated header

- packages/build/src/core/dry.js
- packages/build/src/core/instructions.js
- packages/build/src/core/main.js
This is a small refactoring of the logic related to instructions, required in preparation for an upcoming PR related to error handling.
> Small refactoring related to instructions

- packages/build/package-lock.json
- packages/build/package.json
- packages/config/package-lock.json
- packages/config/package.json
This reduce the npm package size by avoiding adding test files to the npm bundle.
> Reduce npm package size

- README.md
- docs/creating-a-plugin.md
This improves documentation by:
- describing the new `plugin.config` property
- simplifying few examples
> Improve documentation

- packages/build/src/plugins/child/constants.js
The `constants` passed to plugins should be normalized when user is on Windows.
> Fix `constants` on Windows

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/plugins/child/constants.js
- packages/build/src/plugins/child/load.js
- packages/build/src/plugins/child/main.js
This PR improves Windows support for the `CACHE_DIR` constant.
> Improve Windows support for caching logic

- .gitignore
This removes a line in `.gitignore` that is not used anymore.
> Fix `.gitignore`

- packages/build/package-lock.json
- packages/build/package.json
This upgrades the JavaScript client dependency.
> Upgrade Netlify dependency

- packages/build/src/plugins/functions/index.js
- packages/build/src/utils/list.js
This PR improves the error message used when validating plugins.
> Improve error message

- packages/config/src/validate/example.js
- packages/config/src/validate/validations.js
This improves configuration validation by adding a comment and removing some dead code.
> Improve config validation

- CONTRIBUTING.md
- packages/build/package-lock.json
This fixes the CI tests that are currently failing.
> Fix failing tests

- packages/build/src/core/main.js
- packages/build/src/telemetry/index.js
> Send site id

- packages/config/src/validate/example.js
- packages/config/src/validate/main.js
- packages/config/src/validate/validations.js
This enhances the helpers used to validate the configuration object, by passing the properties keys to them.
> Allow using key in validation logic

- packages/build/src/cache/main.js
- packages/build/src/cache/plugin.js
This refactors some logic in the caching core plugin.
> Refactor some caching logic

- packages/build/src/cache/main.js
This refactors some logic in the "save cache" plugin.
> Refactor cache-related logic

- packages/config/src/validate/helpers.js
This PR removes some dead code.
> Remove some dead code

- examples/example-one/plugins/example/package.json
- examples/example-one/src/index.html
- examples/example-one/src/style.css
- package.json
This PR extracts the improvements made to the `examples` directory in #596.
> Improve example directory

- examples/example-two/.gitignore
- examples/example-two/README.md
- examples/example-two/functions/one.js
- examples/example-two/gulpfile.js
- examples/example-two/netlify.yml
- examples/example-two/package-lock.json
- examples/example-two/package.json
- examples/example-two/plugin.js
- examples/example-two/src/index.html
This adds an example directory which is automatically built on Netlify Build CI. This allows for Netlify Build to integration test itself.
> Add an example directory

- packages/build/tests/plugins/utils-cache/tests.js
This fixes a test that is currently failing in CI.
> Fix failing tests in CI

- packages/build/tests/utils/cache/tests.js
This fixes tests that are currently failing on Windows in CI.
> Fix failing tests on Windows

- packages/cache-utils/README.md
This updates the `README` of the cache utility.
> Update `README` of utility

- packages/cache-utils/README.md
This adds more documentation about the methods available in the `cache` utility.
> Add more documentation about the `cache` utility

- packages/build/src/plugins/options.js
- packages/build/src/plugins_core/cache.js
- packages/build/src/plugins_core/functions.js
- packages/build/src/plugins_core/main.js
This moves some files around so that core plugins are in the same directory.
> Move files

- packages/functions-utils/README.md
This improves the documentation of the `functions` utility.
@sw-yx What do you think?
> Improve documentation of the `functions` utility

- packages/build/src/core/bin.js
This improves the speed of builds when run through the CLI.
> Improve speed

- packages/cache-utils/README.md
- packages/functions-utils/README.md
- packages/git-utils/README.md
> Update util docs

- CONTRIBUTING.md
- README.md
- examples/backwards-compat/README.md
- packages/git-utils/README.md
> Update git util docs

- package-lock.json
- package.json
> Upgrade ESLint

- package-lock.json
- package.json
Upgrade eslint-config-prettier dependency
> Upgrade eslint-config-prettier

- package-lock.json
- package.json
Upgrade eslint-plugin-import dependency
> Upgrade eslint-plugin-import

- package-lock.json
- package.json
Upgrade eslint-plugin-node dependency
> Upgrade eslint-plugin-node

- package-lock.json
- package.json
Upgrade eslint-plugin-prettier dependency
> Upgrade eslint-plugin-prettier

- package-lock.json
- package.json
> Upgrade husky

- package-lock.json
- package.json
> Upgrade lerna

- package-lock.json
- package.json
> Upgrade nyc

- packages/build/package-lock.json
- packages/build/package.json
- packages/config/package-lock.json
- packages/config/package.json
> Upgrade resolve

- packages/build/package-lock.json
- packages/build/package.json
- packages/git-utils/package-lock.json
- packages/git-utils/package.json
> Upgrade moize

- packages/build/package-lock.json
- packages/build/package.json
> Upgrade yargs

- packages/cache-utils/README.md
The cache utility `README` was outdated and contained few mistakes not matching the latest API. This PR fixes those.
> Update `README` of cache utility

- packages/cache-utils/src/main.js
- packages/cache-utils/src/manifest.js
This is a small refactoring of the cache utility. It simply removes an unused variable.
> Small refactoring of cache utility

- packages/build/src/core/config.js
- packages/build/src/core/main.js
- packages/build/src/telemetry/index.js
This is a small refactoring of the variables related to CLI flags.
> Small variables refactoring

- packages/build/src/plugins/child/load.js
- packages/build/src/plugins/child/package.js
- packages/build/src/plugins/install.js
- packages/build/src/plugins/load.js
- packages/build/src/plugins/options.js
This add an internal utility helper to detect whether a plugin is local or not.
> Add `local` utility helper

- packages/config/package-lock.json
- packages/config/package.json
This upgrades some dependencies inside `@netlify/config`.
> Upgrade dependencies of `@netlify/config`

- packages/build/package-lock.json
- packages/build/package.json
This upgrades the `uuid` dependency.
> Upgrade `uuid` dependency

- packages/build/package-lock.json
- packages/build/package.json
This upgrades the `resolve` dependency.
> Upgrade `resolve` dependency

- packages/build/src/core/config.js
- packages/build/src/plugins/git.js
- packages/build/src/utils/remove_falsy.js
This adds a small helper function to remove falsy values from an object.
> Add `removeFalsy()` helper function

- packages/build/src/log/constants.js
- packages/build/src/log/empty.js
- packages/build/src/log/main.js
- packages/build/src/log/plugin_error.js
This is a small refactoring of constants used during logging. This PR just moves lines around.
> Refactor log constants

- packages/build/src/error/clean_stack.js
- packages/build/src/error/stack.js
Related to #735.
This is a small refactoring of the error stack cleanup. This just moves code around, but does not change the logic itself.
> Small refactoring of stack cleanup

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/tests/helpers/main.js
This adds a test helper function required for an upcoming PR.
> Add `copyToTemp()` test helper function

- packages/build/tests/helpers/main.js
Some tests were failing on Mac. This is due to the directory returned by `os.tmpdir()` being a symlink on Mac as opposed to other OS. This PR fixes this.
> Fix tests failing on Mac

- packages/build/tests/config/context/tests.js
- packages/build/tests/config/load/tests.js
- packages/build/tests/core/flags/tests.js
- packages/build/tests/helpers/dir.js
- packages/build/tests/helpers/main.js
- packages/build/tests/helpers/temp.js
- packages/build/tests/plugins/env/tests.js
- packages/build/tests/plugins/functions/tests.js
- packages/build/tests/plugins/install/tests.js
- packages/build/tests/plugins/load/tests.js
- packages/build/tests/utils/cache/tests.js
- packages/build/tests/utils/git/tests.js
The test helpers are all inside one big file at the moment.
This PR just splits them into several files.
> Move some code around

- packages/run-utils/README.md
just adding a little bit of info shared in netlify slack
> document that `run` is a thin wrapper

- docs/creating-a-plugin.md
document utils.build.fail/cancel a little more
discussion: https://netlify.slack.com/archives/CPCL7QAE4/p1583849912137900
notified: https://github.com/neverendingqs/netlify-deployment-hours-plugin/blob/master/index.js#L16, who else?
> document utils.build.fail/cancel a little more

- packages/build/src/error/serialize.js
- packages/build/src/error/type.js
This is a small refactoring of the error utilities. It mostly moves some lines around.
> Small refactoring of error utilities

- packages/build/src/core/api.js
- packages/build/src/error/location.js
- packages/build/src/error/type.js
This PR improves error messages when there's an API error (call to Bitballoon).
> Improve error messages of API calls

- packages/build/package-lock.json
This PR upgrades the OpenAPI definition to include a fix for the `cancelSiteDeploy` endpoint.
> Upgrade OpenAPI definition

- packages/build/package-lock.json
- packages/build/package.json
This PR upgrades `zip-it-and-ship-it` to its latest beta release.
> Upgrade `zip-it-and-ship-it`

- packages/build/tests/README.md
The documentation for the tests setup is slightly outdated. This PR fixes that.
> Fix tests documentation

- packages/build/package-lock.json
- packages/build/package.json
This upgrades the Netlify `js-client` to the latest major version.
The latest major version of the `js-client` does not add any feature relevant to this project.
> Upgrade `js-client`

- packages/build/package-lock.json
- packages/functions-utils/package-lock.json
Upgrades `kind-of` dependency to fix a security vulnerability reported both by GitHub and `npm audit`.
> Upgrade `kind-of` dependency

- packages/build/package-lock.json
- packages/config/package-lock.json
Fixes #1085.
This upgrades some dependencies to fix security vulnerabilities.
> Fix `npm audit` issues

- packages/build/src/plugins/child/load.js
This removes an argument that is not used.
> Remove dead code

- packages/build/src/plugins/child/error.js
- packages/build/src/plugins/child/load.js
- packages/build/src/plugins/child/main.js
- packages/build/src/plugins/child/run.js
This PR simply shuffles some lines of code around and simplifies how plugin events pass information to each other. This is refactoring only.
> Refactor child process files

- packages/build/src/error/type.js
This PR adds code comments on each available error type. 
It also shuffles those error types around in the file a little.
> Add comments on error types

- packages/build/src/plugins/options.js
Part of #1220.
This allows core plugins to be optional, so that we can make the automatic installation of Netlify Functions optional.
This requires #1242 to be merged first for users to be able to opt-in to those modules without getting a `npm install` error.
> Allow core plugins to be optional

- packages/config/README.md
The `README` of `@netlify/config` is very outdated and documents removed features.
This PR updates it.
The different options/CLI flags and the meaning of the output/return value is not documented yet. This is a first draft to just get started and remove old documentation.
> Update `@netlify/config` `README`

- packages/build/src/plugins/options.js
This is a small refactoring extracting a function to the top-level scope.
> Small refactoring extracting a function

- packages/build/src/install/main.js
Fixes #1222.
When we automatically install plugins, function dependencies or local plugin dependencies, we currently have some logic that tries to take advantage of lock files. This logic is creating too many issues, so this PR is removing it to prioritize stability.
> Fix automatic installation crashing

- README.md
Fixes #1232.
This adds more documentation about the `netlify build` CLI command.
> Add more documentation about the `netlify build` CLI command

- README.md
> we're stable now! 🔥

- packages/build/src/telemetry/track.js
Fixes #1391.
We do a telemetry call at the end of the build.
This call should not impact build speed, so it's spawned in a child process.
However, it should also not impact build status, so errors should be ignored.
This PR implements this.
> Fix `spawn node ENOENT`

- packages/build/src/install/main.js
We have some logic related to the lack of support for `npm ci` in old npm versions. However `npm ci` is not used anymore, so that function can be removed. This is refactoring only.
> Simplify code related to npm install

- packages/build/tests/helpers/common.js
This PR is a small refactoring of how CLI flags are passed to the `@netlify/build` binary in tests.
It only shuffles lines around, but does not change the test logic.
> Refactor how CLI flags are passed in tests

- packages/config/src/validate/main.js
- packages/config/src/validate/validations.js
This removes some dead code related to validation warnings in `@netlify/config`. That code is not used anymore.
> Remove code related to validation warnings in `@netlify/config`

- packages/build/src/env/changes.js
This is a small refactoring that simplifies some code without changing its behavior.
> Simplify some code

- packages/build/tests/helpers/common.js
This simplifies some code related to the `PRINT` environment variable used in testing.
This is just refactoring, it does not change any logic.
> Refactor some code related to the `PRINT` environment variable

- packages/config/src/api/client.js
- packages/config/src/main.js
This is a small refactoring of how some options are used in `@netlify/config`. 
This does not change any behavior.
> Refactor some code in `@netlify/config`

- packages/config/src/api/client.js
- packages/config/src/options/branch.js
- packages/config/src/options/main.js
- packages/config/tests/context/tests.js
- packages/config/tests/helpers/main.js
`@netlify/config` is influenced by some environment variables.
This PR adds the possibility to override those with an `env` option. This is useful notably in testing.
> Add `opts.env` to `@netlify/config`

- packages/build/tests/helpers/main.js
- packages/config/tests/helpers/main.js
> Add some comments

- packages/build/tests/core/tests.js
- packages/build/tests/env/tests.js
- packages/build/tests/error/tests.js
- packages/build/tests/plugins/tests.js
- packages/config/tests/parse/tests.js
- packages/git-utils/tests/main.js
This PR re-enables some tests that were disabled due to platform-specific issues which got fixed by the tests refactoring.
It also adds few code comments.
> Re-enable some tests

- packages/build/src/plugins/ipc.js
This PR refactors the logic related to parent/child process communication. It only moves lines around, without changing the behavior.
> Refactor IPC logic

- .github/workflows/workflow.yml
This runs CI tests using Node 14 instead of Node 13.
> Test in Node 14 instead of Node 13

- packages/build/tests/install/tests.js
This simplifies some tests, by creating a test helper for some of the logic that was repeated between most of the tests of the file.
> Simplify some tests

- packages/build/tests/log/tests.js
This is a small refactoring of some tests, putting some common options together.
> Simplify some test

- packages/build/tests/README.md
- packages/build/tests/helpers/common.js
This updates the documentation of how tests are working in this monorepo.
> Update documentation of the test helpers

- packages/build/tests/core/tests.js
`get-node` is used in some tests to retrieve a Node.js binary from a specific Node.js version, in order to test the `--node-path` CLI flag. 
However, this can sometimes fail due to network error when fetching `https://nodejs.org/dist`. This makes those tests randomly fail. This is a rare error though.
This PR fixes this by retrying up to 10 times on network error.
> Fix test that randomly fails

- packages/build/src/error/monitor/normalize.js
This improves some of the regular expressions used to group Bugsnag errors, based on some errors encountered in production.
> Improve Bugsnag error grouping

- packages/build/src/core/main.js
This moves some lines of code to make a big function a little smaller.
> Move some lines of code

- packages/build/src/core/main.js
This splits a big function into two smaller functions. This is refactoring only.
> Split a function into two functions

- packages/build/src/core/config.js
This moves a function inside a file.
> Move a function

- CONTRIBUTING.md
This adds some documentation about the release process in the `README.md`.
> Add documentation about release process

- packages/cache-utils/package-lock.json
- packages/cache-utils/package.json
- packages/functions-utils/package-lock.json
- packages/functions-utils/package.json
This upgrades the `cpy` dependency used in `utils.cache` and `utils.functions`.
> Upgrade `cpy`

- packages/git-utils/package-lock.json
- packages/git-utils/package.json
This upgrades `moize` used in `utils.git`.
> Upgrade `moize`

- packages/run-utils/package-lock.json
- packages/run-utils/package.json
This upgrades `semver` used as dev dependency in `utils.run`
> Upgrade `semver`

- packages/build/tests/helpers/temp.js
This refactors some test helper, in order to help create a test related to the upcoming `--timersFile` CLI flag.
> Refactor some test helper

- packages/build/package-lock.json
- packages/build/package.json
`pretty-ms@6` [is not compatible](https://github.com/sindresorhus/pretty-ms/releases/tag/v6.0.0) with Node 8.
> Downgrade `pretty-ms`

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/commands/run.js
- packages/build/src/core/main.js
- packages/build/src/time/report.js
- packages/build/tests/time/tests.js
This adds metrics about how long each plugin event takes, and also `build.command`.
> Send metrics about plugins and `build.command`

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/commands/run.js
- packages/build/src/core/config.js
- packages/build/src/core/main.js
- packages/build/src/plugins/load.js
- packages/build/src/plugins/options.js
- packages/build/src/plugins/spawn.js
- packages/build/src/time/report.js
This refactors how the duration of each build phase is measured, by using a function wrapper.
> Add function wrapper to measure duration

- packages/build/src/commands/error.js
- packages/build/src/core/main.js
- packages/build/src/error/handle.js
- packages/build/src/status/report.js
This refactors the main function, so that it can be measured by the duration function wrapper, as part of the speedy builds feature.
This only refactors code, it does not change the logic.
> Refactor main function

- packages/build/src/buildbot_client/main.js
- packages/build/src/commands/run.js
- packages/build/src/core/main.js
- packages/build/src/error/parse/location.js
- packages/build/src/error/type.js
This is preparing for another PR. I'm splitting #1659 into separate PRs.
#1659 is where these changes came from. #1686 needs to be merged first, and is the base for these changes.
I have implemented a socket server client that will connect to the buildbot socket server and send a deploy message.
**Checklist**
> Buildbot socket server client

- packages/build/tests/time/tests.js
Part of https://github.com/netlify/buildbot/issues/888
This refactors the tests related to performance monitoring, so they re-use some shared logic.
> Refactor timings tests

- packages/build/src/commands/run.js
This improves some comments about plugin error handling to make them clearer and more accurate.
> Improve documentation of error handling

- packages/build/src/log/logger.js
This refactors the logging methods we use so that they can all override the default indentation and color.
> Refactor logging utility

- packages/build/src/plugins/child/status.js
This splits a function into few smaller functions.
> Split a function into smaller functions

- packages/build/src/plugins/resolve.js
This is a small refactoring to remove a linting warning.
> Small refactoring to decrease cyclomatic complexity

- packages/config/src/main.js
This splits a function into two smaller functions.
> Refactor a function to make it smaller

- .eslintrc.json
- packages/build/src/core/main.js
- packages/build/src/log/messages/plugins.js
- packages/build/src/plugins/ipc.js
- packages/build/src/plugins/node_version.js
- packages/build/src/plugins/spawn.js
- packages/build/tests/error/fixtures/cancel/plugin.js
- packages/build/tests/error/fixtures/cancel_error_option/plugin.js
- packages/build/tests/error/fixtures/cancel_post_deploy/plugin.js
- packages/build/tests/error/fixtures/exception/plugin.js
- packages/build/tests/error/fixtures/exception_array/plugin.js
- packages/build/tests/error/fixtures/exception_circular/plugin.js
- packages/build/tests/error/fixtures/exception_props/plugin.js
- packages/build/tests/error/fixtures/exception_string/plugin.js
- packages/build/tests/error/fixtures/fail_build/plugin.js
- packages/build/tests/error/fixtures/fail_build_error_option/plugin.js
- packages/build/tests/error/fixtures/fail_build_post_deploy/plugin.js
- packages/build/tests/error/fixtures/plugin_exit/plugin.js
- packages/build/tests/error/fixtures/unhandled_promise/plugin.js
- packages/build/tests/helpers/common.js
- packages/build/tests/plugins/fixtures/cache/plugin.js
- packages/cache-utils/tests/save_restore.js
- packages/functions-utils/tests/helpers/main.js
Like https://github.com/netlify/cli/pull/1278
This adds the `require-await` ESLint rule
> Add `require-await` ESLint rule

- packages/build/src/plugins_core/deploy/buildbot_client.js
Thanks to #1826, core plugins errors are now automatically handled without having to define a new error type for each of them. Therefore, we can remove the specific error type for the deploy core plugin without impacting the quality of our error handling.
> Simplify error handling of deploy core plugin

- packages/build/src/commands/get.js
- packages/build/src/commands/run_command.js
- packages/build/src/core/dry.js
- packages/build/src/status/add.js
Related to #1191
This renames some functions related to build failures to make them clearer.
> Rename some functions

- packages/build/src/core/constants.js
- packages/build/src/plugins_core/deploy/buildbot_client.js
- packages/build/src/plugins_core/deploy/index.js
- packages/build/tests/helpers/tcp_server.js
- packages/build/tests/plugins/tests.js
Fixes #1913.
This removes deploy timeout.
> Fix deploy timeout

- packages/build/src/commands/plugin.js
- packages/build/src/plugins/load.js
- packages/build/src/plugins/manifest/main.js
- packages/build/src/status/add.js
- packages/build/src/status/load_error.js
- packages/build/src/status/success.js
This splits a file into some smaller files.
> Split file into smaller files

- packages/build/src/core/lingering.js
Fixes #1932.
See #1932 for the background on this.
This is not a perfect solution, but I am not managing to reproduce this problem, and am hopeful #1888 will fix the underlying problem.
> Fix lingering process `[node]`

- .eslintrc.js
- .gitattributes
- .github/workflows/workflow.yml
- package-lock.json
- package.json
- scripts/run_on_error.js
See https://github.com/netlify/cli/pull/1387, https://github.com/netlify/build/issues/1950
This makes npm scripts similar to the ones in Netlify CLI.
This also aligns the GitHub actions workflow file.
> Improve npm scripts

- CONTRIBUTING.md
This documents how to make a beta release in Netlify Build.
> Add documentation about the beta release

- CONTRIBUTING.md
This documents that linting and prettification should be run on file save if possible.
> Document lint-on-save recommendation

- .eslintrc.js
- packages/config/README.md
- packages/git-utils/README.md
This adds the [`multiline-comment-style`](https://eslint.org/docs/rules/multiline-comment-style) ESLint rule.
> Add `multiline-comment-style` ESLint rule

- .eslintrc.js
- packages/config/src/api/build_settings.js
- packages/git-utils/src/main.js
- packages/git-utils/src/refs.js
This adds the [`default-param-last`](https://eslint.org/docs/rules/default-param-last) ESLint rule.
> Add `default-param-last` ESLint rule

- .eslintrc.js
- packages/build/tests/helpers/server.js
This adds the [`prefer-destructuring`](https://eslint.org/docs/rules/prefer-destructuring) ESLint rule.
> Add `prefer-destructuring` ESLint rule

- .eslintrc.js
- packages/build/src/env/changes.js
- packages/build/src/log/messages/status.js
- packages/build/src/plugins/child/validate.js
- packages/build/src/time/report.js
- packages/config/src/validate/main.js
See https://github.com/netlify/cli/pull/1395
This adds the `array-callback-return` ESLint rule.
> Add `array-callback-return` ESLint rule

- .eslintrc.js
- packages/build/src/plugins_core/functions/error.js
This adds the [`no-return-await`](https://eslint.org/docs/rules/no-return-await) ESLint rule.
> Add `no-return-await` ESLint rule

- .eslintrc.js
- packages/build/src/error/handle.js
- packages/build/src/error/monitor/report.js
- packages/build/src/log/old_version.js
- packages/build/src/log/stream.js
- packages/build/src/plugins/load.js
- packages/build/tests/core/tests.js
- packages/build/tests/helpers/common.js
- packages/build/tests/plugins/tests.js
- packages/cache-utils/src/fs.js
- packages/functions-utils/src/main.js
- scripts/run_on_error.js
This adds the [`no-shadow`](https://eslint.org/docs/rules/no-shadow) ESLint rule.
> Add `no-shadow` ESLint rule

- .prettierrc.json
This removes a redundant Prettier option. See https://github.com/netlify/cli/pull/1435
> Remove redundant Prettier option

- .eslintrc.js
- .prettierrc.json
- ava.config.js
- package-lock.json
- package.json
- packages/config/src/case.js
This uses the shared ESLint and Prettier configuration at `@netlify/eslint-config-node` ([link to repository](https://github.com/netlify/eslint-config-node)).
See https://github.com/netlify/cli/pull/1462 for more details.
> Use `@netlify/eslint-config-node`

- .eslintrc.js
- package-lock.json
- package.json
See https://github.com/netlify/cli/pull/1485
> Upgrade `@netlify/eslint-config-node`

- .eslintrc.js
- packages/build/src/plugins/ipc.js
Fixes #1956.
This adds [`eslint-plugin-promise`](https://github.com/xjamundx/eslint-plugin-promise).
> Add `eslint-plugin-promise`

- .eslintrc.js
- packages/build/src/error/handle.js
- packages/build/src/plugins/child/logic.js
- packages/build/tests/plugins/tests.js
See https://github.com/netlify/build/issues/1955
This adds [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import).
> Add `eslint-plugin-import`

- packages/build/tests/core/tests.js
This is a small refactoring of the tests related to telemetry. This does not modify them.
> Simplify tests related to telemetry

- packages/config/src/files.js
This is a small refactoring of a function in `@netlify/config`.
It does not change behavior.
> Small refactoring

- packages/build/src/commands/error.js
- packages/build/src/commands/plugin.js
- packages/build/src/error/build.js
- packages/build/src/plugins/ipc.js
- packages/build/src/plugins/load.js
- packages/build/src/plugins/manifest/main.js
- packages/build/src/plugins/spawn.js
- packages/build/src/status/load_error.js
This refactors IPC error handling, to prepare for #2056.
This only moves logic around. This does not modify it.
> Refactor IPC errors

- renovate.json5
Add another dependency which does not support Node 8
> Add `supports-color` to `renovate.json5`

- .gitignore
Ignore `.vscode` specific settings
Add `.vscode` to `.gitignore`
Being careful to not commit `.vscode`
**Checklist**
> chore: git ignore .vscode

- packages/build/src/log/messages/plugins.js
This removes some dead code that is not needed anymore since #2089.
> Remove dead code related to `plugins.json` fetch

- packages/build/src/install/missing.js
- packages/build/src/log/messages/install.js
- packages/build/src/plugins/resolve.js
This PR improves the code comments related to plugins installation, and rename some internal variables.
> Improve comments related to plugins installation

- packages/build/src/utils/resolve.js
I have encountered a situation where `require.resolve()` returned a non-existing file.
Following the [official documentation](https://nodejs.org/api/modules.html#modules_require_resolve_request_options), this should never happen. I tried digging into the Node.js codebase, but could not find an answer.
https://github.com/nodejs/node/blob/831f4c755d2270e7b44c075176ab4a05698d21d9/lib/internal/modules/cjs/helpers.js#L101
https://github.com/nodejs/node/blob/3604fadacf480dd141d636883d559631ee62128c/lib/internal/modules/cjs/loader.js#L840
What is very strange is that [`resolve`](https://github.com/browserify/resolve) (the userland implementation of `require.resolve()`) does not show this behavior in my case.
What is even stranger is that when passing the exact same arguments to …
> Fix bug with `require.resolve()`

- packages/build/tests/error/tests.js
This fixes a test that is currently randomly failing.
> Fix a randomly failing test

- .github/workflows/labeler.yml
This PR adds an action to automate PR labeling
> chore: add PR labeler action

- .github/workflows/workflow.yml
- packages/build/src/log/stream.js
- packages/build/src/time/report.js
- packages/build/tests/error/fixtures/cancel_callback/plugin.js
- packages/build/tests/error/fixtures/early_exit/plugin_slow.js
- packages/build/tests/error/fixtures/fail_build_callback/plugin.js
- packages/build/tests/error/fixtures/fail_plugin_callback/plugin.js
- packages/build/tests/error/fixtures/uncaught/plugin.js
- packages/build/tests/error/fixtures/unhandled_promise/plugin.js
- packages/build/tests/error/fixtures/warning/plugin.js
- packages/build/tests/plugins/fixtures/interleave/plugin.js
- packages/cache-utils/tests/helpers/main.js
Part of https://github.com/netlify/team-dev/issues/1
This runs CI tests on Node 15.
I've checked the changelog of Node 15, and everything should be ok.
> Upgrade to Node 15

- packages/build/package-lock.json
- packages/build/package.json
Forcing a version bump of `@netlify/config` on `@netlify/build`
> chore(deps): bring build's config depedency to the latest version

- packages/build/package.json
- packages/functions-utils/package.json
Hopefully this time will actually force a release 🙏 
As per - https://github.com/netlify/team-dev#forcing-a-release - I've bumped `zip-it-and-ship-it` in the `package.json` as a way to force this. The lockfile is already up to date.
> fix(deps): force a release for #2244 and bump zip-it-and-ship-it

- .eslintrc.js
> chore: fix linting with npm 7 workspaces

- packages/build/src/log/messages/core_commands.js
- packages/build/src/plugins_core/functions/index.js
This PR fixes an issue where `@netlify/build` would incorrectly show a message indicating that a function has been bundled with warnings. It also formats the errors and warnings a bit better.
**Checklist**
> fix: fix esbuild error reporting

- packages/build/src/error/info.js
This renames an internal variable.
> fix: rename internal variable

- packages/build/src/core/lingering.js
Part of #1966.
This simplifies the lingering processes query.
> fix: improve lingering processes query

- packages/build/src/core/lingering.js
- packages/build/src/log/messages/core.js
- packages/build/tests/core/tests.js
Part of #1966.
This adds bullet points to the lingering process warning message, and refactors it for some upcoming PRs.
> feat: improve lingering process message to add bullet points

- .github/workflows/release-please.yml
- package.json
Fixes the release process, see https://github.com/netlify/build/runs/2229732832?check_suite_focus=true#step:5:15
> chore(release-please): install deps before publishing to npm

- renovate.json5
See https://github.com/netlify/build/pull/2530
Merging this PR should also autoclose #2530
> chore(renovate): ignore ps-list major updates

- packages/build/src/plugins/compatibility.js
- packages/build/src/plugins/expected_version.js
Part of #2579.
Depends on #2613. In draft mode until that PR is merged to simplify reviewer's work.
This start adding the logic related to plugin versions pinning. Since the API is not sending the versions information yet, this is a noop at the moment, and some plumbing work is still missing. Also, no tests yet for the same reason.
> feat: start pinning plugin versions

- package.json
This fixes the manual publish flow.
> chore: fix manual publishing

- packages/build/tests/README.md
This fixes some documentation links
> chore: fix some documentation links

- packages/build/tests/helpers/normalize.js
Part of https://github.com/netlify/build/issues/2682
This fixes the snapshot normalization of ports.
> chore: fix snapshot normalization of ports

- packages/build/src/plugins/resolve.js
Part of https://github.com/netlify/build/issues/2575
This removes some dead code.
> chore: remove some dead code

- packages/build/src/commands/core_command.js
- packages/build/src/commands/run_command.js
- packages/build/src/commands/run_commands.js
- packages/build/src/core/dry.js
- packages/build/src/core/main.js
- packages/build/src/plugins_core/functions/index.js
Part of #1193.
This removes some unused variables.
> chore: remove dead code

- packages/config/src/files.js
- packages/config/src/main.js
Part of #1193.
This renames a variable to make it clearer.
> chore: rename a variable

- packages/config/src/base.js
- packages/config/src/main.js
Part of #1193.
This moves some lines of code, without changing behavior.
> chore: move lines of code

- packages/config/src/build_dir.js
- packages/config/src/files.js
- packages/config/src/log/messages.js
Part of #1193.
This is small refactoring of a warning message, needed for an upcoming PR.
> fix: refactor a warning message

- packages/config/src/files.js
- packages/config/src/main.js
Part of #2889.
This moves some lines of code, without changing any behavior.
> fix: move some lines of code

- renovate.json5
Should auto close https://github.com/netlify/build/pull/3006
> chore(deps): ignore major updates for dot-prop

- packages/config/package.json
- packages/functions-utils/package.json
So it is the same as `netlify/build`
> fix: pin zisi version in functions utils

- package-lock.json
- packages/build/package.json
- packages/functions-utils/package.json
> chore: revert "fix(deps): update dependency @netlify/zip-it-and-ship-it to v4.6.0"

- renovate.json5
> chore: add `keep-func-props` to `renovate.json5`

- packages/build/src/plugins/child/mutations.js
- packages/build/src/plugins/child/run.js
Part of #3051.
This simplifies the proxy logic related to `netlifyConfig`, removing lots of code now unnecessary.
> feat: simplify proxy logic

- package-lock.json
- packages/build/package.json
Forcing `@netlify/config` update to latest - https://github.com/netlify/build/pull/3300
https://github.com/netlify/build/pull/3296
> chore(dependencies): bump @netlify/config major version

- .github/workflows/fossa.yml
- fossa workflow file failing
- N/A
- update method for downloading fossa cli tool
**Checklist**
N/A
> fix: fossa workflow

- packages/build/src/core/dry.js
This is a small code simplification by using [the `p-filter` utility](https://github.com/sindresorhus/p-filter).
> chore: small code simplification

- packages/build/src/plugins/list.js
This versions `plugins.json` so that breaking changes in `plugins.json` do not break sites.
> feat: add versioning to `plugins.json`

- .github/workflows/release-please.yml
Applies the same fix as https://github.com/netlify/cli/pull/3105
> chore: pin release please version

- packages/config/src/headers.js
Part of https://github.com/netlify/build/issues/2890
See also https://github.com/netlify/netlify-headers-parser/pull/11
This simplifies headers parsing by moving most of the logic to `netlify-headers-parsing` and re-using the `parseAllHeaders()` which does the same logic as the one currently in `@netlify/config`.
> feat: simplify headers parsing

- packages/config/src/redirects.js
Part of https://github.com/netlify/build/issues/1193
See also https://github.com/netlify/build/pull/3468 and https://github.com/netlify/netlify-redirect-parser/pull/316
This simplifies redirects parsing by moving most of the logic to `netlify-redirect-parsing` and re-using the `parseAllRedirects()` method which does the same logic as the one currently in `@netlify/config`.
> feat: simplify redirects parsing

- renovate.json5
This updates `renovate.json5`.
> chore: update `renovate.json5`

- packages/config/src/env/main.js
This fixes a wrong comment and confusing duplicate code.
> fix: duplicate code

- package-lock.json
- package.json
Follow-up on https://github.com/netlify/build/pull/3640
Lerna is not needed anymore.
> chore: remove lerna

- packages/build/test-d/config/build.ts
- packages/build/test-d/config/functions.ts
- packages/build/test-d/config/inputs.ts
- packages/build/test-d/config/netlify_config.ts
- packages/build/test-d/netlify_plugin.ts
- packages/build/test-d/netlify_plugin_options.ts
- packages/build/test-d/options/netlify_plugin_build_util.ts
- packages/build/test-d/options/netlify_plugin_cache_util.ts
- packages/build/test-d/options/netlify_plugin_git_util.ts
- packages/build/test-d/options/netlify_plugin_run_util.ts
- packages/build/test-d/options/netlify_plugin_status_util.ts
Follow-up on https://github.com/netlify/build/pull/3816
This improves the types tests to also test the newly exported types.
@bengry Does this look good?
---
> chore: improve tests of plugin TypeScript types

- packages/build/package.json
Follow up on https://github.com/netlify/build/pull/3895
> fix: force release

- .eslintrc.js
This removes some unused rule exceptions in `.eslintrc.js`.
---
> chore: remove some dead code in `.eslintrc.js`

- .eslintrc.js
- packages/build/src/plugins/child/utils.js
- packages/functions-utils/package.json
- packages/functions-utils/src/main.js
- packages/functions-utils/tests/fixtures/directory/test/index.js
- packages/functions-utils/tests/fixtures/file/test.js
- packages/functions-utils/tests/fixtures/file/test.mjs
- packages/functions-utils/tests/fixtures/file/test_2.js
- packages/functions-utils/tests/fixtures/file/test_2.mjs
- packages/functions-utils/tests/fixtures/list/four.js/four.js.js
- packages/functions-utils/tests/fixtures/list/one/index.js
- packages/functions-utils/tests/fixtures/list/test.js
- packages/functions-utils/tests/fixtures/list/two/three.js
- packages/functions-utils/tests/fixtures/list/two/two.js
- packages/functions-utils/tests/helpers/main.js
- packages/functions-utils/tests/main.mjs
This switches `functions-utils` from CommonJS to pure ES modules.
---
> chore!: use pure ES modules with `functions-utils`

- packages/cache-utils/README.md
- packages/functions-utils/README.md
- packages/git-utils/README.md
Part of https://github.com/netlify/pod-workflow/issues/236
Build plugins can now use ES modules.
This PR updates the `README.md` accordingly.
---
> feat: update `README.md` to use ES modules with plugins

- packages/build/src/plugins_core/functions/utils.js
- packages/cache-utils/src/fs.js
- packages/functions-utils/src/main.js
> fix: use fs promises directly

- package-lock.json
- packages/cache-utils/package.json
- packages/config/package.json
- packages/functions-utils/package.json
Unsure if this should be a new major version along with #4037, I'll let you decide. :)
---
---
> fix(deps): update del to v6.0.0

- package-lock.json
- packages/build/package.json
These were flagged in the E2E tests on CLI and indeed ts-node has them as peerDependencies.
---
---
> fix(deps): add missing ts-node peer dependencies

- package-lock.json
- packages/build/package.json
Pins `@netlify/zip-it-and-ship-it` to v5.4.1.
> fix: pin zip-it-and-ship-it to v5.4.1

- packages/config/package.json
Empty commit to trigger a release for https://github.com/netlify/build/pull/4176
> fix(config-redirects): revert 216213fc2f6f5ff9b61c3bb3a71afac7d7099ebf

- packages/build/tests/edge_handlers/tests.js
Extracted from https://github.com/netlify/build/pull/4212 to fix some flaky tests
---
> test: fix flaky tests

- packages/config/docs/file_paths.md
- packages/config/docs/main.md
This adds some documentation about `@netlify/config`. This is intended for anyone working on this repository.
---
> chore: document `@netlify/config`

- packages/build/docs/errors.md
Fixes https://github.com/netlify/build/issues/1837
This adds some documentation about how errors are handled and reported in Netlify Build. This is intended for anyone working on this repository.
---
> chore: add documentation about error handling and monitoring

- packages/build/docs/plugins.md
This documents Build plugins, for developers contributing to this repository.
---
> chore: add documentation about Build plugins

- packages/build/docs/flow.md
This documents the main flow and steps of Netlify Build.
This also includes some of the main steps of buildbot, from a Netlify Build standpoint.
---
> chore: document Netlify Build main flow and steps

- package-lock.json
- packages/build/package.json
Updates the versions of `@netlify/build` and `@netlify/config` in the lockfile.
> fix: update `@netlify/config` to 18.0.0

- packages/build/src/steps/run_core_steps.js
- packages/build/tests/edge_functions/fixtures/functions_invalid/netlify.toml
- packages/build/tests/edge_functions/fixtures/functions_invalid/netlify/edge-functions/functions-1.ts
- packages/build/tests/edge_functions/tests.js
**This PR:**
* Fixes error from reportStatuses by providing an empty array of pluginsOptions
* Handle errors in one place: `executeBuildStep`
---
> fix: fix report errors in runCoreSteps

- packages/build/src/error/monitor/normalize.js
- packages/build/tests/monitor/tests.js
Adds a couple more cases to the error normalisation logic, as well as a unit test.
> feat: improve error normalisation logic

- packages/build/src/core/feature_flags.js
- packages/build/src/plugins_core/edge_functions/index.js
Wraps #4410 behind a feature flag.
> feat: set Edge Bundler system logger behind feature flag

- .eslintrc.cjs
- packages/build/src/core/main.js
- packages/build/src/steps/run_core_steps.js
- packages/build/src/steps/run_step.js
- packages/build/src/steps/run_steps.js
- packages/config/src/bin/flags.js
- packages/config/src/main.js
- packages/config/src/validate/validations.js
Possibly fixes [this issue](https://github.com/netlify/cli/pull/4920#issuecomment-1211080375)
---
> fix: pass system log to runCoreSteps

- package-lock.json
update package-lock so it reflects changes in package.json
---
> chore: update package-lock to include zip-it-and-ship-it with carot

- lerna.json
we do not use lerna anymore. Lerna was removed in #3642
> chore: delete lerna.json

- package-lock.json
- packages/build/src/log/messages/compatibility.js
- packages/build/src/plugins/spawn.js
Improve messaging around runtime log outputs
---
> feat: improve messaging around runtimes in log outputs

- packages/build/src/log/messages/compatibility.js
Add old/existing nextjs plugin to list of supported runtimes, as package rename has been paused by father-time themself.
---
> feat: add existing nextjs plugin as a runtime

- packages/build/src/plugins_core/edge_functions/index.js
Undo changes from https://github.com/netlify/build/pull/4443 as this might actually not be the right way to implement a solution to the issue as we are trying to use a logic that actually is created mostly to work with plugins and this does not seem to do anything because nothing is handling sending the status update to the api.
For work on https://github.com/netlify/pillar-runtime/issues/245
---
> fix: revert feat: use utils.status.show to add no of edge functions to deploy summary (#4443)

- packages/config/src/env/main.js
Fixes #4441 
Adds a null check before converting to string
---
> fix: null check

- packages/build/src/log/messages/compatibility.js
- packages/build/src/log/messages/install.js
- packages/build/src/utils/runtime.js
Add reference to framework runtimes when installing missing packages at start of build process
---
> feat: add reference to runtime when installing missing packages

- packages/build/src/log/messages/install.js
Actually use the length property to check if any runtimes were used
---
> fix: length check for runtimes used

- packages/build/tests/core/tests.js
Fixes failing tests on my M1 mac as there is no node binary for arm64 darwin https://nodejs.org/dist/v4.0.0/
---
> test: fix tests to pass on m1 mac

- .github/workflows/release-please.yml
- package-lock.json
- package.json
- packages/build/package.json
- packages/cache-utils/package.json
- packages/config/package.json
- packages/functions-utils/package.json
- packages/git-utils/package.json
- packages/run-utils/package.json
This PR caches lerna build output
---
> fix: lerna caching

- .github/workflows/pre-release.yml
- .github/workflows/release-please.yml
- ava.base.js
> fix: install then build workspaces

- .circleci/config.yml
Create a github release on publish
---
> chore: create github release on publish

- .release-please-manifest.json
- package-lock.json
- packages/nock-udp/CHANGELOG.md
- packages/nock-udp/LICENSE
- packages/nock-udp/README.md
- packages/nock-udp/ava.config.js
- packages/nock-udp/package.json
- packages/nock-udp/src/main.js
- packages/nock-udp/test/helpers/udp_server.js
- packages/nock-udp/test/main.js
- packages/nock-udp/tsconfig.json
- release-please-config.json
part of #4545 
Furthermore drop node 8 support + move the package to ESModules
---
> fix!: migrate to ESModules and add types + adapt minimum node version

- package-lock.json
- packages/functions-utils/ava.config.js
- packages/functions-utils/package.json
- packages/functions-utils/src/main.ts
- packages/functions-utils/tests/helpers/main.ts
- packages/functions-utils/tests/main.test.ts
- packages/functions-utils/vitest.config.ts
Migrates the tests to typescript + vitest
---
> chore: migrate function-utils to vitest

- package-lock.json
- packages/build-info/package.json
We forgot to add a dependency to the dependencies array which results in 
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@netlify/build-info' imported from /opt/build-bin/get-build-info.mjs
at new NodeError (node:internal/errors:387:5)
at packageResolve (node:internal/modules/esm/resolve:852:9)
at moduleResolve (node:internal/modules/esm/resolve:901:20)
at defaultResolve (node:internal/modules/esm/resolve:1115:11)
at nextResolve (node:internal/modules/esm/loader:163:28)
at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
at link (node:internal/modules/esm/module_job:75:36) {
code: …
```
> fix: add missing dependency yaml

- nx.json
Currently, when renovate updates minor or patch versions it only updates the lock file. The workflow then runs no tests because the package-lock.json file is not a dependency of any project.
This Pr adds all the relevant files from the root as dependencies so any change to them marks all packages as affected, with the exception of the ava base file which only triggers the packages with ava.
---
> chore: correctly add root files as implicit dependencies

- package-lock.json
- packages/build/package.json
- packages/testing/package.json
Renovate couldn't do a proper update of edge-bundler because `@netlify/testing` was not using the right version of `@netlify/config` 😓 I hope this works!
---
> fix: update edge-bundler

- .release-please-manifest.json
- package-lock.json
- packages/build/CHANGELOG.md
- packages/build/package.json
> Release please  branches  main

- packages/build-info/src/context.ts
- packages/build-info/src/get-build-info.ts
- packages/build-info/tests/failing-framework-info.test.ts
- packages/build-info/tests/fixtures/invalid-project/package.json
- packages/build-info/tests/get-build-info.test.ts
- packages/build-info/vitest.config.ts
Fixes https://answers.netlify.com/t/builds-failing-because-they-started-using-npm-instead-of-yarn/79495/21?u=lukas.holzer
cc @ericapisani 
---
> fix: gracefully handle crashing framework info

- .github/workflows/workflow.yml
Let's see if this makes the CI easier to work with.
> chore: retry failed CI runs

- packages/framework-info/src/frameworks/solid-start.json
Reverts #4845. The Solid Start team are going to go back to port `3000`, so just undoing my recent change.
Fixes #4850
---
> fix: Revert "fix: update Solid Start default port (#4845)"

- packages/build-info/src/node/bin.ts
- packages/build-info/src/node/get-build-info.ts
- packages/build-info/tests/__snapshots__/bin.test.ts.snap
- packages/build-info/tests/get-build-info.test.ts
- packages/build-info/tests/pnpm.test.ts
- packages/build-info/tests/yarn.test.ts
This is a prerequisite for https://github.com/netlify/build/pull/4876 to be able to feature flag the change.
we need to first implement the flag before passing it otherwise the command will break with `
Unknown argument: featureFlags`
---
> feat: add feature flagging possibility to build-info

- package-lock.json
- packages/build-info/package.json
- packages/build-info/src/file-system.ts
- packages/build-info/src/metrics.ts
- packages/build-info/src/node/bin.ts
- packages/build-info/src/node/get-build-info.ts
- packages/build-info/src/node/metrics.ts
- packages/build-info/src/package-managers/detect-package-manager.ts
- packages/build-info/src/project.ts
- packages/build-info/tsconfig.json
Enables error reporting to bugsnag for netlify/build-info
Part of https://github.com/netlify/pillar-workflow/issues/1140
---
> feat: add bugsnag error reporting for netlify/build-info

- package-lock.json
- packages/build-info/package.json
- packages/build-info/src/node/bin.ts
- packages/build-info/src/node/feature-flags.ts
- packages/build-info/tests/__snapshots__/bin.test.ts.snap
Prerequisite for https://github.com/netlify/buildbot/pull/2573
Part of https://github.com/netlify/pillar-workflow/issues/1157
---
> feat: use dev cycle feature flagging

- packages/build-info/CHANGELOG.md
- packages/build-info/package.json
Manual release as the revert was not a conventional commit message
-->
---
> chore: release main

- packages/build-info/src/metrics.ts
- packages/build-info/src/node/bin.ts
- packages/build-info/src/node/get-build-info.ts
- packages/build-info/src/node/metrics.ts
- packages/build-info/src/project.ts
- packages/build-info/src/workspaces/detect-workspace.ts
- packages/build-info/tests/failing-framework-info.test.ts
Fixes this bugsnag error: https://app.bugsnag.com/netlify/build-info/errors/6437291649884e0009c582a7#comments
And improve debugging with session and added metadata from https://github.com/netlify/buildbot/pull/2652
---
> feat: improve bugsnag reporting and fix error

- packages/config/src/api/site_info.js
Fixes a typo for the API to work properly
---
> fix: fix typo

- packages/build-info/src/workspaces/get-workspace-packages.test.ts
- packages/build-info/src/workspaces/get-workspace-packages.ts
Fixes https://app.bugsnag.com/netlify/build-info/errors/647c4b98d3375400080ac93c?event_id=647c4b9800bd6f719ef70000&i=em&m=nw
---
> fix: fixes an issue where it broke if no patterns are provided

- packages/build/src/core/build.ts
- packages/build/src/core/flags.js
- packages/build/src/log/messages/config.js
- packages/build/src/steps/core_step.ts
- packages/build/src/steps/get.js
- packages/build/src/steps/run_step.ts
- packages/build/src/steps/run_steps.js
- packages/build/tests-metadata.json
The minimal PR for passthrough of our already existent value sent from BB. Consumption of this data to follow.
Tests already assert not impact to the value existing.
---
> feat: Passthrough explicitSecretKeys field

- packages/build-info/src/settings/get-toml-settings.ts
The @netlify/build-info package has to be platform independent otherwise we are causing issues in the react-ui
---
> fix: remove node specific dirname

- packages/build-info/src/node/__snapshots__/get-build-info.test.ts.snap
- packages/build-info/src/node/get-build-info.test.ts
- packages/build-info/src/node/get-build-info.ts
- packages/build-info/src/project.ts
- packages/build-info/src/runtime/brew.test.ts
- packages/build-info/src/runtime/brew.ts
- packages/build-info/src/runtime/cask.test.ts
- packages/build-info/src/runtime/cask.ts
- packages/build-info/src/runtime/go.test.ts
- packages/build-info/src/runtime/go.ts
- packages/build-info/src/runtime/index.ts
- packages/build-info/src/runtime/java.test.ts
- packages/build-info/src/runtime/java.ts
- packages/build-info/src/runtime/node.test.ts
- packages/build-info/src/runtime/node.ts
- packages/build-info/src/runtime/php.test.ts
- packages/build-info/src/runtime/php.ts
- packages/build-info/src/runtime/python.test.ts
- packages/build-info/src/runtime/python.ts
- packages/build-info/src/runtime/ruby.test.ts
- packages/build-info/src/runtime/ruby.ts
- packages/build-info/src/runtime/runtime.ts
- packages/build-info/src/runtime/rust.test.ts
- packages/build-info/src/runtime/rust.ts
- packages/build-info/src/runtime/swift.test.ts
- packages/build-info/src/runtime/swift.ts
- packages/build-info/tests/bin.test.ts
Part of https://github.com/netlify/buildbot/issues/2772
This PR adds lang-runtime to build-info for consumption in buildbot.
---
> feat: detect lang runtime

- packages/build-info/src/node/get-build-info.ts
- packages/build-info/tests/bin.test.ts
Places language detection outside the feature-flag
---
> chore: place outside ff

- packages/build-info/src/frameworks/index.ts
- packages/build-info/src/settings/get-build-settings.ts
> fix: export PollingStrategies and getSettings as part of the public api

- packages/build-info/src/get-framework.ts
Needed for the CLI
Technically this would be a breaking change but as we are the only consumers and the function is not used I would ignore it for now.
---
> fix: fix return type of get framework to return the class

- packages/build-info/src/build-systems/package-managers.test.ts
- packages/build-info/src/build-systems/package-managers.ts
- packages/build-info/src/node/__snapshots__/get-build-info.test.ts.snap
- packages/build-info/src/settings/get-build-settings.test.ts
As suggested by @ascorbic let's update the build command for pnpm workspaces to build the dependent projects as well.
See this [slack thread](https://netlify.slack.com/archives/C048U1XSHMX/p1689694672417109) for more info
See the official reference: https://pnpm.io/filtering#--filter-package_name-1
---
> feat: update pnpm build command for workspaces to build dependents

- packages/build-info/src/build-systems/nx.test.ts
- packages/build-info/src/build-systems/nx.ts
- packages/build-info/src/frameworks/framework.ts
- packages/build-info/src/get-framework.ts
- packages/build-info/src/project.test.ts
- packages/build-info/src/project.ts
- packages/build-info/src/settings/get-build-settings.test.ts
- packages/build-info/src/workspaces/detect-workspace.ts
- packages/build-info/tests/fixtures/nx-integrated-old/workspace.json
Fixes https://github.com/netlify/build/issues/5166
Detect frameworks inside nx-integrated through the executor field instead of relying on the regular framework detection, as this is inaccurate.
If it's not a forced framework through the executor we fallback on the regular detection
---
> fix: fix nx-integrated detection via forced framework

- packages/build-info/src/project.ts
- packages/build-info/src/settings/get-build-settings.test.ts
- packages/build-info/src/settings/get-build-settings.ts
This is needed for the CLI to make it possible to run from any directory
---
> feat: make getBuildSettings accept an optional package parameter

- packages/build-info/src/settings/get-build-settings.ts
> fix: fixes an issue where an empty packagePath was ignored

- packages/build/src/log/description.ts
This is needed when we use a detected command inside the CLI so we want to identify it.
This is needed for https://github.com/netlify/cli/pull/5816
When running `ntl build` in a project where no build command is specified over the toml file.
---
> feat: add new command origin

- packages/build-info/src/frameworks/astro.test.ts
- packages/build-info/src/frameworks/astro.ts
Update `astro` ports for their `3.x.x` release
Docs ref: https://docs.astro.build/en/guides/upgrade-to/v3/#changed-default-port-3000
---
> feat: udpate astro ports for 3.x.x

- packages/build/src/install/missing.js
> fix: check testOpts properly in rationalising integrations

- packages/build-info/src/runtime/php.test.ts
- packages/build-info/src/runtime/php.ts
It seems there was a typo (unless I'm missing something) in `composer.json`
---
> fix: typo in PHP detection

- packages/build/types/netlify_plugin_constants.d.ts
Fixes #FRA-76
Updates types for the Netlify API Plugin Constants
> chore: add netlify api constant types

- packages/build/types/netlify_plugin_options.d.ts
Quick PR to add feature flags types
> chore: add feature flags to types

- packages/build/src/error/types.ts
Tiny follow up to - https://github.com/netlify/build/pull/5381
---
> fix(build-error): add core step id to the build error type and traces

- package-lock.json
- packages/build/package.json
Related wtih COM-110 - https://linear.app/netlify/issue/COM-110/make-opentelemetry-an-optional-dependency-in-build - make `@netlify/opentelemetry-sdk-setup` an optional peer dependency:
- https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependencies
---
> fix(build): add otel sdk setup as an optional peer dependency

- packages/opentelemetry-sdk-setup/src/bin.ts
Skips otel logic entirely (including pkg.json reading) if the enabled property is false.
---
> fix(otel-sdk-setup): skip sdk setup entirely if disabled

- packages/build/src/core/types.ts
> fix: update types to include the packagePath on the build flags

- packages/build-info/src/build-systems/nx.ts
Fixes https://app.bugsnag.com/netlify/build-info/errors/64c76ba46be3700008fc9770?filters[error.status]=for_review&filters[event.since]=30d&filters[app.release_stage]=production&event_id=65b90c1800d27f645f1d0000
---
> feat: add latest nx executors to detection

- packages/build/src/steps/core_step.ts
- packages/build/src/steps/plugin.js
- packages/build/src/steps/update_config.js
> feat: stop logging internal config mutations

- packages/build/src/steps/get.ts
- packages/build/tests/functions/fixtures/functions_leftover/.netlify/edge-functions/leftover.mjs
- packages/build/tests/functions/fixtures/functions_leftover/.netlify/functions-internal/leftover.mjs
- packages/build/tests/functions/fixtures/functions_leftover/manifest.yml
- packages/build/tests/functions/fixtures/functions_leftover/netlify.toml
- packages/build/tests/functions/fixtures/functions_leftover/plugin.mjs
- packages/build/tests/functions/tests.js
> fix: don't wipe functions created in `onPreDev`

- packages/build/src/plugins/resolve.js
- packages/build/tests/install/tests.js
- packages/config/tests/api/tests.js
These feature flags are enabled since September 2023. Time to remove them
---
> fix: remove cli_fetch_integrations and cli_fetch_integrations

- package-lock.json
- packages/opentelemetry-sdk-setup/package.json
> fix(deps): bump honeycomb-otel

- package-lock.json
- packages/build/package.json
- packages/build/src/plugins/compatibility.ts
- packages/build/src/plugins/expected_version.ts
- packages/build/src/plugins/manifest/main.ts
- packages/build/src/plugins/options.ts
- packages/build/src/plugins/plugin_conditions.ts
- packages/build/src/utils/json.ts
- packages/build/src/utils/package.ts
- packages/framework-info/package.json
- packages/framework-info/src/context.ts
- packages/framework-info/src/core.ts
- packages/framework-info/src/package.ts
- packages/opentelemetry-sdk-setup/package.json
- packages/opentelemetry-sdk-setup/src/sdk-setup.ts
- packages/opentelemetry-sdk-setup/src/util.ts
> fix: revert revert of `read-pkg-up` update

- packages/config/package.json
- packages/config/src/mutations/apply.js
This enables visual-editor plugin to inject snippet into html in dev mode.
Related PRs:
- https://github.com/netlify/cli/pull/6686
> feat: added dev.processing.html.injections to mutable props [CRE-1203]

- packages/zip-it-and-ship-it/src/main.ts
Exports types that the Netlify CLI needs.
> feat: export types

- packages/config/src/api/site_info.ts
- packages/config/tests/api/tests.js
This ensures that when we query what integrations are installed for a team, we ignore the integration if it's the integration that is hosted on the site that is running the build.
---
> feat: exclude integration site id from meta request

- package-lock.json
- packages/zip-it-and-ship-it/package.json
Update version of serverless-functions-api to incorporate a fix for incident 214
---
> fix: bump serverless-functions-api version with the fix

- .github/workflows/workflow.yml
- packages/edge-bundler/node/bridge.ts
https://linear.app/netlify/issue/FRP-775/deno-cli-v1450-causing-issues
> fix: pin version of Deno CLI

- packages/config/src/api/site_info.ts
- packages/config/tests/api/tests.js
> feat: change meta endpoint to pass siteid as a url parameter

- packages/build-info/src/frameworks/next.ts
next@15 added support for `next.config.ts`: https://nextjs.org/blog/next-15#support-for-nextconfigts
---
> fix: detect next if typescript config file is used

- .github/workflows/workflow.yml
Optimistic attempt to see if https://github.com/netlify/build/actions/runs/13133810932/job/36646084127?pr=6049 is by any chance caused by corepack problems ( https://github.com/nodejs/corepack/issues/612 )
---
>  chore: update corepack from version bundled with node

- .eslintrc.cjs
To finish https://github.com/netlify/build/pull/6157
---
> fix: add the right vitest linter to the eslint config

- packages/build/src/log/messages/install.js
We log that we're installing integrations but we call em extensions now! For a long time! Ahh!
---
> fix: changing wording to extensions instead of integrations

- packages/build/src/types/netlify_plugin_options.ts
This adds some missing types for the `extensionMetaData`.
---
> fix: add extra types for extensionMetaData

- packages/build-info/src/frameworks/expo.ts
See https://docs.expo.dev/guides/publishing-websites/#create-a-build.
These changed at some point. We could do conditional settings per expo version, but that probably isn't worth it at this point.
> fix(build-info): update expo build config

- packages/build/src/plugins_core/secrets_scanning/secret_prefixes.ts
- packages/build/src/plugins_core/secrets_scanning/utils.ts
Fixes https://linear.app/netlify/issue/WRFL-2548/expand-secret-prefixes
Expands the list of secret prefixes the enhanced scan will check for
---
> feat: expand secret prefixes

- package-lock.json
- packages/zip-it-and-ship-it/package.json
- packages/zip-it-and-ship-it/src/runtimes/go/index.ts
- packages/zip-it-and-ship-it/src/runtimes/node/index.ts
- packages/zip-it-and-ship-it/src/runtimes/node/utils/zip.ts
No changes, just package file rename to resolve renovate warning
---
> chore: cpy-file was renamed to copy-file

- packages/zip-it-and-ship-it/src/runtimes/node/utils/zip.ts
Introduced in  #6334 (while reverting #6287)
---
> fix: update import statement - `cp-file` was renamed to `copy-file`

- .gitignore
- lerna.json
- package-lock.json
- package.json
Upgrades our lerna package to the latest version
Notes:
- `useNx` is now true by default
- `useWorkspaces` was removed
---
> chore(deps): upgrade to lerna v8

- nx.json
Resolves the following warning:
```
NX   Using `implicitDependencies` for global implicit dependencies configuration is no longer supported.
Use "namedInputs" instead. You can run "nx repair" to automatically migrate your configuration.
For more information about the usage of "namedInputs" see https://nx.dev/deprecated/global-implicit-dependencies#global-implicit-dependencies
```
---
> chore: repair nx config

- package-lock.json
- packages/js-client/README.md
- packages/js-client/package.json
- packages/js-client/src/types.ts
Reverts netlify/build#6383
More code changes needed before this change can land, rolling back
> Revert "fix: remove node-fetch from js-client package"

- packages/js-client/src/types.ts
Purpose of this change is to fix the changelog in the release branch
---
> fix: revert "remove node-fetch from js-client package (#6383)"

- packages/cache-utils/tests/dir.test.ts
deprecated with - https://github.com/vitest-dev/vitest/pull/4400
so we use modern api there
---
> test: replace deprecated `SpyInstance` with `MockInstance`

- packages/edge-bundler/node/bundler.test.ts
- packages/edge-bundler/node/formats/tarball.ts
- packages/edge-bundler/node/utils/fs.ts
- packages/edge-bundler/node/utils/sha256.ts
The edge function tarballs were being generated with incorrect paths. This PR fixes that.
> fix: fix generation of EF tar file

- package-lock.json
- packages/js-client/package.json
- packages/js-client/src/methods/params.js
ref https://github.com/e18e/ecosystem-issues/issues/156
---
:badger:
> fix: remove lodash-es
