netlify/build

- README.md
- docs/creating-a-plugin.md
- package.json
Follow-up on #107.
This documents some npm keywords and GitHub topics that plugin authors should add to their plugins, so that users can easily find/search them.
> Add recommendations on keywords to add to plugins

- .gitignore
- package.json
This speeds up ESLint by using caching.
This also print errors with the source code lines that failed.
> Speed up linting

- .editorconfig
This fixes some cross-platform issues when developing on Windows by adding an [`.editorconfig` file](https://editorconfig.org).
> Improve Windows development

- docs/creating-a-plugin.md
- packages/build/src/plugins/child/load.js
- packages/build/src/plugins/child/logic.js
- packages/build/src/plugins/child/run.js
- packages/netlify-plugin-no-more-404/index.js
- packages/netlify-plugin-notifier/index.js
We are passing the `pluginConfig` to plugins initialization functions, but we should also be passing the `config`. 
For example I needed this when working on the `functions` core plugin.
> Pass `config` to plugin initialization function

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/plugins/functions/index.js
This adds the improvements coming from https://github.com/netlify/zip-it-and-ship-it/pull/48.
I.e. this adds the following improvements to Netlify Functions:
- use async I/O everywhere instead of sync I/O
- when the destination folder does not exist, it is created instead of throwing an error
- allow `functionFolder/index.js` ([this works](https://github.com/netlify/zip-it-and-ship-it/pull/48#issuecomment-533510640) with current BuildBot and API)
- [allow requiring files](https://github.com/netlify/zip-it-and-ship-it/pull/49) outside of the function directory
- allow Node.js `>= 8.3.0` (instead of `>= 8.5.0`)
In addition the following bugs are fixed:
- missing optional dependencies should not throw. However, at the moment, this only works for optional dependencies of dependencies, not …
> Improve Netlify Functions support

- README.md
- docs/creating-a-plugin.md
- examples/example-two/README.md
- packages/build/src/core/lifecycle.js
- packages/build/src/scaffold/main.js
This fixes the following spelling typos:
- `javascript` -> `JavaScript`
- `dependancies` -> `dependencies`
> Fix spelling

- packages/netlify-plugin-lighthouse/README.md
- packages/netlify-plugin-monorepo/README.md
- packages/netlify-plugin-svgoptimizer/README.md
This simplifies some `README` of plugins by removing `enabled: true` since this is the default value.
> Simplify some plugins `README`

- packages/build/src/log/patch.js
Secrets were being redacted as `[secure]` inside user commands but as `[secrets]` inside plugins. This PR makes it more consistent.
> Fix secrets redacting

- packages/build/src/core/instructions.js
- packages/build/src/log/patch.js
- packages/build/src/log/stream.js
- packages/build/src/plugins/ipc.js
Fixes #343.
The current BuildBot is not handling child processes streaming properly. This fixes it:
- when run in the BuildBot, plugins output is printed all at once (each time some plugin lifecycle has eneded)
- when run locally, plugins output is streamed
> Fix output streaming in the BuildBot

- packages/build/src/log/main.js
This fixes internal error stack traces being printed when a lifecycle command fails without printing any output.
> Fix error stack traces

- packages/build/src/core/dry.js
- packages/build/src/log/main.js
This fixes the following issues with dry run:
- it did not work when 0 hooks were run (e.g. empty configuration file)
- the header was misaligned when all hook names were very short
> Fix dry run

- packages/build/src/core/main.js
At the moment running dry run programmatically calls `process.exit()`. `process.exit()` should only be called when dry run is done through the CLI.
> Fix dry run exit

- packages/build/src/core/main.js
- packages/config/package-lock.json
- packages/config/package.json
- packages/config/path.js
This allows using several base directories to search for the configuration file when using `getConfigPath()`. For example the CLI searches first for `process.cwd()` then for `site.root`.
> Improve `--config` option resolution

- packages/build/src/core/main.js
- packages/build/src/log/main.js
- packages/build/src/utils/telemetry/index.js
This moves lines of code around to keep the logging file only related to console logging.
> Move some code around

- packages/build/tests/README.md
This adds a `README` with documentation about how to write and debug our integration tests.
> Add documentation about the integration tests

- .github/workflows/workflow.yml
This improves the CI speed by reducing the matrix size while still checking across OS and on both oldest and newest Node.js versions.
> Improve CI speed

- ava.config.js
This improves the CI speed by increasing parallelism. Ava defaults to 2 test files in parallel at once when run in CI.
> Improve CI speed more

- packages/build/tests/README.md
- packages/build/tests/helpers/main.js
This adds a `debug` option to test helpers to print the non-normalized output of `netlify-build`.
The option is documented in the tests `README.md`.
> Add `debug` option to test helpers

- packages/build/tests/helpers/main.js
This adds a 10 minutes test timeout, to better catch bugs that make the Build hang.
> Add test timeout

- packages/build/src/plugins/child/constants.js
This fixes a bug in `netlify-plugins-core`.
This was not caught by the tests because the line of code is behind a `if (isNetlifyCI())` condition.
> Fix netlify-plugins-core

- packages/build/src/plugins/child/main.js
When a promise is resolved twice, an error is currently printed. This PR fixes this.
> Fix process errors logging

- examples/example-two/package-lock.json
- examples/example-two/package.json
The examples (`examples/example-two`, run by `npm run example`) does not currently work on Windows. This PR fixes this.
> Make example work on Windows

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/plugins/functions/index.js
Since the introduction of the `FUNCTIONS_SRC` constant, `netlify-functions-core` stopped working on Windows due to the introduction of OS-specific path delimiters. This PR fixes that.
> Fix netlify-functions-core on Windows

- packages/build/src/core/instructions.js
- packages/build/src/log/stream.js
The output from plugins was sometimes missing due to child process's output not being flushed out. This PR fixes this.
> Fix plugin output sometimes missing

- packages/build/src/plugins/ipc.js
This fixes the exit handler for child processes which was not doing cleaning up properly.
> Improve child processes exit handler

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/core/instructions.js
- packages/build/src/plugins/child/main.js
- packages/build/src/plugins/ipc.js
- packages/build/src/plugins/load.js
The current plugins IPC relies on the assumption that a plugin's hooks are run serially. This won't be true anymore once we introduce plugins parallelization. This would lead to plugin hooks being resolved in random order, making the build crash.
This PR solves this problem by introducing multiplexing to plugins (similar to how HTTP/2 does it).
> Improve parent/child IPC for plugins parallelization

- packages/build/tests/helpers/main.js
This adds a `snapshot` parameter to the test utility to configuring snapshots.
> Add `snapshot` test parameter

- packages/build/src/core/bin.js
The builds logs are not always flushed when the process exits. This leads to the BuildBot logs to be interleaved with Netlify Build. This PR fixes this.
> Fix log flushing issue

- packages/build/tests/helpers/normalize.js
This fixes an issue related to a bug in [nyc](https://github.com/istanbuljs/istanbuljs/issues/141). 
This would make tests randomly fail on Windows in CI. This PR fixes this.
> Fix test coverage-related bug

- .github/workflows/workflow.yml
Coveralls test coverage currently pick up only one of the OS test coverage (usually Linux) instead of merging all coverage maps. This is due to a long-standing bug in Coveralls.
> Try fixing Coveralls test coverage

- .github/workflows/workflow.yml
- README.md
- codecov.yml
- package.json
- scripts/coverage.sh
This replaces Coveralls with Codecov. 
Coveralls has some bugs that break parallel test coverage:
- https://github.com/coverallsapp/github-action/issues/18
- https://github.com/coverallsapp/github-action/issues/13
This means we are only getting test coverage from the fastest build, usually Linux, and not from Windows and Mac.
Using Codecov fixes that.
> Add Codecov

- packages/build/src/plugins/child/constants.js
The cache constant was initialized to `/opts/build/cache` instead of `/opt/build/cache`.
@jlengstorf
> Fix cache constant

- packages/build/tests/helpers/normalize.js
This fixes the normalization performed in test snapshots related to time durations.
> Fix time duration normalization in tests

- codecov.yml
Codecov adds PR comments but this is a little spammy. Test coverage can already be seen from PR statuses.
> Remove Codecov PR comments

- codecov.yml
At the moment, PRs fail when test coverage decreases by any percentage. This changes it to only fail when test coverage drops by more than 5% (which should indicate an anomaly).
> Do not make PR fail when test coverage decreases

- packages/netlify-plugin-axe/index.js
This fixes the Axe plugin to use the current directory (which is the base directory) instead of `CONFIG_PATH`.
> Fix Axe plugin to use the current directory

- packages/build/src/core/dry.js
- packages/build/src/core/instructions.js
- packages/build/src/core/main.js
- packages/build/src/log/main.js
- packages/build/src/telemetry/index.js
The number of instructions is used in several places: dry logging, normal logging, error handling, etc.
This PR does a small refactoring to add an `instructionsCount` variable to contain that information so it's consistent across the code base.
> Refactor instructions count

- packages/build/src/core/instructions.js
- packages/build/src/core/main.js
- packages/build/src/log/main.js
Currently, if two plugins have an `onError` hook, and one of them throws an error, the other `onError` is not guaranteed to complete.
This PR fixes this by ensuring that if `onError` hooks fail, they first wait for other `onError` to complete before propagating their error. The error thrown inside the `onError` hook is eventually propagated and printed on logs, for users to see what's wrong with their error handling.
Tagging @sdras since we discussed this issue.
> Improve error handling

- packages/build/src/plugins/ipc.js
`onError` hooks receive the `error` instance as argument:
```js
module.exports = {
name: 'netlify-plugin-example',
onError({ error }) {
console.error(error)
}
}
```
However plugins are spawned as child processes. The parent process communicates to them through [`child_process` `ipc`](https://nodejs.org/api/child_process.html#child_process_options_stdio) which uses JSON as the message format. This leads to `error` instances being converted to plain objects, which makes them lose their `Error` prototype, `message`, `name` and `stack` properties.
This PR fixes this by serializing and parsing error instances ourselves.
Note that Node.js added support for `v8` serialization (based on the HTML structured clone algorithm) [**yesterday**](https://github.com/nodejs/node/blob/master/doc/changelogs/C …
> Fix `onError` hook

- packages/netlify-plugin-axe/index.js
- packages/netlify-plugin-axe/package-lock.json
- packages/netlify-plugin-axe/package.json
This improves the Axe plugin:
- use the new `plugin.config` property
- use peerDependencies 
- use async I/O
- remove unnecessary chmod call
> Improve Axe plugin

- packages/build/tests/plugins/load/fixtures/early_exit/plugin.js
A test was failing on Windows due to child process termination being different on Windows and on Unix.
> Fix tests on Windows

- packages/build/tests/plugins/load/tests.js
This fixes some issues on Windows since it terminates processes differently.
> Fix cross-platform issue

- packages/build/src/log/stream.js
- packages/build/tests/plugins/run/tests.js
This a partial fix to plugin outputs being truncated when they are too big.
> Fix plugins with big output

- packages/config/src/validate/helpers.js
This enhances the helper that validates property names in the configuration, in order to support legacy/deprecated property names.
> Allow legacy properties when validation property names

- packages/config/src/validate/example.js
At the moment examples used on configuration validation are static. This PR allows them to be dynamic functions instead, taking the failed property as input.
> Allow dynamic examples in configuration validation

- packages/config/src/validate/main.js
At the moment error messages thrown during configuration validation are static. This PR enhances them to allow dynamic error messages, taking the failed property as input.
> Dynamic configuration validation error messages

- packages/config/src/validate/main.js
- packages/config/src/validate/validations.js
At the moment configuration validation failures always result in a build error. This enhances this by allows warning messages instead, for example for deprecated properties, that do not make builds fail.
> Allow warning messages during configuration validation

- packages/config/src/validate/helpers.js
This adds a configuration validation helper for the generic case of properties being renamed.
> Add configuration validation helper for deprecated properties

- packages/config/src/lifecycle.js
- packages/config/src/normalize.js
- packages/config/src/validate/validations.js
This allows users to use deprecated `build.lifecycle.event` which will be normalized to the new `build.lifecycle.onEvent` instead.
> Normalize `build.lifecycle.event` to `build.lifecycle.onEvent`

- packages/config/src/validate/validations.js
This prints a warning message when user uses the deprecated `build.lifecycle.event` instead of the new `build.lifecycle.onEvent`.
> Print warning message when user uses deprecated `build.lifecycle.event`

- packages/config/src/lifecycle.js
- packages/config/src/normalize.js
This allows users to write lifecycle events case-insensitively. For example `build.lifecycle.onbuild` would work like `build.lifecycle.onBuild`.
> Normalize lifecycle event case

- packages/config/src/validate/helpers.js
This enhances the configuration validation helpers by allowing mapping configuration properties.
> Enhance configuration validation helpers

- packages/config/src/validate/validations.js
This allows lifecycle events to be case-insensitive.
> Do not throw errors when lifecycle events case is lowercase

- packages/config/src/index.js
This exports the legacy lifecycle names from `@netlify/config` so that `@netlify/build` can use them to normalize and validate plugin event handlers.
> Export legacy lifecycle names from `@netlify/config`

- packages/build/src/plugins/child/validate.js
This makes validation of event handler names in plugins handle legacy names (`plugin.build` instead of `plugin.onBuild`).
> Fix plugin event handler names validation

- packages/build/src/plugins/child/load.js
- packages/build/src/plugins/child/normalize.js
This normalizes plugin event names so that plugin authors that used the legacy `plugin.event` methods do not have compatibility issues.
Related to #531.
> Normalize plugin event names

- packages/build/tests/config/normalize/fixtures/case/netlify.yml
- packages/config/src/lifecycle.js
This makes `config.build.lifecycle` events case-insensitive.
> Make lifecycle events case-insensitive

- package.json
This removes `npm run example` due to `example-two` being removed by #550.
> Remove `npm run example`

- packages/build/tests/README.md
- packages/build/tests/helpers/main.js
This PR improves test snapshots helpers by adding a `normalize` option to turn it off.
> Improve test snapshots normalization

- packages/build/tests/log/stack/fixtures/config_validation/netlify.yml
- packages/build/tests/log/stack/fixtures/lifecycle/file.js
- packages/build/tests/log/stack/fixtures/lifecycle/netlify.yml
- packages/build/tests/log/stack/fixtures/load/netlify.yml
- packages/build/tests/log/stack/fixtures/load/plugin.js
- packages/build/tests/log/stack/fixtures/plugin/netlify.yml
- packages/build/tests/log/stack/fixtures/plugin/plugin.js
- packages/build/tests/log/stack/tests.js
This adds some tests covering the normalization/cleaning we do on error stack traces to keep logs as user-friendly as possible.
> Add tests covering stack traces normalization

- .gitignore
This adds `.yarn-error.log` to `.gitignore` since it sometimes created for example when the network connection is down.
> Add `.yarn-error.log` to `.gitignore`

- packages/build/tests/helpers/main.js
This fixes some tests that sometimes randomly fails when npm or yarn encounters some network connection issues.
> Fix tests failing on npm/yarn network connection

- packages/build/src/core/main.js
- packages/build/src/plugins/install.js
- packages/build/src/plugins/options.js
This moves the logic related to plugin resolution closer to plugin loading instead of making it part of the plugin dependencies installation logic.
> Move some lines of code

- .nycrc.yml
- codecov.yml
- packages/build/src/core/bin.js
- packages/build/src/core/main.js
- packages/build/src/log/redact.js
- packages/build/src/plugins/options.js
This fixes test coverage by skipping few cases that are temporary (feature flags) and will be removed soon.
> 100% test coverage

- CONTRIBUTING.md
This fixes `CONTRIBUTING.md` as a follow-up of #602.
> Fix `CONTRIBUTING.md` documentation

- packages/build/tests/helpers/main.js
This fixes a test that was randomly failing when there was a network connection with npm.
Reference: https://github.com/netlify/build/pull/602/checks?check_run_id=346368546
> Fix test failing due to npm network connection

- packages/build/tests/README.md
This updates the documentation about how testing works for users who cannot run Node.js binaries locally.
> Update tests documentation to use `npx ava`

- examples/backwards-compat/README.md
The toml for backwards compatibility is currently an older version and causes errors in the current version of netlify build cli, specifically the error mentions incorrect syntax.
This addresses the comments in [this issue](https://github.com/netlify/build/issues/337#issuecomment-545211855) and updates the docs accordingly
I've updated the docs to reflect the changes to the toml
**Checklist**
> Update toml to use correct syntax

- packages/cache-utils/package-lock.json
- packages/cache-utils/package.json
- packages/cache-utils/src/hash.js
Caching was crashing when trying to cache directories with lots of big files. This PR fixes it by: 
- using streaming when files are big
- limiting the max concurrency to the number of CPUs cores
- using a faster hashing algorithm
> Fix crashes with caching

- packages/build/tests/utils/cache/fixtures/hash/plugin.js
- packages/build/tests/utils/cache/fixtures/hash_big/plugin.js
- packages/build/tests/utils/cache/fixtures/hash_directory/plugin.js
- packages/cache-utils/src/hash.js
- packages/cache-utils/src/main.js
- packages/cache-utils/src/manifest.js
This makes saving cache faster in CI, since CI moves files, which is faster to do than computing hashes.
> Make saving cache faster in CI

- docs/creating-a-plugin.md
- packages/build/src/plugins/child/constants.js
- packages/cache-utils/README.md
This is adding `CACHE_DIR` constant back in.
Even with caching utilities, it's handy to be able to do things with cache dir location.
Was there a specific reason we removed this? @ehmicky
> Restore cache constant

- packages/build/tests/plugins/install/tests.js
This fixes a test that sometimes fails on Windows due to Windows locking directories few milliseconds after their files have been read/write, which creates a `EBUSY` error.
> Fix test that sometimes fails on Windows

- packages/build/tests/config/load/tests.js
- packages/build/tests/helpers/main.js
- packages/build/tests/plugins/constants/tests.js
- packages/build/tests/plugins/functions/tests.js
- packages/build/tests/plugins/install/tests.js
Tests sometimes fail on Windows due to directory locking (`EBUSY`). A previous PR fixed it for one specific test, but this is a more generic problem. This PR introduces a helper function to solve this for all tests.
> Fix test failing on Windows

- packages/cache-utils/README.md
- packages/functions-utils/README.md
- packages/git-utils/README.md
- packages/run-utils/README.md
It is not required to run `npm install` anymore to use utilities.
This PR fixes documentation to reflect this.
> Fix utilities `README`

- packages/build/tests/helpers/main.js
This fixes the git user name being `test` during tests, which shows up in GitHub actions and Codecov UI.
> Fix git user name

- packages/cache-utils/README.md
This PR improves the `README` of the cache utility based on @jlengstorf feedback in https://github.com/netlify/build/issues/216#issuecomment-574391653.
It moves most examples to the relevant `API` section so users don't need to scroll up and down.
It does not modify the content itself.
[Quick link](https://github.com/netlify/build/blob/docs%2Fimprove-git-readme/packages/cache-utils/README.md) to the `README`.
> Improve the `README` of the cache utility

- packages/build/src/utils/is-netlify-ci.js
- packages/build/tests/cache/main/tests.js
- packages/build/tests/log/colors/tests.js
- packages/build/tests/plugins/constants/tests.js
- packages/build/tests/plugins/run/tests.js
- packages/build/tests/utils/cache/tests.js
- packages/cache-utils/src/ci.js
The CI detection internal logic currently relies on `DEPLOY_PRIME_URL`. We should instead rely on the `NETLIFY=true` environment variable, which purpose is specifically to detect whether we are inside the Netlify CI.
Related to #734.
> Fix CI detection

- packages/build/src/core/commands.js
- packages/build/src/log/main.js
- packages/build/src/log/package.js
Update error logging to include package.json information including git url, npm url, issues url, & version of plugin info.
Fixes https://github.com/netlify/build/issues/764
Remote CI will see the following, with a big block to determine where the error logs end as well. This is due to additional logs spit out afterwards by buildbot
Local view is less verbose, to allow devs to focus on the error & stack trace
> Update error logging

- packages/build/src/log/empty.js
- packages/build/src/log/main.js
- packages/build/src/log/plugin_error.js
- packages/build/tests/helpers/normalize.js
Some empty lines are missing in logs in production due to a bug in the buildbot (https://github.com/netlify/buildbot/issues/595).
This PR implements a workaround for this while this bug is being fixed.
> Fix missing empty lines in logs

- packages/build/tests/helpers/main.js
If a developer has the `NETLIFY_AUTH_TOKEN` environment variable, it is leaked when developing locally. This PR fixes that.
> Fix exposing API tokens locally

- packages/build/src/core/config.js
Some CLI flags can be either an empty string or `undefined`. This PR normalizes them to `undefined` only for consistency purpose.
> Small refactoring of empty values

- packages/build/src/core/config.js
- packages/build/src/core/main.js
- packages/build/src/core/site_info.js
- packages/build/src/plugins/child/constants.js
- packages/build/src/plugins/load.js
- packages/build/src/telemetry/index.js
This PR makes builds load the current Netlify Site information so it can be used in other parts of the build. 
Since this is currently only meant to be used for environment variables inside local builds, and calling the `getSite` API endpoint is slow, this is only performed in local builds that have the required information to perform the call. Otherwise, it is silently ignored.
> Load Netlify Site information in local builds

- packages/build/tests/helpers/normalize.js
This fixes a test that was failing on Node `8.3.0` due to Node 10 changing adding new properties to some types of errors.
> Fix test failing on Node `8.3.0`

- packages/build/src/error/serialize.js
- packages/build/src/log/main.js
- packages/build/src/plugins/error.js
This is a small refactoring of the error logic to accommodate needs for a follow-up PR. This does not change behavior.
> Small error logic refactoring

- packages/build/src/plugins/child/main.js
Fixes #820.
This removes the `config` argument passed to plugin event handlers. This has been renamed to `netlifyConfig` and nobody is currently using it.
> Remove backwards compat `config` from plugin lifecycle API

- docs/creating-a-plugin.md
This PR improves our current Markdown documentation related to `package.json` best practices when publishing a Build plugin.
@jlengstorf and @klavavej and working on better documentation, so this is more a temporary improvement in the meantime.
> Improve documentation for plugin authors

- packages/config/src/base_dir.js
- packages/config/src/error.js
- packages/config/src/path.js
- packages/config/src/validate/main.js
Related to #802.
In `@netlify/config`, we currently distinguish between errors that are:
- caused by user, such as configuration file syntax errors
- caused by our code or plugins code, which are most likely bugs
We do this in order to report this differently.
We do it by adding a `type: 'userError'` property to user errors. 
Note: we do this instead of defining a custom `Error` class since it's easier to keep the original error (and its stack trace) this way.
This PR simply refactors the code to provide with a common utility for throwing errors that follow that pattern, instead of adding that `type` property all the times. This is refactoring only, no behavior changes.
> Simplify error handling in `@netlify/config`

- packages/build/src/plugins/child/constants.js
- packages/config/src/files.js
Fixes #665.
Related to #802.
`@netlify/config` is assigning a default value of `build.publish` to the base directory. 
This is what the buildbot does from a logic standpoint. However:
- The CLI needs to know whether `build.publish` was defined or not by the user, because it errors then (unlike the `--prod` CLI flag is used), which is different from what the buildbot is doing (see #665)
- The current buildbot does not assign that default value. Instead, it leaves the value empty. To be on the safe side once the buildbot starts using `@netlify/config`, this PR replicates that behavior.
Note that the `BASE_DIR` constant passed to plugin still has the default value, since it's more convenient for plugin authors.
> Fix default value of `build.publish`

- packages/build/tests/core/telemetry/tests.js
An integration test is currently hanging when run locally (but not in CI) due to an incorrect parameter. This PR fixes that.
The test is meant to perform an invalid HTTP request but the current parameter was actually valid, making the test hang.
> Fix invalid test

- packages/config/src/index.js
This PR improves an error message shown when an error is thrown inside `@netlify/config` but the user is using no configuration file.
> Improve error message in `@netlify/config`

- packages/build/src/core/config.js
- packages/config/src/index.js
Related to #802.
The `context` option defaults to the `CONTEXT` environment variable or to `'production'`.
This default value is assigned inside `@netlify/build`. However this should be assigned by `@netlify/config` instead so that users of both libraries get the correct default value.
> Fix `context` default value

- packages/config/src/files.js
Related to #802.
When `build.base` is defined, `build.functions` and `build.publish` are relative to it. Otherwise they are relative to the repository root directory. This logic is present [in the buildbot](https://github.com/netlify/buildbot/blob/77379b6d05a07355f28f6b725fb3c96cb742a426/bot/configuration.go#L57).
`@netlify/config` replicates this logic, but the current code can be simplified. This PR refactors the code to simplify it, without changing behavior.
> Simplify code related to configuration file paths

- packages/build/tests/config/load/tests.js
- packages/config/src/base_dir.js
- packages/config/src/index.js
Part of #802.
Netlify Build currently ensures that the build directory has read and write permissions.
This behavior is not backward compatible with the buildbot which does not do those permission checks.
A user could technically have no build command and publish a specific directory of the repository source files, hence not require any write permissions for it. Those permissions checks would be breaking to that user.
Therefore this PR is removing those checks.
> Remove permissions checks on build directory

- packages/build/src/core/commands.js
- packages/build/src/core/config.js
- packages/build/src/core/main.js
- packages/build/src/plugins/child/constants.js
- packages/build/src/plugins/child/utils.js
- packages/build/src/plugins/env.js
- packages/build/src/plugins/git.js
- packages/build/src/plugins/install.js
- packages/build/src/plugins/load.js
- packages/build/src/plugins/options.js
- packages/build/src/plugins/spawn.js
- packages/config/src/build_dir.js
- packages/config/src/files.js
- packages/config/src/index.js
We use the internal variable name `baseDir` for what is actually the build directory (not the `base` directory). This is called `buildDir` in the buildbot as well.
This PR renames this variable to avoid confusion. This only renames internal variables that are not exposed to the users.
> Rename `baseDir` to `buildDir`

- packages/build/src/core/main.js
- packages/build/src/plugins/options.js
- packages/build/tests/config/cwd/fixtures/build_base_cwd/netlify.yml
Part of #802.
Most paths inside Netlify Build are relative to the build directory (which is either `build.base` or the repository root directory).
However inside the configuration file, paths should be relative to that configuration file since this is what users are most likely to expect. At the moment, this is only for local plugins paths.
This PR fixes this issue.
> Fix paths resolution inside the configuration file

- packages/build/tests/config/load/tests.js
This removes some dead code in a single test.
This test is using an option (`config`) which has been removed in a previous PR and is not needed anymore for that test.
> Remove some dead code

- packages/config/src/context.js
- packages/config/src/utils/merge.js
Part of #802.
This separates the logic we use to merge configuration objects together into its own utility function.
Merging configuration objects is used in several places:
- when merging `context` configuration
- when merging UI settings
> Add configuration merging logic

- packages/build/src/core/config.js
- packages/build/tests/config/load/tests.js
- packages/config/src/bin/main.js
- packages/config/src/main.js
- packages/config/src/path.js
Part of #802.
When using `@netlify/config`, the `--config` CLI flag should be optional. Most users don't need to specify that flag since we automatically find the configuration file inside the repository root directory or base directory. This means this option should be a named parameter instead of a positional one.
> Make `--config` CLI flag optional

- packages/build/src/log/main.js
An empty line (for cosmetics) is missing between the CLI flags logging and the current directory logging. This PR fixes that.
> Fix missing newline after CLI flags logging

- packages/config/src/bin/main.js
This removes some small dead code.
A `return` statement after `process.exit()` is never reached.
> Remove dead code

- packages/config/src/main.js
Part of #802.
This simplifies the main error message in `@netlify/config` when an error happens during configuration resolution (e.g. parsing error). When the code reaches that point, `configPath` cannot be `undefined` since, if there is no configuration file, no error can be thrown from parsing it. So the code can be simplified a little.
> Simplify some error message in `@netlify/config`

- packages/config/src/options/branch.js
`@netlify/config` uses the `BRANCH` environment variable to figure out branch-specific contexts. If undefined, it is not used. However when set to an empty string, it should behave as if it was `undefined`, which is not the case at the moment. This PR fixes that.
> Fix `BRANCH` environment variable

- packages/build/tests/config/validate/tests.js
When the configuration file has errors or warnings, those are shown in colors. 
This PR adds a test to ensure the colors are correctly shown.
> Add a test for config warning messages colorization

- packages/build/src/core/main.js
Some statements are currently not covered by the top-level error handler.
This PR fixes this.
> Improve error handling at the start of the build

- packages/build/src/core/api.js
- packages/build/src/core/config.js
- packages/build/src/core/site_info.js
An API client is currently created in order to retrieve Site information in local builds (to set some environment variables like `REPOSITORY_URL`).
An upcoming feature (cancelling builds) requires this API client to be made available in order parts of the codebase. This PR implements this.
> Make API client available to the whole codebase

- packages/config/tests/cwd/tests.js
An integration test is randomly failing due to a race condition. This PR fixes this.
> Fix randomly failing test

- packages/config/src/options/main.js
- packages/config/src/utils/is-netlify-ci.js
Trying to address #918.
A user with a Yarn monorepo setup was using the Netlify Build beta and it worked until the latest changes related to configuration file parsing.
The "current directory" which is logged (which actually is what we internally call "base directory") used for the build commands was [correct before](https://app.netlify.com/sites/deputy/deploys/5e6090f7dad16feedd484c8f) (points to the subdirectory) but [not anymore](https://app.netlify.com/sites/deputy/deploys/5e67050ac2b0736048de28b5) (points to project root directory). 
The problem seems to be the following: the latest logic of `@netlify/config` assumes that the buildbot is passing the "Base directory" UI setting using the `--defaultConfig` CLI flag. This is what the buildbot will eventually do (there is ongoing work …
> Fix monorepo support

- packages/build/src/error/clean_stack.js
Stack trace cleaning removes the stack trace lines coming from internal `@netlify/build` code. However the current RegExp was working locally but not when `@netlify/build` is installed as a npm dependency. This PR fixes that.
> Improve stack trace cleaning

- packages/build/src/core/commands.js
- packages/build/src/log/stream.js
Fixes #876.
In the production CI, plugins `stdout` and `stderr` are buffered (due to some issues with streaming in the buildbot). This involves setting up some listeners on the `data` event of those streams. Those event listeners were never properly cleaned up, creating a memory leak.
This PR fixes that.
> Fix memory leak

- packages/build/tests/helpers/dir.js
A few of the tests were failing on my machine since I have commit signing on which prompts for a password occasionally.
This allows running the tests when commit signing is enabled.
> test: disable commit signing during tests

- packages/build/src/plugins/child/load.js
Plugins receive a `constants` object in their event handlers. This object is retrieved through an async function.
This PR moves retrieving that object a little later on in the code. This is because some validation logic happens in-between and that validation code should happen as early as possible (since it stops the build). This PR does not change any visible behavior otherwise.
> Move some line of code

- packages/build/src/plugins/child/normalize.js
`plugin.config` was previously renamed to `plugin.inputs`. We added a backward compatibility fix for people using the old names.
However now that `plugin.inputs` has been moved to `manifest.yml`, this fix is not needed anymore. Note that both `plugin.config` and `plugin.inputs` still do not error, they just don't do anything anymore.
> Remove unused backward compatibility fix

- packages/build/src/plugins/child/load.js
- packages/build/src/plugins/load.js
This PR moves some of the code from the plugins child process to the parent process instead. Plugins child processes have stronger requirements (such as the Node.js minimum allowed version), so we need to keep their code as minimal as possible.
This PR just moves code around. The behavior does not change otherwise.
> Move some code from plugins to the parent process

- packages/build/tests/plugins/constants/tests.js
One test seems to be randomly failing on Linux since #988.
This PR temporarily disables it on Linux until we have time to figure out what causes this. I am currently having issues reproducing this problem locally.
> Temporarily disable one test

- packages/build/src/log/main.js
- packages/build/src/log/serialize.js
- packages/build/src/plugins/manifest/check.js
We have some logic to serialize objects (with YAML) that should be printed in logs.
This logic is duplicated in two places. This PR refactors this so both places use the same code.
> Refactor serialization in logs

- packages/build/src/plugins/options.js
- packages/build/src/plugins_core/main.js
We have 3 kinds of plugins:
- core plugins are installed by us on every build: `{ package: '@netlify/plugin-functions-core', location: '/path/to/main/file.js', core: true }`
- module plugins are installed by users and target a Node module: `{ package: 'netlify-plugin-example' }`
- local plugins are installed by users and target a local file: `{ package: '/path/to/main/file.js' }`
This PR simplifies the code related to differentiating between each of those and assigning default values. It is refactoring-only (does not change behavior).
Note: this PR makes the `core` attribute go from `string | undefined` to `boolean`. I checked the codebase and this (rarely used) attribute is always transtyped to a boolean at the moment, so no issues there.
> Simplify some code related to local plugins

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/plugins_core/functions/plugin.js
When users specify Netlify Functions, we automatically install any dependencies those Functions might have with `npm install` (Yarn not supported yet), providing they have a `package.json`.
To do this, we need to find all the `package.json` inside Netlify Functions. The current code is quite slow since it's recurses over all subdirectories. This also requires ensuring we are not recursing inside `node_modules`. 
This PR implements a faster (and simpler) alternative that only looks for `functions/package.json` and `functions/*/package.json`. The behavior does not change otherwise.
> Improve Netlify Functions automatic install

- packages/build/tests/error/plugin_load/tests.js
- packages/build/tests/helpers/main.js
- packages/build/tests/plugins/env/tests.js
- packages/build/tests/plugins/install/tests.js
- packages/build/tests/plugins/load/tests.js
- packages/build/tests/utils/git/tests.js
- packages/config/tests/context/tests.js
- packages/config/tests/cwd/tests.js
- packages/config/tests/helpers/main.js
- packages/config/tests/load/tests.js
Many tests are testing builds that are either:
- not inside a git repository
- not inside a Node.js directory (with a `package.json`)
However `@netlify/build` itself is both. Those tests must then copy the test fixture to a temporary directory and use that instead. 
Since this is a common pattern and is quite verbose, this PR adds a test helper to be able to perform this operation. This is used through the `copyRoot` option.
```js
test('No repository root', async t => {
await runFixture(t, 'no_root', { copyRoot: {} })
})
```
The `copyRoot` option is an object has two additional parameters:
- `git` `{boolean}` (default: `true`): whether the test fixture should be inside a git repository
- `branch` `{string}`: create a new git branch and switch to it
This PR only adds this test helper, …
> Add a test helper

- packages/build/package-lock.json
- packages/build/package.json
[`cp-file@8` is not compatible](https://github.com/sindresorhus/cp-file/releases/tag/v8.0.0) with Node `8.3.0` which we still support.
We therefore need to downgrade to `cp-file@7`.
> Downgrade `cp-file`

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/plugins/ipc.js
This upgrades `uuid` from `3.4.0` to `7.0.2`. 
I checked the [`uuid` changelog](https://github.com/uuidjs/uuid/blob/master/CHANGELOG.md#700-2020-02-24) and fixed the breaking changes.
> Upgrade `uuid`

- package-lock.json
- packages/build/package-lock.json
- packages/cache-utils/package-lock.json
- packages/config/package-lock.json
- packages/functions-utils/package-lock.json
`npm audit` is showing many warnings due to an old version of `minimist`.
This version is used in many deep dependencies, so this problem will have to be fixed in several PRs. This PR only uses `npm audit fix`, which fixes 90% of the `npm audit` warnings.
> Fix security vulnerability by upgrading dependencies

- ava.config.js
There are some pending PRs (#1042, #1043, #1044, #1045) which add some tests files in some of the packages of this monorepo. To support those, the Ava configuration needs to be updated to include those future tests.
> Fix Ava configuration

- packages/build/src/log/colors.js
- packages/build/src/log/redact.js
- packages/build/src/log/stream.js
- packages/build/src/plugins_core/cache/plugin.js
- packages/build/src/plugins_core/main.js
- packages/cache-utils/src/dir.js
- packages/cache-utils/src/hash.js
- packages/config/src/validate/example.js
- packages/config/src/validate/helpers.js
- packages/config/src/validate/main.js
- packages/git-utils/src/main.js
- packages/git-utils/src/refs.js
This PR removes all `// istanbul ignore next` comments.
We use test coverage as a way to check which lines of codes are not tested. Using those comments defeats that purpose. Using those comments is only useful when test coverage is enforced to a specific threshold (which we don't do).
Let's be brave and see our true test coverage percentage :)
> Remove `istanbul ignore next` comments

- packages/build/tests/helpers/main.js
- packages/cache-utils/src/dir.js
- packages/config/src/options/main.js
We sometimes need to know in our code whether the code is run inside production or inside our tests. We try to avoid this, since integration tests should leave the actual production code intact. However there are currently 2 cases in our codebase where this was difficult.
To detect whether we are running in tests, we've been using the `TEST_CACHE_PATH` environment variable. However this variable is used for a different purpose (testing our cache logic). This PR decouples concerns by adding a new environment variable `NETLIFY_BUILD_TEST` whose sole purpose is to specify that we are currently running tests.
> Add `NETLIFY_BUILD_TEST` environment variable

- packages/cache-utils/package-lock.json
- packages/cache-utils/package.json
- packages/cache-utils/src/main.js
- packages/cache-utils/src/utils/polyfills.js
One production dependency is missing from the `cache` utility. This was unnoticed until now since it only crashes when both:
- Node.js version is `<10`
- the `cache` utility is used directly (not inside Netlify Build)
This PR fixes that.
> Fix `cache-utils` missing dependency

- packages/cache-utils/src/dir.js
- packages/cache-utils/src/list.js
- packages/cache-utils/src/main.js
- packages/cache-utils/src/path.js
In production, the `cache` utility uses the same cache directory that the buildbot uses. Locally it uses `.netlify/cache/` instead. 
This PR adds an undocumented `cacheDir` option which allows us to override that logic and specify the cache directory explicitly. This option will be used in some tests added by #1042.
> Add a `cacheDir` option to the `cache` utility

- packages/git-utils/src/refs.js
The `CACHED_COMMIT_REF` environment variable is used in the `git` utility. Its value is retrieved at load time. However it should be retrieved at run time instead. This allows for users to modify it dynamically. This will be used for example by the tests added by #1044.
> Fix environment variable `CACHED_COMMIT_REF` in the `git` utility

- packages/build/tests/core/config/tests.js
- packages/build/tests/helpers/common.js
- packages/build/tests/helpers/main.js
- packages/build/tests/helpers/normalize.js
- packages/config/package-lock.json
- packages/config/package.json
- packages/config/tests/base/tests.js
- packages/config/tests/cli/tests.js
- packages/config/tests/context/tests.js
- packages/config/tests/cwd/tests.js
- packages/config/tests/helpers/main.js
- packages/config/tests/load/tests.js
- packages/config/tests/normalize/tests.js
- packages/config/tests/parse/tests.js
- packages/config/tests/validate/tests.js
Both `@netlify/build` and `@netlify/config` use the same test setup, based on snapshot testing. The only difference are that they: 
- use different entry points / binaries
- inject different environment variables
This PR refactors the setup by putting all common test setup under a specific `tests/helpers/common.js` file, then putting what's specific in each project in a `tests/helpers/main.js` file inside each project.
This PR only moves lines around and renames variables, it does not change any testing behavior.
> Refactor test utilities

- packages/build/package.json
- packages/build/src/error/serialize.js
- packages/build/src/log/main.js
- packages/build/src/plugins/env.js
- packages/build/src/utils/omit.js
- packages/config/package-lock.json
- packages/config/package.json
- packages/config/src/utils/omit.js
- packages/config/src/validate/validations.js
Fixes #1048 
This removes the `omit.js` dependency. Besides not being well maintained, it includes an old version of `core-js` which [prints warning messages on `npm install`](https://github.com/benjycui/omit.js/issues/6).
We do not want to use `lodash.omit` because it is huge ([1500 lines of code](https://unpkg.com/lodash.omit@4.5.0/index.js) compared to [12 lines of code](https://github.com/benjycui/omit.js/blob/master/src/index.js) for `omit.js`). This is because `lodash.omit` comes with all the extraneous features and utility helpers of the whole Lodash ecosystem. Tiny modules are much simpler to debug and less bug-prone.
I could not find any well maintained alternatives on npm except for `filter-obj`, which we already use. However it needs to be wrapped with a tiny utility function …
> Remove `omit.js`

- packages/build/src/core/config.js
- packages/config/src/options/main.js
This bug is combination of several problems. 
Some of those problems are related to the buildbot transitioning from an "old" version (without `@netlify/config`) to a "new" one (with `@netlify/config`), and failure from `@netlify/config` to provide correct backward compatibility between both.
The "Base directory" UI setting is currently communicated by the "old" buildbot to Netlify Build by changing the current directory to it before calling `@netlify/build`. However the "new" buildbot is using the `--defaultConfig` CLI flag instead. 
To be able to support both, `@netlify/config` sets a `--defaultConfig` CLI flag value of `{ build: { base: getCwd() } }`. The "old" buildbot uses this, therefore getting the correct "Base directory" UI setting. The "new" buildbot does not use it since it …
> Fix duplicated paths bug

- ava.config.js
- packages/cache-utils/src/list.js
- packages/cache-utils/src/path.js
- packages/cache-utils/tests/dir.js
- packages/cache-utils/tests/has.js
- packages/cache-utils/tests/hash.js
- packages/cache-utils/tests/helpers/main.js
- packages/cache-utils/tests/list.js
- packages/cache-utils/tests/move.js
- packages/cache-utils/tests/path.js
- packages/cache-utils/tests/remove.js
- packages/cache-utils/tests/save_restore.js
- packages/cache-utils/tests/ttl.js
Creating a regular file (non-directory) in the temporary directory on Windows fails (as opposed to Unix) with an `EPERM` error:
```js
const { tmpdir } = require('os')
const { writeFile } = require('fs')
const { join } = require('path')
const filePath = join(os.tmpdir(), 'test.js')
// This fails on Windows
writeFile(filePath, 'hello', console.log)
```
The tests of the `cache` utility currently rely on the pattern above, which makes them fail on Windows. This PR fixes that by creating the temporary file inside a subdirectory instead.
Since the subdirectory should be cleaned up after the test, the test helper must return it, together with the path to the test file (which is used in the test itself).
> Fix tests failing on Windows

- CONTRIBUTING.md
Testing beta versions of `@netlify/build` in production is supported, but not documented.
https://github.com/netlify/buildbot/issues/503
**Checklist**
> Document NETLIFY_BUILD_CLI_VERSION

- packages/config/src/options/main.js
- packages/config/src/utils/is-netlify-ci.js
#943 introduced a workaround for a bug (#918) with monorepos. 
This workaround is not needed anymore now that the buildbot is using `@netlify/config` (https://github.com/netlify/buildbot/pull/629, not deployed to production yet). Therefore this PR removes the workaround.
> Revert monorepo bug workaround

- CONTRIBUTING.md
- scripts/docs.js
People have been confused about how formatting works in this monorepo. Linting and Prettier are run on `git push` but can also be run using `npm run format` (new name after #1059). Ideally people would have this done automatically for them with IDE plugins. However many people seem not to have their IDE setup to run Prettier on Markdown files by default.
This PR tries to simplify `CONTRIBUTING.md` to explain the setup a little better.
It also removes the list of monorepo packages (and the associated logic which automatically updated it) based on the discussion [here](https://github.com/netlify/docs/issues/488#issuecomment-601931560).
> Improve `CONTRIBUTING.md`

- README.md
- package-lock.json
- package.json
- scripts/docs.js
The current logic to dynamically inject the Table of Contents modifies the whole `README.md` in a way that is incompatible with Prettier, which creates several issues.
This PR migrates it to a different tool `doctoc` that does not have this problem, is solely focused on ToC generation and is used by 4000 GitHub repositories. 
This changes only internal tooling: the ToC remains the same and will keep being dynamically updated.
> Use doctoc

- .github/ISSUE_TEMPLATE/bug_report.md
This improves the issue templates used for bugs, to make it more useful for our specific use case. 
This also removes several parts to make the template less verbose. Users otherwise just disregard it altogether. Those parts are:
- Calls to create PRs instead 
- Steps to reproduce (not very relevant, we just need a deploy link to reproduce most bugs)
- Expected behavior and screenshots (usually people mention that when describing the bug)
Also the environment and CLI flags are only useful for CLI users.
> Improve bug report issue template

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Improve issue templates to match our new company-wise GitHub labels.
> Fix GitHub labels in issue templates

- package.json
This is a small improvement of npm scripts:
- rename `pre-push` to `format`
- distinguish between formatting tasks and automated tests
- merge some npm scripts
- re-order some npm scripts
> Improve npm scripts

- .github/workflows/workflow.yml
- scripts/coverage.sh
The Codecov access token is not needed in public repositories to upload test coverage maps. This PR fixes that.
> Remove Codecov token from GitHub action

- .github/workflows/workflow.yml
- package.json
This splits linting and steps into two separate steps in the GitHub actions UI. This makes looking for the logs or the duration of either step easier.
> Separate linting and testing in GitHub actions UI

- .github/workflows/workflow.yml
PRs coming from forks do not currently trigger GitHub actions. This fixes that.
> Run GitHub actions on PRs coming from forks

- packages/cache-utils/README.md
This adds a warning in the `README` of the `cache` utility that the `restore` method is potentially destructive (it overwrites files).
> Add a warning in `cache` utility `README`

- packages/cache-utils/src/path.js
- packages/cache-utils/tests/path.js
When the `cache` utility restores previously cached files/directories, those are overwritten. 
Therefore we should forbid caching the repository root directory (which is the current directory from the standpoint of the `cache` utility) or any direct parent of it.
This otherwise creates the [problems experienced](https://github.com/jlengstorf/netlify-plugin-gatsby-cache/issues/8) for example by our Gatsby plugin.
This PR adds validation against this problem and some tests for this new validation.
> Do not allow caching the current directory or any parent

- packages/cache-utils/src/main.js
- packages/cache-utils/tests/digests.js
`utils.cache.save()` returns a boolean indicating whether the file was found and it was properly cached.
We have a `digests` option as a performance optimization. When a digest file (like `package-lock.json`) in the cache is identical to the local file, we skip caching since the directory to cache is identical. At the moment, when that happens, we return `false`. However we should return `true` since that is just a performance optimization, which should behave just as if the cache actually got cached.
Some tests were adjusted accordingly.
> Fix `utils.cache.save()` return value

- packages/build/package-lock.json
Upgrades `minimist` dependency to fix a security vulnerability reported both by GitHub and `npm audit`.
> Upgrade `minimist`

- package-lock.json
Related to #1085
This fixes a dependency used by `lerna` that had security warnings with `npm audit` and GitHub.
> Fix vulnerable dependency in `lerna`

- .eslintrc.json
This removes some dead code in `.eslintrc.json`:
- the `scaffold` directory does not exist anymore
- the `scripts/docs.js` file does not exist anymore
> Remove dead code in `.eslintrc.json`

- README.md
Fixes #1094.
This adds more documentation about the Node.js environment in which Build plugins run.
> Add documentation about the Node.js environment

- README.md
Plugins can be top-level functions returning the plugin object.
The only use of this feature (as opposed to using logic at the top-level scope) is when the events that get triggered depend on user inputs. This is rather an edge case.
This PR rework the documentation of this feature to make its purpose clearer.
> Add more information about dynamic events

- packages/build/src/core/main.js
- packages/build/src/error/location.js
- packages/build/src/error/serialize.js
- packages/build/src/error/type.js
- packages/build/src/log/main.js
- packages/build/src/log/theme.js
- packages/build/src/plugins/child/main.js
- packages/build/src/plugins/manifest/check.js
- packages/build/src/plugins/manifest/validate.js
- packages/config/src/validate/example.js
- packages/config/src/validate/main.js
- packages/config/tests/validate/tests.js
This PR makes colors used in logs consistent. All colors are grouped in a `theme.js` and all logs using colors are importing this common theme. Some colors got added/removed/updated in the process to ensure consistency.
Note: one error message in `@netlify/config` that previously had colors does not have it anymore with this PR. This is due to issues passing this theme to `@netlify/config`. I will fix this specific message in a follow-up PR.
> Use consistent colors

- packages/build/src/log/theme.js
We currently color duration timing with `chalk.dim()`. However this works locally (by making it gray) but not in production CI.
This PR fixes this by using `chalk.gray()` instead.
> Fix duration color

- packages/build/src/log/theme.js
The color of `build.command` relies on boldness. However this currently [is not supported by Netlify](https://github.com/netlify/buildbot/issues/688). This PR changes it to cyan instead.
> Fix the color of `build.command`

- packages/build/package-lock.json
- packages/build/package.json
Fixes part of #1143.
This upgrades `log-process-errors` to remove one of the dependencies on `core-js`.
> Upgrade `log-process-errors`

- packages/build/src/core/commands.js
- packages/build/src/error/build.js
- packages/build/src/plugins/ipc.js
- packages/build/src/plugins/load.js
- packages/build/src/plugins/options.js
- packages/build/src/plugins/spawn.js
When plugins start, we first spawn a child process before loading the plugin main JavaScript file. Spawning this child process is supposed to never fail, but it could fail for example if there is a bug in `@netlify/build`. 
This PR adds additional error information if this were to happen. Adding a test for it was difficult since theoretically child processes are not supposed to fail on spawn. However we have many tests covering child process errors in general, and all are passing.
> Improve handling of errors when plugins start

- packages/build/package-lock.json
- packages/build/package.json
Fixes #1155.
We should use user's global `yarn` binary instead of installing it as a production dependency. Note that the buildbot has a global `yarn` binary. In local builds, we only use `yarn` if the repository has a `yarn.lock`.
> `yarn` should not be a production dependency

- packages/cache-utils/README.md
This undocuments the `move` option for `utils.cache`.
This option speeds up caching by moving files instead of copying them. This replicates what our buildbot does and is the default mode in production. However in local builds (Netlify CLI), we want to copy instead since it would destroy local repositories. 
This option should not be used by plugins. It is meant for internal usage.
> Undocument the `move` option

- codecov.yml
Codecov posts PR comments that are mostly noise. 
Commit status could be useful. Unfortunately at the moment they seem to go randomly up and down. So this PR disables it too.
> Disable Codecov PR comments and commit status

- packages/build/src/plugins/child/main.js
Fixes #1138
Errors inside `onEnd` and `onError` plugin event handlers were not properly handled. This PR fixes this.
The tests were added as `skip()` as part of another PR (#1111).
> Fix `onEnd` and `onError` error handling

- packages/cache-utils/README.md
This PR updates the documentation of the return value of the `cache` utility to better match the actual intent behind it.
Otherwise, some plugin authors have so far been using improper log messages there.
> Update documentation of the return values of the `cache` utility

- README.md
We have just added the possibility to describe plugin inputs using an optional `description` field in the `manifest.yml`.
```yml
name: netlify-plugin-example
inputs:
- name: foo
description: Describes foo
```
This PR adds documentation for it in the `README`.
> Document `inputs[*].description` field from `manifest.yml`

- packages/build/src/core/commands.js
- packages/build/tests/core/build_command/tests.js
In the buildbot (which uses Linux), we run `build.command` with Bash. However in local builds (Netlify CLI) on Windows, Bash might not be available. This PR fixes this.
> Fix `build.command` shell on Windows

- packages/build/src/core/config.js
- packages/build/src/core/main.js
At the very beginning of a build, we normalize CLI flags: assign default values, remove `undefined` values, etc.
This PR puts that logic into its own function and moves it outside of the `try`/`catch` block. This is because an incoming PR will add error monitoring, and error monitoring behavior depends on some of those flags, so must be called later. Note that there is a top-level `try`/`catch` block above this, so errors will still always be caught.
> Move CLI flags normalization

- packages/build/src/core/main.js
- packages/build/src/error/cancel.js
When a build fails, we check if the `utils.build.cancelBuild()` caused that failure. If so, we call the API endpoint to cancel the build. This function is currently called `handleError()` which is imprecise. This PR renames it to `maybeCancelBuild()`.
> Rename `handleError()` to `maybeCancelBuild()`

- packages/build/src/core/main.js
- packages/build/src/error/colors.js
- packages/build/tests/error/monitor/fixtures/colors/netlify.toml
- packages/build/tests/error/monitor/fixtures/colors/plugin.js
- packages/build/tests/error/monitor/tests.js
This removes colors from any build `error.message` so that:
- The raw ANSI sequences are not shown in the error monitoring dashboard
- Those do not clash with our colors theme
> Remove colors from `error.message`

- packages/build/src/error/type.js
Uncaught exceptions error type is currently `internal`, while plugin uncaught exceptions is `pluginInternal`. 
Unfortunately Bugsnag search filters uses fuzzy matching, which means error types must be completely distinct from each other. Otherwise it is impossible to search only for `internal`.
This PR renames the `internal` error type to `exception`.
> Fix uncaught exceptions error name

- packages/build/src/error/type.js
We have several error types with a fairly elaborate sets of properties determine how each error type should be both logged and reported to Bugsnag. The goal is to make declarative so that new error types can be added without having to change the core error handling logic.
This PR adds comments explaining what each property means.
> Add comments to error types properties

- packages/build/src/error/type.js
We have a `reason` property in error types that is not currently used (dead code). This PR removes it.
> Remove error `reason`

- packages/build/src/error/clean_stack.js
`process.cwd()` can crash due to a [range of reasons](https://linux.die.net/man/3/getcwd) including the `build.command` removing the current directory.
`process.cwd()` is currently used in one place: when cleaning up stack traces. This PR adds a `try`/`catch` block.
This error happened [in production](https://app.bugsnag.com/netlify/netlify-build/errors/5ea96cd6c7ea9900180be80c).
> Fix `process.cwd()` crash

- packages/build/src/error/type.js
Uncaught exceptions are [currently reported in Bugsnag](https://app.bugsnag.com/netlify/netlify-build/errors/5ea9c6d063104a0017720495) as `<UnknownErrorClass>` instead of `exception` due to a bug in the code, which this PR fixes.
> Fix uncaught exceptions reporting

- packages/build/src/error/monitor/normalize.js
`error.message` is used to group errors in Bugsnag. 
It the `error.message` contains a URL with a unique ID, this creates unique errors where it should not. For example [this](https://app.bugsnag.com/netlify/netlify-build/errors/5eace62e94aa900018d973bf) and [that](https://app.bugsnag.com/netlify/netlify-build/errors/5eadea5f7211110018923c09).
This PR fixes this by replacing any URLs by always the same string.
> Improve error handling grouping

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/install/missing.js
- packages/build/src/plugins/options.js
- packages/build/src/utils/resolve.js
Fixes #1197.
The `resolve` package uses a callback async signature. Due to [a bug in that package](https://github.com/browserify/resolve/issues/151#issuecomment-368210310), it does not work with `util.promisify`. Instead, `new Promise()` must be used.
This PR also upgrade `resolve` to the next major version, currently in beta, but that version probably solves more problems than it introduces.
> Fix automatic package installation uncaught exception

- packages/config/src/parse/parsers.js
Fixes #1236.
The `toml` package return objects created using `Object.create(null)`. This sometimes creates issues with libraries not used to that type of value. We should convert those to normal plain objects instead.
> Fix `toml.parse()` returning an object with `null` prototype

- packages/build/src/error/serialize.js
Fixes #1233
Some errors being thrown in production are not `Error` instances (e.g. they are strings). This fixes handling those errors.
> Fix handling non-error instances

- README.md
This PR documents that environment variables can be modified between plugins and `build.command` by setting `process.env`. That feature was just introduced (see #1174 and #1129).
> Document that `process.env` can be modified in plugins

- README.md
The methods in `utils.build.*` interrupt the current function. Under the hood, they actually throw an error. Although not strictly necessary, we should recommend prepending `return` to those methods since it makes it clear that the control flow is being interrupted both to human readers and to linters.
This PR updates the documentation accordingly.
It also removes a sentence about those methods working with `async` event handlers. Since we support `async` event handlers, users will probably assume our utilities work with them, so there's no need to specify it.
> Improve documentation for `utils.build`

- packages/build/src/log/logger.js
This ensures the color theme is used in all parts of the codebase. A file was still directly requiring `chalk`.
> Use color theme in all parts of the codebase

- README.md
We have received some [support ticket](https://community.netlify.com/t/cant-send-https-requests-from-the-netlify-build-plugin/11682) related to improper use of asynchronous code. This PR adds some documentation related to this topic.
I have also opened #1106 to discuss how we support asynchronous code.
> Add documentation about asynchronous code

- packages/build/src/install/main.js
Part of https://github.com/netlify/buildbot/issues/735
The buildbot [is using a custom cache folder](https://github.com/netlify/build-image/blob/6dfe19d15f524c85d6f9bf7df9fb30b0a9f0a61a/run-build-functions.sh#L112) for Yarn: `~/.yarn_cache`. We should use this in Netlify Build as well when running Yarn, since that's the folder being actually cached once the build ends. We should only do this in production.
> Use custom cache folder with Yarn

- packages/build/src/error/monitor/report.js
- packages/build/src/error/type.js
Related to #1223
Bugsnag has the concept of `context`, to group errors together.
Netlify also has a concept named `context`: build contexts.
To prevent confusions, this PR renames error `context` to groups instead.
> Rename error `context` to `group`

- packages/build/src/error/monitor/report.js
- packages/build/src/error/parse.js
- packages/build/src/error/serialize_log.js
- packages/build/src/error/type.js
- packages/build/src/log/main.js
Each error type has its own `header` shown in the terminal.
Since we will re-use this for statuses `title` (#1223), this PR renames `header` to `title` instead.
> Rename `header` to `title`

- packages/build/src/error/cancel.js
- packages/build/src/error/monitor/report.js
- packages/build/src/error/parse.js
- packages/build/src/error/type.js
Part of #1223.
Errors information is attached to a symbol property. It is retrieve using `getErrorInfo()`.
Also, each error type as a sets of properties retrieved using `getTypeInfo()`.
This PR is a small refactoring to try to decouple those two separate things more.
> Small refactoring of `getTypeInfo()`

- packages/build/src/log/main.js
This uses a brighter color for a deprecation warning (`red.bright` instead of just `red`).
> Use a brighter color for deprecation warning

- packages/build/src/core/commands.js
- packages/build/src/core/main.js
- packages/build/src/error/cancel.js
- packages/build/src/error/parse/parse.js
- packages/build/src/error/parse/properties.js
- packages/build/src/error/parse/serialize_log.js
- packages/build/src/error/parse/serialize_status.js
- packages/build/src/error/type.js
Part of #1223.
This creates statuses for every plugin that errors. Those statuses are meant to be shown in the UI deploy summary.
The statuses are created using the same logic as the one used to print errors in build logs, with few differences to make them fit better in the UI deploy summary context.
Note that this PR does not have tests yet: in a follow-up PR, I will add the `statuses` API call, which will make testing this PR much easier. I will add some tests then. The currently existing tests are passing though, so this should not break anything in the meantime.
> Add error statuses

- packages/build/src/plugins/options.js
- packages/build/src/plugins/resolve.js
This is a small refactoring to simplify the code related to `loadedFrom: local` (local plugins). It does not change behavior.
> Simplify some code related to `loadedFrom`

- packages/build/src/error/monitor/report.js
This fixes the following error message:
```
TypeError: Cannot read property 'replace' of undefined
at normalizeMessage (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.2/lib/node_modules/@netlify/build/src/error/monitor/normalize.js:33:18)
at Array.reduce (<anonymous>)
at normalizeGroupingMessage (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.2/lib/node_modules/@netlify/build/src/error/monitor/normalize.js:6:28)
at getGroupingHash (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.2/lib/node_modules/@netlify/build/src/error/monitor/report.js:56:20)
at reportBuildError (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.2/lib/node_modules/@netlify/build/src/error/monitor/report.js:24:24)
at build (/opt/buildhome/.netlify-build-nvm/versions/node/v12.16.2/lib/node_mod …
```
> Fix `Cannot read property 'replace' of undefined`

- packages/build/src/error/parse/properties.js
On build errors, if the error has static properties, we print them. We serialize them using `util.inspect()`. However we should increase the maximum depth level, otherwise we get things like:
```
11:25:44 PM:   Error properties
11:25:44 PM:   {
11:25:44 PM:     name: 'JSONHTTPError',
11:25:44 PM:     status: 422,
11:25:44 PM:     json: { errors: { package: [Array] } }
11:25:44 PM:   }
```
(Notice the `[Array]`)
This PR fixes this.
> Improve `util.inspect()` depth when logging error properties

- packages/build/src/plugins/resolve.js
- packages/build/src/utils/resolve.js
Fixes #1250.
The `resolve` library gives very unhelpful error messages. This means when we fail to find a plugin, the build error logs are confusing.
The `require.resolve()` can be used and does the same thing, but synchronously.
> Fix `resolve`

- packages/build/tests/error/monitor/fixtures/plugin_homepage/plugin.js
A test fixture is mistakenly using `onInit()` even though this event handler is deprecated.
> Fix test fixture using `onInit()`

- packages/build/src/log/main.js
This renames an internal variable `config` to `netlifyConfig` to make it more consistent with the rest of the codebase.
> Rename `config` variable to `netlifyConfig`

- packages/build/src/error/cancel.js
- packages/build/src/log/main.js
Fixes #1333.
When using `cancelBuild()`, the logs should show successful colors (cyan), not error ones (red).
> Improve logging of `cancelBuild()`

- packages/build/src/error/parse/parse.js
The following error happens in some builds:
```
Cannot read property 'split' of undefined 
src/error/parse/stack.js:27:24 splitStack
src/error/parse/stack.js:23:10 splitStackInfo
src/error/parse/stack.js:5:48 getStackInfo
src/error/parse/parse.js:30:48 parseError
src/error/parse/serialize_status.js:5:63 serializeErrorStatus
src/core/commands.js:289:21 handleCommandError
src/core/commands.js:160:15 runCommand
internal/process/task_queues.js:97:5 processTicksAndRejections
src/core/commands.js:75:104 async pReduce.index
src/core/commands.js:69:72 async runCommands
```
This happens when an error is thrown that is an `Error` instance but whose `message` or `stack` property is not a `string`. This PR ensures we handle that edge case.
> Fix error normalization

- packages/build/src/error/monitor/report.js
On build errors, we report the plugin's `package.json`. However we report it in two different places. This PR removes the redundancy.
> Do not report plugin `package.json` twice on build errors

- packages/build/src/core/commands.js
- packages/build/src/log/main.js
We have two functions to log errors: one for the errors due to `utils.build.failPlugin()`, one for all the errors. This PR merges those two functions. This is refactoring only.
> Simplify code related to error logging

- README.md
This adds documentation in the `README.md` about the new `utils.status.show()` (#1223).
This PR should only be merged once this utility is available in production. 
However it is ready for code review.
> Add documentation for `utils.status.show()`

- README.md
The following:
```toml
[[plugins]]
package = "hello/world"
```
Could mean two things:
- local path `./hello/world`
- GitHub repository `github.com/hello/world`. This is a recognized syntax by `npm install`.
To avoid confusion, and following the same convention as Node.js `require()`, local plugin paths must start with either `.` or `/`.
```toml
[[plugins]]
package = "./hello/world"
```
Some users though might forget the leading `./` (example [error in production](https://app.bugsnag.com/netlify/netlify-build/errors/5ec7075b9039bc0017bd4a4e)). This PR improves the documentation.
> Improve documentation of local plugins

- README.md
Fixes #1231.
This adds documentation about `utils` in the `README.md`.
> Add documentation about utilities

- packages/build/src/install/local.js
This is a small performance optimization: when a build has no `package.json` but has some local plugins, the local plugin automatic installation should not be performed (since there is no `package.json`). This prevents `pkg-dir` from being called, which saved few microseconds.
> Improve the speed of local plugin automatic installation

- README.md
The documentation of `utils` in the `README` has a typo. 
This PR also adds an example to help developers visualize how to use those `utils`.
> Improve documentation of `utils`

- packages/config/src/validate/validations.js
Part of #1303.
Follow-up on #1346.
#1346 removed `plugins[*].type`. But there was one place where this attribute was still used. This PR removes it.
> Finish removing `plugins[*].type`

- README.md
This fixes a typo in the argument passed to `utils.status.show()`.
> Fix typo in `utils.status.show()`

- packages/config/src/default_config.js
- packages/config/src/normalize.js
This is a small refactoring of how `plugin.origin` is assigned. Its value is `ui` when the plugin has been installed from the UI (`defaultConfig` parameter) and `config` when installed from `netlify.toml` (`config` parameter). This does not change behavior.
> Refactor `plugin.origin`

- packages/build/src/core/bin.js
- packages/config/src/bin/main.js
- packages/config/tests/cli/tests.js
Related to https://github.com/netlify/buildbot/issues/772
When the output of `@netlify/config` is over 65536 bytes, it is truncated. This might be due to calling `process.exit()`. `process.exit()` does not wait for I/O to be flushed. This is a problem when using async I/O such as `console.log()` when `stdout` is redirected to a pipe (I/O is sync if redirected to a TTY).
The good pattern [as outlined in Node.js documentation](https://nodejs.org/dist/latest-v14.x/docs/api/process.html#process_process_exit_code) is to use `process.exitCode`.
> Fix wrong usage of `process.exit()`

- packages/build/src/install/main.js
- packages/build/src/install/missing.js
We have some logic to add dependencies with either npm or Yarn.
However this currently is only used with npm, with automatic installs. Even if users use Yarn in their projects, automatically installed plugins will use npm to match the behavior from the `build-image` and make the logic more resilient.
Also, the latest version of dependencies is always installed in that case.
This PR does some refactoring simplifying that code taking into account the above. It does not change any behavior.
> Simplify code related to automatic installs

- packages/build/src/telemetry/track.js
The child process spawned for the telemetry needs to call `childProcess.unref()`. Otherwise, it will keep the parent process alive, which defeats the point of using a child process for that purpose.
This PR fixes this.
> Fix performance issue

- packages/build/src/error/monitor/normalize.js
This is a small addition to #1387, due to changes in #1397.
This improves how Bugsnag reports that specific error.
> Fix Bugsnag grouping

- packages/build/src/error/monitor/normalize.js
This is a follow-up on #1405, which adds normalization of base64 encoded URIs.
> Improve normalization of Bugsnag errors

- packages/build/tests/install/functions/tests.js
- packages/build/tests/install/local/tests.js
- packages/build/tests/install/missing/tests.js
The tests related to `npm install` are currently run serially because we previously experienced some network errors when run in parallel.
Now that the number of those tests has been reduced, this PR runs them in parallel instead, for improved test speed.
> Improve speed of installation-related tests

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/error/monitor/start.js
When `@netlify/build` is run several times for a single process (e.g. during tests), Bugsnag prints a warning because `Bugsnag.start()` return value is a singleton which cannot be instantiated twice.
This PR adds `memoize-one` so that calling `Bugsnag.start()` a second time returns the same return value, but without any warning message printed on console.
> Improve Bugsnag start logic

- packages/build/src/core/bin.js
- packages/build/src/core/main.js
This PR changes the programmatic return value of `@netlify/build` from a boolean to an object. This allows for more flexibility if we need to add more information in the return value.
This is required by an upcoming PR which will add more information in the return value.
> Improve `@netlify/build` return value

- packages/build/src/core/main.js
This allows the argument to `@netlify/build` (when run programmatically) to be optional.
> Make `flags` object optional

- packages/build/src/core/bin.js
- packages/build/src/core/config.js
- packages/build/src/log/main.js
- packages/build/tests/helpers/common.js
- packages/build/tests/helpers/main.js
There is a `NETLIFY_BUILD_DEBUG` environment variable which prints additional information in logs. However environment variables are global, which makes it difficult to run parallel tests in the same process. This PR does not remove that environment variables but adds an additional way to specify it: a `--debug` CLI flag, which is test-friendlier.
> Add `debug` flag

- packages/build/src/core/config.js
- packages/build/src/core/main.js
- packages/build/src/error/monitor/start.js
- packages/build/src/log/main.js
- packages/build/tests/error/monitor/tests.js
There is a `BUGSNAG_KEY` environment variable to set the Bugsnag API key. However environment variables are global, which makes it difficult to run parallel tests in the same process. This PR does not remove that environment variable but adds an additional way to specify it: a `--bugsnag-key` CLI flag, which is test-friendlier.
> Add `--bugsnag-key` CLI flag

- packages/build/src/core/bin.js
- packages/build/src/core/commands.js
- packages/build/src/core/config.js
- packages/build/src/core/main.js
- packages/build/src/error/monitor/report.js
- packages/build/src/log/main.js
- packages/build/src/plugins/load.js
- packages/build/src/plugins/manifest/main.js
- packages/build/src/plugins/options.js
- packages/build/src/status/report.js
- packages/build/tests/error/monitor/tests.js
The `NETLIFY_BUILD_DEBUG` environment variable is used in tests to change some runtime behavior, such as printing the request payload sent to Bugsnag (because it is hard to mock the API request due to some Bugsnag implementation details).
Environment variables are global, making it hard to run several tests in parallel inside the same process. This PR switch instead to a boolean parameter/flag `testOpts.errorMonitor`, which is test-friendlier.
> Add `testOpts.errorMonitor` flag

- packages/build/src/core/main.js
- packages/build/src/log/old_version.js
- packages/build/tests/log/old_version/tests.js
The `NETLIFY_BUILD_TEST` environment variable is used in tests to change some runtime behavior, such as forcing `update-notifier` to print a message.
Environment variables are global, making it hard to run several tests in parallel inside the same process. This PR switch instead to a boolean parameter/flag `testOpts.oldCliLogs`, which is test-friendlier.
> Add `testOpts.oldCliLogs` flag

- packages/build/src/plugins/child/api.js
- packages/build/src/plugins/child/load.js
- packages/build/tests/plugins/api/tests.js
The `NETLIFY_BUILD_API_CLIENT` environment variable is used in tests to enable the API client feature.
Environment variables are global, making it hard to run several tests in parallel inside the same process. This PR switch instead to a boolean parameter/flag `testOpts.apiClient`, which is test-friendlier.
> Add `testOpts.apiClient` flag

- packages/build/src/plugins/options.js
- packages/build/src/plugins/resolve.js
- packages/build/tests/core/flags/tests.js
- packages/build/tests/plugins/load/tests.js
The `TEST_BUILD_IMAGE_PLUGINS_DIR` environment variable is used in tests to mock the location of the `build-image` pre-installed plugins directory.
Environment variables are global, making it hard to run several tests in parallel inside the same process. This PR switch instead to a boolean parameter/flag `testOpts.buildImagePluginsDir`, which is test-friendlier.
> Add `testOpts.buildImagePluginsDir` flag

- packages/build/src/plugins/options.js
- packages/build/src/plugins_core/cache/plugin.js
- packages/build/src/plugins_core/main.js
- packages/build/tests/cache/main/tests.js
- packages/build/tests/helpers/main.js
The `TEST_CACHE_PATH` environment variable is used in tests for two reasons: 
- mock the location of the cache directory
- detect whether the core `cache` plugin should be used (it is only used in tests at the moment)
Environment variables are global, making it hard to run several tests in parallel inside the same process. For the second purpose (plugin detection), this PR switch instead to a boolean parameter/flag `testOpts.cachePath`, which is test-friendlier. For the first purpose (location mocking), it keeps the environment variable for the moment, as that value must be available in child processes.
> Add `testOpts.cachePath` flag

- packages/build/src/status/report.js
- packages/build/tests/status/helpers/run.js
The `NETLIFY_BUILD_TEST_STATUS` environment variable is used in tests to force sending an API status.
Environment variables are global, making it hard to run several tests in parallel inside the same process. This PR switch instead to a boolean parameter/flag `testOpts.sendStatus`, which is test-friendlier.
> Add `testOpts.sendStatus` flag

- packages/build/src/core/main.js
- packages/build/src/telemetry/complete.js
- packages/build/src/telemetry/request.js
- packages/build/src/telemetry/track.js
- packages/build/tests/core/telemetry/tests.js
The `TEST_SCHEME` and `TEST_HOST` environment variables are used in tests to mock the telemetry API endpoint.
Environment variables are global, making it hard to run several tests in parallel inside the same process. This PR switches instead to a parameter/flag `testOpts.telemetryOrigin`, which is test-friendlier.
> Add `testOpts.telemetryOrigin` flag

- packages/config/src/bin/main.js
This puts one line of code in `@netlify/config` which was not inside the `try`/`catch` block, in case this throws.
> Improve error handling of `@netlify/config`

- packages/config/src/main.js
- packages/config/src/options/branch.js
- packages/config/src/options/main.js
`@netlify/config` might be called several times within the same process. Between those calls, environment variables might be modified using `process.env`. This happens for example in some tests.
At the moment, environment variables are retrieved when `@netlify/config` loads. This changes it to retrieving their values each time `@netlify/config` is run, to make it test-friendlier.
> Improve environment variables usage in `@netlify/config`

- packages/cache-utils/src/list.js
- packages/cache-utils/src/path.js
If the current directory is changed between two calls to the `cache` utility, the second call will not get the new current directory. This PR fixes this.
> Improve retrieval of the current directory in the `cache` utility

- packages/build/src/core/config.js
- packages/build/src/core/main.js
- packages/build/tests/env/main/tests.js
- packages/build/tests/error/build/tests.js
- packages/build/tests/status/helpers/run.js
- packages/config/src/api/client.js
- packages/config/src/main.js
- packages/config/tests/api/tests.js
The `TEST_HOST` and `TEST_PORT` environment variables are used in tests to mock the Bitballoon API endpoint/
Environment variables are global, making it hard to run several tests in parallel inside the same process. This PR switch instead to parameters/flags `testOpts.host|port`, which is test-friendlier.
> Use `testOpts.host|port` with `@netlify/config`

- scripts/coverage.sh
The `-y` flag of Codecov has been deprecated. Codecov now automatically detects `codecov.yml` if it's in the repository root directory.
> Fix codecov script

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/core/bin.js
- packages/build/src/core/main.js
- packages/build/src/env/main.js
- packages/build/src/log/colors.js
- packages/build/src/plugins/child/error.js
- packages/build/tests/helpers/common.js
We have some logic to decide whether colors should be shown in the parent process and each child process. 
`supports-color` is the main library used by other libraries (like `chalk`) to detect this. It performs its logic at load time, so we must set any environment variable before `chalk` is loaded. `util.inspect.defaultOptions.colors` is also used by `console.*()`.
The current logic we have relies on a number of things such as `stdout.isTTY`. However both `supports-color` (used by `chalk`) and `process.getColorDepth()` (which is used by core Node.js) use a similar logic. Their logic is actually even more advanced.
Therefore this PR removes most of our colors logic to let those underlying libraries do their job.
It still keeps two things:
- In production/buildbot, the terminal is …
> Improve colors support

- packages/build/src/core/commands.js
- packages/build/src/log/stream.js
When a plugin event handler starts, we redirects its stdout/stderr to the parent process. When the event handler stops, we undo it, to leave room to the next plugin. 
However there was a race condition in the current logic: we were not waiting for the plugin's stdout/stderr to be flushed out before switching it off. This led to tests randomly failing.
This PR fixes it by waiting one macrotask (`setTimeout(0)`) before switching off the redirection. This gives enough time for the flush to happen. I made some manual testing with thousands of plugins running in parallel and it always correctly flush out.
> Fix tests randomly failing

- packages/build/tests/helpers/common.js
This removes the test timeout, as this might be triggered in rare occasions due to all tests being started at once in parallel, and in slow hardware like Windows in GitHub actions.
> Remove test timeout

- packages/build/tests/core/cli/tests.js
- packages/build/tests/helpers/common.js
Tests should use the `failed` return value of `execa` instead of `exitCode`. This is because a future PR will add a test mode where the main function is triggered programmatically instead of through the CLI, in which case there won't be any exit code. This PR prepares the code for this future PR.
> Use `failed` instead of `exitCode`

- packages/build/tests/plugins/node_version/tests.js
This is a small refactoring of the tests related to `--node-path`.
> Refactor `--node-path` tests

- packages/build/src/core/config.js
- packages/build/src/core/constants.js
- packages/cache-utils/src/dir.js
- packages/cache-utils/tests/dir.js
`utils.cache` guesses which cache directory is the most appropriate depending on the environment. In order to test this behavior, we previously relied on an environment variable `NETLIFY_BUILD_TEST`.
Environment variables are global, so they make it harder to run several tests in parallel inside the same process. This PR switches to testing for the presence of the parameter/flag `testOpts.cachePath` (also added by #1430) instead.
It also updates some tests accordingly.
> Refactor how `utils.cache` is tested

- packages/config/src/main.js
This is a small refactoring of how `siteId` is passed around in `@netlify/config`.
It does not change any behavior.
> Refactor `siteId` in `@netlify/config`

- packages/config/src/main.js
- packages/config/src/options/main.js
This is a small refactoring of how options are handled in `@netlify/config` which divides between: 
- Assigning default option values (sync, happens before `getApiClient()`)
- Normalizing options (async, happens after `getApiClient()`)
This is refactoring only. It does not change any behavior.
> Refactor default values of `@netlify/config`

- packages/build/src/core/config.js
This is a small refactoring of the function assigning default flags. It does not change its behavior.
> Refactor how default flags are assigned

- packages/build/tests/core/build_command/tests.js
- packages/build/tests/core/config/tests.js
- packages/build/tests/error/monitor/tests.js
- packages/build/tests/error/stack/tests.js
- packages/build/tests/helpers/common.js
- packages/build/tests/plugins/load/tests.js
- packages/config/tests/base/tests.js
- packages/config/tests/helpers/main.js
- packages/config/tests/load/tests.js
This removes a test helper `getJsonOpt()` used when passing JSON argument to `@netlify/build` or `@netlify/config` binaries. 
A future PR will also remove the `escapeExecaOpt()` test helper.
The reason we want to remove those is because another future PR will call tests programmatically instead of through the CLI.
> Remove `getJsonOpt()` test helper

- packages/build/src/core/config.js
`@netlify/build` is influenced by some environment variables.
This PR adds the possibility to override those with an `env` option. This is useful notably in testing.
> Add `env` option to `@netlify/build`

- packages/build/tests/core/build_command/tests.js
- packages/build/tests/core/cli/tests.js
- packages/build/tests/core/config/tests.js
- packages/build/tests/core/dry/tests.js
- packages/build/tests/error/monitor/tests.js
- packages/build/tests/error/stack/tests.js
- packages/build/tests/helpers/common.js
- packages/build/tests/helpers/main.js
- packages/build/tests/log/colors/tests.js
- packages/build/tests/log/old_version/tests.js
- packages/build/tests/plugins/load/tests.js
- packages/build/tests/status/helpers/run.js
- packages/config/src/bin/main.js
- packages/config/tests/base/tests.js
- packages/config/tests/cli/tests.js
- packages/config/tests/helpers/main.js
- packages/config/tests/load/tests.js
This PR runs tests using the Node.js main function instead of using the CLI entry point and spawning a new child process for each test. This makes tests much faster.
Doing it also allows removing the `escapeExecaOpt()` test helper and the `NETLIFY_BUILD_TEST` environment variable as a side effect.
Few tests still require calling the CLI entry point, mostly the tests testing the CLI entry point itself or flags that only exist in CLI such as `--help` or `--version`.
> Run tests using the programmatic main functions

- packages/build/tests/helpers/common.js
This fixes colors not being shown in tests when using the debugging mode (`PRINT=1` environment variable).
> Fix colors in tests

- packages/build/src/plugins/ipc.js
When a Build plugin has exited unexpectedly, we print an error message since we cannot communicate to that process anymore.
The current logic that checks whether the child process has exited is incomplete. It currently checks for `childProcess.connected` being `false`. However, in highly concurrent code like the tests, that attribute is sometimes not `false` yet, while `childProcess.exitCode` or `childProcess.signal` has been set. This makes some tests fail randomly.
This PR fixes this.
> Fix test randomly failing

- packages/build/tests/error/fixtures/early_exit/plugin_slow.js
This fixes a test that is failing on Node 8 (but not Node 14) due to the `child_process` logic having changed between those Node.js versions.
> Fix test failing on Node 8

- packages/build/tests/helpers/main.js
Some tests are failing on Windows due to path delimiters being `\` instead of `/`. This PR fixes this.
> Fix some tests failing on Windows

- packages/run-utils/tests/main.js
Some tests are failing on Windows (unless Unix utilities have been installed) due to them using `echo` which is different in Unix and in `cmd.exe`. This PR disables those tests on Windows.
> Fix some tests on Windows

- packages/build/tests/install/tests.js
Some of the tests call `yarn`. This relies on the `PATH` environment variable being modified. This requires a child process being spawned for those tests. Otherwise, the tests will fail if `yarn` is not globally installed. This PR fixes this.
> Fix tests using Yarn

- packages/build/tests/helpers/common.js
- packages/build/tests/helpers/main.js
The `debug` flag is passed to every test. However it is specific to `@netlify/build`, not `@netlify/config`, so should be moved to logic that is not common to both.
> Small refactor of test helper

- packages/build/src/env/metadata.js
- packages/build/src/error/monitor/location.js
- packages/build/tests/error/tests.js
The `SITE_NAME` and `SITE_ID` environment variables have just been added.
This PR allows us to simplify some code which was trying to figure out the site's name by extracting it from the `DEPLOY_URL` environment variable.
This PR also sends those two to Bugsnag on build errors, for debugging purpose.
> Add support for `SITE_NAME`

- packages/build/src/core/bin.js
- packages/build/src/log/colors.js
- packages/build/src/plugins/child/main.js
- packages/build/tests/log/tests.js
The buildbot is now setting the `FORCE_COLOR` environment variable to `1` when calling `@netlify/build` (https://github.com/netlify/buildbot/pull/805).
Thanks to this, we can simplify the logic related to colors. We take care of several uses cases:
- buildbot vs local plugins. Buildbot relies on setting `FORCE_COLOR=1`. Local builds usually happen in interactive TTYs, so they are automatically detected as supporting colors. This means colors are known at require-time, so `supports-color` does not need to dynamically loaded anymore.
- colors in the parent process, in the build command, and in Build plugins
- `FORCE_COLOR=1` in the buildbot forces colors in most libraries like `supports-color` (used by `chalk`)
- `utils.inspect()` (used by `console.log()`) requires manually setting …
> Simplify colors logic

- packages/build/src/log/main.js
We are printing flags in logs, but are hiding many for several reasons.
This PR adds some code comments to explain the rational behind each.
It also adds `functionsDistDir` to the list of flags hidden in production.
> Refactor how flags are hidden

- packages/config/src/options/main.js
Fixes #1539.
When `cwd` does not exist, `process.cwd()` throws an error. 
However this should not be the case when a `cwd` option was passed to `@netlify/config` instead.
> Do not fail when `cwd` does not exist but was passed as option to `@netlify/config`

- packages/git-utils/package-lock.json
- packages/git-utils/package.json
- packages/git-utils/src/exec.js
- packages/git-utils/src/main.js
- packages/git-utils/tests/main.js
Fixes #1540.
When the `cwd` option passed to `git-utils` points to a non-existing directory, we should throw a better error message.
> Improve error message on invalid `cwd` in `git` utils

- packages/cache-utils/src/list.js
- packages/cache-utils/src/path.js
- packages/cache-utils/src/utils/cwd.js
- packages/cache-utils/tests/list.js
Fixes #1536.
There are several reasons why `cwd` might not exist when `utils.cache.list()`. For example, it might have been removed by the user or a plugin. Or the build might be canceling ([example deploy](https://app.netlify.com/sites/staffbase-staffbasetest/deploys/5eeb8d5b145f7c0008849492)).
When this happens, the build should not crash.
> Fix `utils.cache.list()` failing if `cwd` does not exist

- packages/cache-utils/src/path.js
- packages/cache-utils/tests/path.js
Fixes #1537 and #1538.
When `cwd` does not exist, `utils.cache.*` and the `path` is relative, the function must fail since we cannot resolve it (`cwd` being the base of that relative path). However, we should provide a better error message than the current one.
Also, when the `path` is an absolute path, `cwd` is not needed. We should not throw an error then if `cwd` does not exist.
> Fix invalid `cwd` in `cache` utility

- packages/cache-utils/README.md
- packages/cache-utils/src/list.js
- packages/cache-utils/src/main.js
- packages/cache-utils/src/path.js
- packages/cache-utils/src/utils/cwd.js
- packages/cache-utils/tests/list.js
- packages/cache-utils/tests/path.js
This adds a `cwd` option to all `utils.cache.*` methods to modify the current directory. The current directory is used mostly to resolve relative paths passed as arguments. 
This is useful in testing, and few tests are simplified thanks to this.
> Add `cwd` option to `utils.cache.*`

- packages/build/src/plugins/child/utils.js
- packages/functions-utils/README.md
- packages/functions-utils/src/main.js
- packages/functions-utils/tests/main.js
This is a follow-up on similar issues to fix `utils.functions.list()` performance by making it use `listFunctions()` instead of `listFunctionsFiles()` which is much slower. This PR does it by adding `utils.functions.listAll()` which returns all Functions required files (much slower). This is useful for `neltify-plugin-inline-functions-env` for example (see https://github.com/bencao/netlify-plugin-inline-functions-env/pull/6).
> Add `utils.functions.listAll()`

- packages/config/src/bin/flags.js
This marks the `--debug` `@netlify/config` CLI flag as an undocumented flag.
> Add more documentation about --debug `@netlify/config` flag

- packages/config/src/log/main.js
Due to the buildbot problem described in https://github.com/netlify/buildbot/issues/595, empty lines are not shown in production.
This PR fixes this problem in `@netlify/config` using the same workaround that's been working in `@netlify/build`, by adding an invisible character inside empty lines.
> Fix newline problem in `@netlify/config`

- packages/config/src/log/main.js
In debug mode, the CLI flags of `@netlify/config` are printed. 
However, in production, `@netlify/config` is called twice: first directly (so that buildbot can use the result) and then inside `@netlify/build` itself. To prevent doing the logic twice, we use a `cachedConfig` CLI flag to re-use the result of the first call.
On the second call, we should not print the CLI flags again. This PR fixes this.
> Do not print `@netlify/config` CLI flags twice

- packages/config/src/log/logger.js
- packages/config/src/log/main.js
This moves some of the logging logic of `@netlify/config` into its own file.
> Move log logic of `@netlify/config`

- packages/config/package-lock.json
- packages/config/package.json
`chalk@4` is not compatible with Node `8.3.0`, so we need to downgrade to `chalk@3`.
> Downgrade chalk

- packages/cache-utils/README.md
- packages/cache-utils/src/list.js
- packages/cache-utils/tests/list.js
Part of #1362.
`utils.cache.list()` crashes some builds when there are too many files cached. This PR fixes this by only returning the first 2 depth levels of directories/files being cached.
This PR also makes `utils.cache.list()` return directories, not only files, as described in #1362.
> Fix `utils.cache.list()` crashing builds

- packages/config/src/default.js
- packages/config/src/main.js
This moves the `defaultConfig` logic from `@netlify/config` to its own file.
This is refactoring-only.
> Move `defaultConfig` logic to its own file

- packages/build/src/core/config.js
- packages/build/src/core/main.js
This moves some lines of code related to configuration loading.
This also runs them in parallel instead of serially, as a small performance optimization.
> Move some configuration logic between files

- packages/build/src/core/main.js
This moves some lines of code at the start of the main file into their own function, to make the main function smaller.
> Move some lines of code at the start of builds

- packages/build/src/core/config.js
This moves some lines of code related to configuration logging to their own function.
> Move lines of code related to configuration logging

- packages/build/src/core/config.js
- packages/build/src/core/main.js
This moves some variables around to make them available earlier in the main logic.
> Move some variables

- packages/build/src/core/config.js
- packages/build/src/core/main.js
This moves the function that retrieves `constants` later in the logic, closer to where it is actually used. This is refactoring only.
> Move logic to retrieve `constants`

- packages/build/src/core/config.js
- packages/build/src/core/flags.js
- packages/build/src/core/main.js
This splits a file into two: one for the flags parsing, and one for the configuration parsing.
> Split a file into two

- packages/build/src/core/commands.js
- packages/build/src/core/config.js
- packages/build/src/core/main.js
We retrieve the site's `package.json` in order to print a warning related to the `CI=true` issues. 
At the moment, we always retrieve it, top-level. Instead, we should only retrieve it when that warning is about to be printed. This is faster.
> Move `package.json` retrieval

- packages/build/src/error/monitor/normalize.js
This fixes a missing `g` flag on a regular expression used to normalize error keys passed to Bugsnag.
> Improve error message normalization

- packages/build/src/core/main.js
This moves the main logic handling build failures into its own function. This is refactoring only.
> Move build error handling logic to its own function

- packages/build/src/core/main.js
This moves one line of code which prints a warning when a build failed and an old version of `netlify/cli` was used.
This ensures this warning is printed at the very end of the build logs.
> Move one line of code related to CLI warnings

- packages/build/src/core/bin.js
This adds a code comment on the CLI entry point with some recommendations on where to place code.
> Add comment on CLI entry point

- packages/build/src/core/main.js
We count the number of commands (build command or plugin event handler) that get performed. We use this information for analytics only.
In dry run, this is estimated. However in real runs, this is the actual number of commands that got performed, excluding commands that got skipped (for example due to the plugin failing). 
Due to a missing variable, we were using the estimated count instead of the actual count.
> Fix `commandsCount` used in analytics

- packages/build/src/core/commands.js
- packages/build/src/core/main.js
- packages/build/src/error/monitor/report.js
- packages/build/src/error/parse/parse.js
- packages/build/src/status/report.js
This moves the logic related to `childEnv` during build errors in order to avoid attaching it to the error instance, which was a temporary hack.
> Move `childEnv`-related logic

- packages/build/src/core/main.js
- packages/build/src/error/parse/parse.js
- packages/build/src/error/parse/serialize_log.js
- packages/build/src/log/main.js
This moves how the `netlifyConfig` is passed to error handling code. This is refactoring only.
> Move `netlifyConfig`-related logic

- packages/build/src/core/commands.js
- packages/build/src/core/main.js
- packages/build/src/status/add.js
This moves some of the logic related to how plugin statuses are being reported when the build fails. This is refactoring only.
> Move logic related to plugin statuses reporting

- packages/build/src/core/commands.js
- packages/build/src/core/main.js
- packages/build/src/log/main.js
- packages/build/src/status/report.js
This moves the warning printed on build failures when Netlify CLI was used and it is not the latest version. Moving it ensures that every code that prints build failure logs uses that logic.
> Move CLI warning on build failures

- scripts/coverage.sh
Our CI is failing due to a Codecov bug. I have posted some information in their [repository](https://github.com/codecov/codecov-bash/issues/330).
However, Codecov just fails way too often. This PR ensures that CI still passes even when Codecov fails uploading test coverage reports.
> Fix Codecov CI failing

- packages/cache-utils/README.md
- packages/functions-utils/README.md
- packages/git-utils/README.md
- packages/run-utils/README.md
Fixes #1635.
Logos were removed by #989. However some were still present in individual packages `README`. This PR removes them.
> Remove logos from `README`

- packages/build/src/core/bin.js
- packages/build/src/core/main.js
`netlify-build` will need to communicate to the buildbot over a Unix socket server. The path to this Unix socket will be provided as a CLI argument.
Part of https://github.com/netlify/build/pull/1659.
I've added a `--buildbotServerSocket` CLI flag.
**Checklist**
> --buildbotServerSocket CLI flag

- packages/build/src/commands/run.js
- packages/build/src/core/main.js
- packages/build/src/log/timer.js
- packages/build/src/telemetry/complete.js
This refactors how we log durations, to accommodate for future work to send that information to Datadog.
> Refactor duration logging

- packages/cache-utils/package-lock.json
- packages/cache-utils/package.json
Ava v3 cannot be used yet because it drops support for Node 8.
> Downgrade Ava

- packages/build/src/core/bin.js
- packages/build/src/core/main.js
- packages/build/src/time/report.js
- packages/build/tests/helpers/temp.js
- packages/build/tests/time/fixtures/plugin/manifest.yml
- packages/build/tests/time/fixtures/plugin/netlify.toml
- packages/build/tests/time/fixtures/plugin/plugin.js
- packages/build/tests/time/fixtures/simple/netlify.toml
- packages/build/tests/time/tests.js
This adds a `--timersFile` CLI flag which allows measuring specific part of the build, and writing the durations to a `*.txt` file. That file is used by the buildbot, which sends the data to Datadog.
This PR also measures the whole build duration that way.
> Add `--timersFile` CLI flag

- packages/build/src/core/main.js
- packages/build/tests/time/tests.js
This adds metrics about how long it takes to load plugins.
> Measure how long plugins take to load

- packages/build/src/core/main.js
- packages/build/tests/time/tests.js
This adds metrics about how long it takes to start plugins child processes.
> Measure how long it takes for plugins processes to start

- packages/build/src/core/main.js
- packages/build/tests/time/tests.js
This adds metrics about how long it takes to load the options and `manifest.yml` of plugins.
> Send metrics about plugins options loading

- packages/build/src/core/main.js
- packages/build/tests/time/tests.js
This adds metrics about how long it takes to retrieve the configuration options.
> Measure how long it takes to retrieve config

- packages/build/src/core/config.js
- packages/build/src/core/main.js
This refactors how CLI flags are passed around. This does not change any logic.
> Refactor how CLI flags are passed around

- packages/functions-utils/README.md
This fixes a typo in the `functions-utils` `README`.
> Fix typo in `functions-utils` `README`

- packages/build/src/core/main.js
- packages/build/src/time/report.js
This improves how the main function of Netlify Build is time-measured, by re-using the same wrapping function as the other parts of the codebase.
> Improve how the main function is measured

- packages/build/src/error/handle.js
Fixes #1696.
When builds are canceled, the whole filesystem is being deleted by the buildbot.
However, the process (and build) keep going. Because no files exist anymore, the build eventually crashes with a randomly weird error. Those should not be logged nor reported.
Note: builds canceled with `utils.build.cancelBuild()` should still show "Build canceled by ...".
> Improve builds cancellation error handling

- packages/cache-utils/src/utils/cwd.js
The `cwd` option passed to `utils.cache.*()` methods should be normalized, since it is compared with other file paths which are normalized too.
> Fix `cwd` option of `cache` utility

- packages/cache-utils/package-lock.json
- packages/cache-utils/package.json
- packages/cache-utils/src/fs.js
- packages/cache-utils/src/main.js
- packages/cache-utils/tests/save_restore.js
- renovate.json5
When `utils.cache.*()` (which is used by all our caching-related Build plugins) is used to cache an empty directory, the build crashes with an error `ENOENT: no such file or directory, open '/opt/build/cache/cwd/.cache.netlify.cache.json'`. This PR fixes this.
The underlying reason is because `utils.cache.*()` is a noop when trying to cache/restore a non-existing file/directory. However, it should also be a noop for empty directories.
This includes several tests.
> Fix caching empty directories

- packages/build/src/commands/run.js
- packages/build/tests/time/tests.js
Part of https://github.com/netlify/buildbot/issues/888
This renames the tag name used in Datadog to monitor the duration of Build plugins.
This will make it easier to separate those from the other metrics.
> Rename the monitoring tag name of Build plugins

- packages/build/src/commands/run.js
- packages/build/src/time/main.js
- packages/build/src/time/report.js
- packages/build/tests/time/tests.js
Part of https://github.com/netlify/buildbot/issues/888
This renames some internal variables that are Datadog tags, but are currently named metrics instead.
> Rename `metricName` to `tag`

- packages/build/tests/time/fixtures/plugin/netlify.toml
- packages/build/tests/time/tests.js
Part of https://github.com/netlify/buildbot/issues/888
This improves a test so that `build.command` duration monitoring is also tested.
> Add test for the `build.command` duration monitoring

- packages/build/src/log/main.js
`timersFile` is an internal CLI flag that should not be shown in the build logs.
> Do not log `timersFile` in production

- package.json
- packages/build/package.json
- packages/cache-utils/package.json
- packages/config/package.json
- packages/functions-utils/package.json
- packages/git-utils/package.json
- packages/run-utils/package.json
Fixes #993.
The `package.json` of our packages are missing some fields. For example, they have no `repository` field, which means the link to GitHub does not show up in npm.
> Improve packages `package.json`

- packages/build/src/commands/run.js
- packages/build/src/time/aggregate.js
- packages/build/src/time/main.js
Part of https://github.com/netlify/build/issues/1738
This adds `parent` statsd tags. This allows for performance measurements to be nested within each other.
> Add `statsd` parent tags

- packages/build/src/time/aggregate.js
- packages/build/src/time/main.js
- packages/build/src/time/report.js
- packages/build/tests/time/tests.js
Part of https://github.com/netlify/build/issues/1738
This renames the internal-only variable `tag` to `stageTag` instead, since we know use several statsd tags (`stage` and `parent`).
> Rename `tag` internal variable to `stageTag`

- packages/build/src/commands/run.js
- packages/build/src/core/config.js
- packages/build/src/core/main.js
- packages/build/src/plugins/load.js
- packages/build/src/plugins/options.js
- packages/build/src/plugins/spawn.js
- packages/build/src/time/aggregate.js
- packages/build/src/time/main.js
- packages/build/tests/time/tests.js
Background at https://github.com/netlify/buildbot/issues/898
This rename all statsd `stage` tags to match the pattern described in https://github.com/netlify/build/issues/1738
_
In particular, this removes the namespace prefixing, and rename `command` to `build_command`.
> Rename all statsd `stage` tags

- packages/build/src/core/main.js
- packages/build/src/time/aggregate.js
- packages/build/src/time/main.js
- packages/build/tests/time/tests.js
Part of https://github.com/netlify/build/issues/1738
The `total` duration measurement is redundant with the buildbot one (which is better since it includes Node.js load time).
This PR replaces it by another one `others`, which counts all the durations that are not taken into account by other measurements. It does hits by using the `total` duration, and subtracting all the others. That measurement should ideally be very small. If it is big, it means there are some slow parts we are not measuring. Detecting those is the purpose of that measurement.
> Replace `total` duration measurement by `others`

- packages/build/src/commands/run.js
- packages/build/src/core/main.js
- packages/build/src/log/main.js
- packages/build/src/telemetry/complete.js
- packages/build/src/time/aggregate.js
- packages/build/src/time/main.js
- packages/build/src/time/measure.js
- packages/build/src/time/report.js
- packages/build/tests/time/tests.js
Fixes #1748.
Some of the performance measurements we are sending are computing by adding/subtracting two measurements.
The measurements are done with nanoseconds precision. [statsd expects milliseconds](https://github.com/b/statsd_spec#metric-types--formats). At the moment, we round right after the measurement is being made, which introduces double rounding and [round-off errors](https://en.wikipedia.org/wiki/Round-off_error). We should instead keep the measurements as nanoseconds as long as possible, i.e. until they are sent to statsd.
> Improve performance monitoring rounding

- packages/build/src/core/constants.js
Some refactoring related to https://github.com/netlify/build/pull/1752
Some of the `constants` we pass to Build plugins are file paths. We normalize those from absolute paths to relative paths instead, so that they are less verbose when printed in logs. Since some `constants` are not file paths, we use a deny list to exclude those from that logic. We could also use a RegExp, but it would be slower and more error prone.
This PR changes the logic to use an allow list instead, so that adding a non-file-paths constant does not accidentally apply this logic on the new constants, which would be worse than not applying the logic on a new file path constant.
> Improve constants path normalization

- packages/build/src/install/local.js
- packages/build/src/plugins/options.js
- packages/build/src/plugins_core/main.js
This refactors the logic used to load core plugins.
This does not change the logic, just refactor its code.
This will make it easier to add the Edge handlers plugin as a core plugin.
> Refactor core plugins logic

- packages/build/src/plugins_core/functions/error.js
Fixes #1766.
When a Netlify Function is missing a dependency, an error message is shown to point to the problem. However, the error message is currently truncating the package name when the package starts with `@`. This PR fixes this.
> Fix error message on missing Netlify Function dependency

- packages/cache-utils/package.json
- packages/cache-utils/src/manifest.js
Fixes #1411. 
This fixes a bug with the `cache` utility happening when trying to cache empty directories.
I can reproduce this bug in production, but not locally, which makes it unfortunately hard to create a regression test.
> Fix cache utility bug

- .eslintrc.json
- package-lock.json
- package.json
- packages/build/src/core/config.js
- packages/build/src/core/main.js
- packages/build/src/env/changes.js
- packages/build/src/error/build.js
- packages/build/src/error/monitor/report.js
- packages/build/src/log/colors.js
- packages/build/src/log/logger.js
- packages/build/src/log/old_version.js
- packages/build/src/plugins/child/lazy.js
- packages/build/tests/error/fixtures/early_exit/plugin_slow.js
- packages/build/tests/helpers/server.js
- packages/build/tests/plugins/fixtures/error_argument/plugin.js
- packages/config/src/log/logger.js
- packages/config/src/validate/example.js
- packages/functions-utils/package-lock.json
- packages/functions-utils/package.json
- packages/functions-utils/tests/main.js
- packages/run-utils/src/main.js
State can make a codebase hard to follow. Following variables whose values change across different files and modules requires a higher cognitive load than following pure functions. I personally find it difficult.
This monorepo mostly follows that principle, and tries to only mutate variable where it is strictly necessary.  State mutation is still required in many instances, such as when shallow cloning an object would lose the prototype (e.g. in `Error`s), when several functions run in parallel need to communicate to each other, or when optimizing for performance.
This goes into the functional vs imperative topic, which is rather subjective. 
This PR's main intention is to maintain consistency with the existing code base programming style (which is functional) by adding a [ESLint …
> Add `eslint-plugin-fp`

- renovate.json5
This adds `os-name` to the list of dependencies not to upgrade due to Node 8 incompatibility.
> Add `os-name` to list of dependencies not to upgrade

- .eslintrc.json
- package-lock.json
- package.json
This removes `babel-eslint`. ESLint uses `espree` instead of `@babel/parser` by default, which is just fine for our use case. `babel-eslint` is only required when using new ES features added by `@babel/parser` but not `espree`.
Also, `babel-eslint` was deprecated and replaced by `@babel/eslint-parser`.
> Remove `babel-eslint`

- .eslintrc.json
- package-lock.json
- package.json
- packages/build/src/plugins/child/error.js
- packages/build/tests/install/fixtures/already/plugin/main.js
- packages/build/tests/install/fixtures/dir/functions/function/index.js
- packages/build/tests/install/fixtures/functions_error/functions/index.js
- packages/build/tests/install/fixtures/functions_npm/functions/index.js
- packages/build/tests/install/fixtures/functions_yarn/functions/index.js
- packages/build/tests/install/fixtures/functions_yarn_ci/functions/index.js
- packages/build/tests/install/fixtures/local_dep/functions/index.js
- packages/build/tests/install/fixtures/local_missing/plugin/main.js
- packages/build/tests/install/fixtures/mispelled_dep/functions/index.js
- packages/build/tests/install/fixtures/no_package/plugin/main.js
- packages/build/tests/install/fixtures/npm/plugin/main.js
- packages/build/tests/install/fixtures/optional/functions/index.js
- packages/build/tests/install/fixtures/yarn/plugin/main.js
- packages/build/tests/install/fixtures/yarn_ci/plugin/main.js
This adds an [ESLint plugin](https://github.com/mysticatea/eslint-plugin-eslint-comments) that ensures that are properly using ESLint comments like `// eslint-disable`. For example, it ensures we are not adding `// eslint-disable` when no ESLint rule was broken.
It also adds the `reportUnusedDisableDirectives` option which has similar goals.
Finally, it removes some `// eslint-disable` comments that were not needed.
> Lint ESLint comments

- packages/build/src/commands/get.js
- packages/build/src/commands/run.js
- packages/build/src/core/dry.js
- packages/build/src/status/add.js
Part of https://github.com/netlify/build/issues/1787, from the `onSuccess` current feature initiative.
`onEnd` and `onError` are handled slightly different from other events:
- `onError` only happens when an error happened
- `onError` is not shown in the number of commands about to be executed when in dry run
- `onEnd` happens regardless of whether an error happened or not
- the last event handler of any plugin, excluding `onError` and `onEnd`, defaults to implicitly calling `utils.status.show({ state: 'success' })`
This PR refactors the logic around the above, to make it clearer. It does not change any behavior.
> Refactor events filtering

- packages/build/src/log/main.js
Fixes https://github.com/netlify/pod-the-builder/issues/56
This improves the warning message shown when a plugin uses `failBuild()` or `cancelBuild()` in an `onSuccess`, `onEnd` or `onError` event handler.
> Improve post-deploy warning message

- packages/build/src/error/monitor/report.js
- packages/build/src/error/parse/parse.js
Part of https://github.com/netlify/buildbot/issues/939#issuecomment-686542767
This is a small refactoring of the logic used to retrieve/parse error information. It makes two different functions re-use the same underlying logic instead of duplicating it. This does not change behavior, except it handles better the case where the thrown exception is not an `Error` instance.
> Refactor error information parsing

- packages/build/src/error/info.js
Part of https://github.com/netlify/buildbot/issues/939#issuecomment-686542767
This improves handling errors that are not `Error` instances. In the previous code, `error[INFO_SYM]` would crash if `error` is not an `Error` instance.
> Improve handling of invalid errors

- packages/build/src/commands/error.js
Part of https://github.com/netlify/buildbot/issues/939#issuecomment-686542767
This improves handling build errors by using a higher-level error parsing function. This does not change the code behavior.
> Refactor build error parsing

- packages/build/src/commands/error.js
- packages/build/src/error/parse/parse.js
- packages/build/src/error/parse/serialize_log.js
- packages/build/src/error/parse/serialize_status.js
- packages/build/src/log/main.js
- packages/build/src/status/add.js
Part of https://github.com/netlify/buildbot/issues/939#issuecomment-686542767 feature
This refactors the code by splitting the functions responsible for serializing error into statuses and logs, and the function responsible for retrieving full error information. This does not change the logic.
> Improve error information parsing

- packages/build/src/error/cancel.js
- packages/build/src/error/monitor/report.js
- packages/build/src/error/parse/parse.js
- packages/build/src/error/parse/serialize_log.js
- packages/build/src/error/parse/stack.js
- packages/build/src/error/type.js
- packages/build/src/log/main.js
Part of https://github.com/netlify/buildbot/issues/939#issuecomment-686542767 feature
Note: this PR diff includes another PR (https://github.com/netlify/build/pull/1802). Once #1802 is merged, this PR can be rebased to make the diff smaller.
We currently have the three following error severity levels:
- `info`: user error:
- `warning`: plugin error
- `error`: system error
There is a fourth severity level: exceptions that are actually not errors. The only instance we currently have of those are build cancellations, which are handled as exceptions, but are still supposed to result in a successful build.
At the moment, those are using a boolean `isSuccess` flag. This PR switches to using a new severity level `none` instead. This will make it easier to map severity levels to exit codes.
> Add `error.severity: none`

- renovate.json5
This adds `yargs` to `renovate.json5` list of dependencies that do not support Node 8
> Add `yargs` to `renovate.json5`

- packages/build/src/core/bin.js
- packages/build/src/core/main.js
- packages/build/src/core/severity.js
- packages/build/tests/core/tests.js
- packages/build/tests/helpers/main.js
When the build fails, the `success` value returned programmatically is `true` instead of `false`.
This was not caught by our tests because:
- The `severity` is used instead of `success` by `@netlify/build` CLI
- The tests are only covering the logs output, not the programmatic return value
This PR fixes this bug and also:
- Adds tests for the programmatic return value
- Moves the logic that translates a `severity` to an exit code so that Netlify CLI can re-use it
> Fix wrong programmatic `success` return value

- packages/build/src/core/main.js
- packages/build/src/core/severity.js
- packages/build/src/error/type.js
- packages/build/tests/core/tests.js
The current `master` includes what happened to be a breaking change: cancelling the build with `utils.build.cancelBuild()` resulting in an exit code `0`. It turns out the buildbot relies on the exit code not being `0` in that case.
This PR fixes it by using exit code `0` for success, `1` for build cancellation, then incrementing all the other exit codes. All those exit codes have just been introduced, and not released to production yet, so this is not a breaking change.
> Fix exit code of build cancellation

- packages/config/src/main.js
- packages/config/tests/load/tests.js
Fixes https://github.com/netlify/build/issues/1816
When called as a binary, `@netlify/config` does not print the API `token` for security reasons. 
The return value of `@netlify/config` is printed on `stdout` which is used by the buildbot and passed back to `@netlify/config` using the `cachedConfig` option. When this happens, the `token` is therefore missing from `cachedConfig`. This results in `@netlify/config` return value missing the `token` under those conditions.
This means, in production, `constants.NETLIFY_API_TOKEN` passed to core plugins like the Edge handlers core plugins, is `undefined`. This PR fixes this problem. It also fixes the related integration test.
> Fix `token` returned by `@netlify/config`

- packages/build/src/commands/error.js
- packages/build/src/commands/get.js
- packages/build/src/commands/run.js
- packages/build/src/core/feature_flags.js
- packages/build/src/core/flags.js
- packages/build/src/core/main.js
- packages/build/src/plugins/child/load.js
- packages/build/src/plugins/child/run.js
- packages/build/src/plugins/child/utils.js
- packages/build/src/plugins/load.js
This uses the new `--featureFlags` CLI flag for the `onSuccess` post-deploy breaking change.
When `--featureFlags=postDeployErrors` is passed to `@netlify/build` from the buildbot, this will enable the following new behavior: errors inside plugin `onSuccess` and `onEnd` will not make the build fail. Instead, only the plugin itself will fail. This is a breaking change, and is therefore being a feature flag.
Before this PR, the feature was already available behing an environment variable. This PR uses the `--featureFlags` CLI flag instead as described in https://github.com/netlify/build/issues/1817 and https://github.com/netlify/buildbot/issues/949. This will allow using LaunchDarkly on it.
> Add `postDeployErrors` feature flag

- packages/build/src/core/normalize_flags.js
- packages/build/tests/core/tests.js
The two main ways `@netlify/build` is used (called `mode`) are the buildbot and the CLI. There is a third way: programmatically with `require()`. That third way is only useful in some specific cases, such as when testing a Build plugin.
Our telemetry logic does not make much sense in that mode, since the code could potentially be run a lot of times if the user is doing stress testing. Also, we found that this code is sometimes crashing. Therefore, it is safer to disable telemetry by default when `mode` is `require`, which this PR does.
> Fix telemetry crash when required programmatically

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/src/telemetry/complete.js
- packages/build/src/telemetry/track.js
The telemetry is sometimes crashing the whole `@netlify/build` process. It seems to be happening inside one of our dependencies `analytics`. This dependency is not useful and only adds complexity, so this PR aims at solving this problem by removing it.
The dependency adds few properties (such as an anonymous ID, etc.), so this PR adds those properties manually in an effort to ensure the behavior is exactly the same as before this PR. No behavior should change.
> Simplify telemetry

- packages/build/tests/time/tests.js
The tests for statsd are randomly failing in CI. I cannot reproduce this locally. 
This PR attempts to improve how failure of the test is currently being reported. Due to trailing spaces, it is hard to see the snapshot difference. The trailing spaces might also be the reason of the snapshot difference. Therefore this PR removes any trailing spaces.
> Try to fix statsd test

- packages/build/src/install/main.js
Part of https://github.com/netlify/build/issues/1853
We run `yarn` in a couple of cases. We use the `--cache-folder=$HOME/.yarn_cache` directory to re-use the cache directory from the buildbot. The command is currently executed with `execa.command()`, which assumes arguments are spaces-delimited. However, this assumption can be wrong when `$HOME` contains a space in it.
This PR switches to `execa()` instead, which does not require spaces escaping.
Ideally, a regression test should be added. This is quite an edge case on a piece of logic that is seldomly used, and creating an integration test is not straightforward, so I'd like to request the permission to skip it for this time :)
The logic around `yarn` is otherwise fully covered, and all tests are passing.
> Fix `yarn` when there is a space in the home directory

- packages/build/tests/helpers/normalize.js
Fixes #1853.
This improves how file paths inside test snapshots logs are being normalized when they contain spaces in them, especially on Windows when the user has a space in their username.
> Fix Windows support on some tests

- packages/config/docs/file_paths.md
This adds some documentation about the different file paths we use in the Netlify configuration.
We have many (current directory, repository root, build directory, configuration path, publish directory, function source/destination directories, edge handlers source/destination directories) so it can get pretty confusing quickly.
However, there are compelling reasons explaining why we do:
- We need to support both local/CLI users, UI users and programmatic users (e.g. our tests)
- Monorepo support
- We use many heuristics so users don't have to configure anything
- Some projects does not use Git
- Some projects do not distinguish between source directories and publish directories
Any new features involving file path resolution needs to pick the right directory to resolve from, and should …
> Add documentation about file paths

- packages/build/src/core/constants.js
- packages/build/src/core/flags.js
- packages/build/src/core/main.js
- packages/build/src/plugins/load.js
- packages/build/src/plugins/options.js
- packages/build/src/plugins_core/deploy/buildbot_client.js
- packages/build/src/plugins_core/deploy/index.js
- packages/build/src/plugins_core/deploy/manifest.yml
- packages/build/src/plugins_core/main.js
Currently deploys run after `netlify-build` has completed. This means that plugins can't run after the deploy has completed.
This PR allows the use of two flags: `--buildbotServerSocket` and `--triggerDeployWithBuildbotServer`. The second is designed to be removed once it is no longer in use. If both flags are passed, it enables a core plugin that sends a deploy message to the buildbot server as the final `onPostBuild` action (via a new core plugin).
Once this has been coordinated with other work in the buildbot, this will allow `onSuccess` and `onEnd` hooks to run after the deploy has completed and the site is live.
**Checklist**
> Run deploy as an onPostBuild event using a new core plugin

- packages/build/tests/plugins/tests.js
Now that Edge handlers bundling works on Windows, we can enable the CI tests on Windows.
> Enable tests for Edge handlers on Windows

- packages/build/src/core/feature_flags.js
- packages/build/src/core/flags.js
- packages/build/src/core/main.js
- packages/build/src/plugins/options.js
- packages/build/src/plugins_core/main.js
We have just added the `--feature-flags` CLI flag in #1823. This flag generalizes the concept of feature flags in order to avoid having to create new CLI flags for each new feature. This generalization helps with instrumenting this concept, e.g. connecting it with LaunchDarkly (https://github.com/netlify/buildbot/issues/949).
This PR replaces `--triggerDeployWithBuildbotServer` with `--feature-flags=triggerDeploy`.
> Use `--feature-flags=triggerDeploy`

- packages/build/src/log/messages/plugins.js
- packages/build/src/plugins_core/deploy/index.js
This adds a log message when the core deploy plugin successfully deploys a Site. 
This makes it clear for plugins running `onSuccess` and `onEnd` events that the Site has now been deployed.
> Add deploy message

- packages/build/src/plugins_core/deploy/index.js
Deploy should happen at the end of `onPostBuild`, right before `onSuccess`. At the moment, it is done at the end of `onBuild`, right before `onPostBuild`.
> Fix core deploy event

- packages/build/src/plugins_core/deploy/buildbot_client.js
When something went wrong inside the deploy core plugin, we close the TCP connection with the buildbot.
However, it is possible this connection has already ended. In that case, `client.end()` will throw, and the original error will be gone, making debugging harder.
This PR solves this problem by not attempting to end the connection when it has already ended.
> Improve error handling when buildbot socket closes

- packages/build/src/plugins_core/deploy/buildbot_client.js
- packages/build/src/utils/errors.js
This prepends error messages when the connection with the buildbot TCP socket (used by the deploy core plugin) fails, which would indicate a bug. Those error messages can help us locate which line of code went wrong, since the stack trace seems to be sometimes missing.
The `error` instance is kept since it usually is a Node.js core error which contains useful static properties.
The cases where the socket might fail:
- Could not connect to the buildbot socket
- Could not send a message to the buildbot socket
- Could not receive a message from the buildbot socket
- The buildbot socket sent a response with `succeeded: false` (this one was already implemented)
Instead of repeating similar looking `try`/`catch` blocks, this PR adds a utility helper.
> Improve error handling of the buildbot socket

- packages/build/src/core/constants.js
- packages/build/src/core/main.js
- packages/build/src/plugins_core/deploy/buildbot_client.js
- packages/build/src/plugins_core/deploy/index.js
This adds a `--testOpts.buildbotServerSocketTimeout` CLI flag. It defaults to 60 seconds. This modifies how long the deploy core plugin waits for a buildbot TCP response before timing out. This is meant for testing purpose.
> Add `--testOpts.buildbotServerSocketTimeout` CLI flag

- renovate.json5
This adds `del` to the list of dependencies that cannot be upgraded due to their lack of support for Node 8.
> Add `del` to Node 8 dependencies

- packages/build/src/commands/plugin.js
- packages/build/src/plugins/child/run.js
- packages/build/src/plugins/load.js
There are some arguments that we'd like to pass to some core plugins, but not to user plugins:
- `constants.API_TOKEN` used to be meant only for the Edge handler core plugin
- `constants.BUILDBOT_SERVER_SOCKET` is meant only for the core deploy plugin
- an upcoming PR will pass the list of plugin events, which is meant only for the core deploy plugin
The core plugin-only information was previously computed at the wrong point in the codebase. It allowed up to cleanup core plugin-only `constants` but this was done too early to cleanup core plugin-only information like the list of plugin events.
This PR moves this logic in order to support that new use case.
> Move core plugin-specific information

- packages/build/src/commands/get.js
- packages/build/src/commands/plugin.js
- packages/build/src/commands/run_command.js
- packages/build/src/commands/run_commands.js
- packages/build/src/core/main.js
- packages/build/src/plugins/child/run.js
- packages/build/src/plugins_core/deploy/buildbot_client.js
- packages/build/src/plugins_core/deploy/index.js
- packages/build/tests/plugins/fixtures/end/manifest.yml
- packages/build/tests/plugins/fixtures/end/netlify.toml
- packages/build/tests/plugins/fixtures/end/plugin.js
- packages/build/tests/plugins/fixtures/success/manifest.yml
- packages/build/tests/plugins/fixtures/success/netlify.toml
- packages/build/tests/plugins/fixtures/success/plugin.js
- packages/build/tests/plugins/tests.js
Builds that use `onSuccess` and `onEnd` needs to wait for post-processing to end, which can take time.
Until we figure out whether this is something we want or not, this PR disables waiting for post-processing if the build does not use any of those events. It does it by sending a different action to the buildbot, which then uses it to decide whether to wait on post-processing or not.
This PR includes 3 integration tests.
> Do not wait for post-processing for most builds

- packages/build/src/core/lingering.js
Fixes #1896.
This does not report the lingering processes from Gatsby telemetry and Jest workers.
> Fix lingering processes warning

- packages/build/src/plugins_core/deploy/buildbot_client.js
- packages/build/src/plugins_core/deploy/index.js
- packages/build/tests/plugins/fixtures/invalid_publish/netlify.toml
- packages/build/tests/plugins/tests.js
Fixes #1912.
When publishing a site and the publish directory does not exist, this prints a user error message, as opposed to a system error.
@Benaiah @vbrown608, could you please confirm that, when a publish directory does not exist while publishing a site, this is always an error?
> Fix publish directory bug with the deploy core plugin

- packages/build/src/core/lingering.js
Follow-up on #1897 and #1896.
A popular Babel plugin [`broccoli-babel-transpiler`](https://github.com/babel/broccoli-babel-transpiler), part of Ember CLI, has a [known issue](https://github.com/babel/broccoli-babel-transpiler/issues/169) leaving child processes running. Due to moving the lingering processes to Netlify Build, those are now printed as warnings. This PR removes those warnings.
> Tweak lingering processes detection

- packages/build/src/utils/resolve.js
This renames some internal variables to ensure that Promises follow the usual `resolve`/`reject` naming convention.
> Small internal variable name fix

- .eslintrc.json
- packages/build/src/env/git.js
- packages/build/src/error/monitor/report.js
- packages/build/src/error/monitor/start.js
- packages/build/src/plugins/resolve.js
- packages/build/src/telemetry/track.js
- packages/build/tests/helpers/dir.js
- packages/cache-utils/src/fs.js
- packages/config/src/options/branch.js
This removes some unnecessary `return` statements. 
In order to do it, this also fixes the `no-empty` ESLint rule.
> Remove unnecessary `return` statements

- .eslintrc.json
- package-lock.json
- package.json
Using Node `8.3.0`, many common utilities provided by Lodash or Underscore can now be done with vanilla JavaScript with the same expressiveness. In those cases, using vanilla JavaScript is better than introducing an additional utility, as it is faster, easier to debug and clearer.
This PR adds an ESLint plugin that lints against those patterns. It does not prevent using those libraries, it just prevents using them in cases they are not needed.
> Lint Lodash and Underscore

- .github/workflows/workflow.yml
This upgrades the Node.js version in CI from `8.3.0` to `8.17.0`.
This does not upgrade the `engines.node` minimal versions, keeping them as `8.3.0`.
> Upgrade Node.js version in CI

- renovate.json5
Yet another dependency not supported in Node 8 anymore.
> Add `update-notifier` to `renovate.json5`

- packages/build/src/log/messages/config.js
The `buildbotServerSocket` CLI flag should not be printed in build logs, it is internal only.
> Do not show the `buildbotServerSocket` CLI flag in production

- .eslintrc.json
- package-lock.json
- package.json
- packages/build/tests/README.md
- packages/build/tests/helpers/common.js
- packages/build/tests/plugins/fixtures/handlers_simple/edge-handlers/test.js
- packages/config/tests/cli/tests.js
This adds [`eslint-plugin-ava`](https://github.com/avajs/eslint-plugin-ava) to lint our Ava test files.
What do you think @erezrokah?
> Lint Ava test files

- .eslintrc.json
This fixes the `no-unused-vars` ESLint rule so it warns against unused arguments. I am not quite sure why this requires this empty object, but it does :)
> Fix `no-unused-vars` rule

- packages/git-utils/README.md
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`explicit-length-check`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/explicit-length-check.md).
> Fix `Array.length` linting error

- packages/build/tests/helpers/main.js
This fixes a linting error from `eslint-plugin-unicorn`.
> Small file path linting error

- packages/build/src/log/logger.js
- packages/build/tests/helpers/normalize.js
- packages/config/src/log/logger.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`escape-case`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/escape-case.md).
> Use consistent case in \u escapes

- packages/build/src/error/parse/normalize.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`no-array-instanceof`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-array-instanceof.md).
> Use `Array.isArray()`

- packages/build/src/error/monitor/normalize.js
This fixes the linting errors from the `eslint-plugin-unicorn` rule [`better-regex`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/better-regex.md).
> Improve RegExps

- .eslintrc.js
- packages/build/src/plugins/ipc.js
- packages/build/tests/core/tests.js
- packages/build/tests/env/fixtures/bugsnag_key/index.js
- packages/build/tests/env/fixtures/empty_string/index.js
- packages/build/tests/error/fixtures/command_full_stack/command.js
- packages/build/tests/error/fixtures/early_exit/plugin.js
- packages/build/tests/error/fixtures/early_exit/plugin_slow.js
- packages/build/tests/error/fixtures/ipc/plugin.js
- packages/build/tests/error/fixtures/plugin_exit/plugin.js
- packages/cache-utils/tests/dir.js
- packages/cache-utils/tests/path.js
- packages/git-utils/tests/main.js
- packages/run-utils/src/main.js
This adds the `node/prefer-global/process` ESLint rule (see [rule documentation](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/prefer-global/process.md)).
This is useful to ensure we are consistent with how we access the `process` global variable.
This is also useful to require this in the top of the file since it is technically a dependency (albeit it is also available as a global variable).
> Lint `process` variable

- .eslintrc.js
- packages/build/src/plugins/child/logic.js
- packages/build/src/plugins/child/utils.js
- packages/build/tests/plugins/tests.js
This adds the [`node/global-require`](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/global-require.md) and [`node/no-mixed-requires`](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-mixed-requires.md) ESLint rules.
Dynamic `require()` statements should be avoided when possible.
There are some cases when those are useful though. In those cases, `// eslint-disable-next-line` can be used.
> Lint dynamic `require()` statements

- .eslintrc.js
- packages/build/src/plugins/ipc.js
[`eslint-plugin-node`](https://github.com/mysticatea/eslint-plugin-node) has lots of great linting rules. Those would be very useful to improve our code quality and ensure consistency.
This PR is added the recommended rules, and enabling some additional rules (with their default options) which are useful. Please let me know what you think! If there are specific rules you think we should disable, please let me know.
> Add more rules from `eslint-plugin-node`

- packages/build/src/time/report.js
The statsd test is randomly failing.
This seems to be due to the statsd library we are using. That library buffers packets to be sent. When closing the connection, it does not provide with a callback/promise/event to know when the buffer is flushed. Therefore, we need to use an unconditional timeout. Adding a second `pTimeout()` seems to fix it, by making sure the microtask created by the library's underlying `setTimeout()` is set first.
> Fix `statsd` test

- .github/workflows/workflow.yml
Fixes #1962.
Also implemented in Netlify CLI at https://github.com/netlify/cli/pull/1387
This runs linting on Node 14 only in CI.
> Only run linting on Node 14 in CI

- package-lock.json
- package.json
- renovate.json5
Part of https://github.com/netlify/build/issues/1962
This upgrades ESLint now that it's only run on Node 14.
> Upgrade ESLint

- .eslintrc.js
The `.eslintrc.js` file is quite big. This triggers the `max-lines` ESLint rule. However, there might not be strong benefits in breaking that specific file into smaller files.
> Add a `eslint-disable` comment

- packages/build/src/plugins_core/deploy/buildbot_client.js
- packages/build/src/plugins_core/deploy/index.js
- packages/build/tests/plugins/fixtures/invalid_publish/netlify.toml
- packages/build/tests/plugins/tests.js
Fixes https://github.com/netlify/buildbot/issues/1003
This removes the validation check for the publish directory now that the buildbot is doing it.
This effectively reverts #1915
> Remove validation check for the publish directory

- .eslintrc.js
`test.only()` and `test.skip()` are useful in debugging. Enabling those ESLint rules would prevent from using those due to the autofix on file save.
> Configure `ava/no-only-test` ESLint rule

- .eslintrc.js
- packages/build/tests/error/fixtures/early_exit/plugin_slow.js
This adds the [`no-await-in-loop`](https://eslint.org/docs/rules/no-await-in-loop) ESLint rule.
> Add `no-await-in-loop` ESLint rule

- .eslintrc.js
- packages/build/src/time/main.js
This adds the [`func-names`](https://eslint.org/docs/rules/func-names) ESLint rule.
> Add `func-names` ESLint rule

- .eslintrc.js
- packages/build/tests/plugins/fixtures/handlers_custom_dir/custom-edge-handlers/test.js
- packages/build/tests/plugins/fixtures/handlers_simple/edge-handlers/test.js
This adds the [`func-style`](https://eslint.org/docs/rules/func-style) ESLint rule.
> Add `func-style` ESLint rule

- .eslintrc.js
Now that linting is only performed in Node 14, this PR removes some dead code.
> Remove some dead code related to linting

- .eslintrc.js
This enables the [`no-process-exit`](https://eslint.org/docs/rules/no-process-exit) ESLint rule.
> Add `no-process-exit` ESLint rule

- .eslintrc.js
- packages/build/src/error/monitor/report.js
- packages/build/src/time/report.js
This adds the [`no-underscore-dangle`](https://eslint.org/docs/rules/no-underscore-dangle) ESLint rule.
> Add `no-underscore-dangle` ESLint rule

- .prettierrc.json
The `endOfOption` Prettier option defaults to `lf`, so this can be removed.
> Simplify Prettier configuration

- packages/build/src/error/parse/clean_stack.js
When printing errors in build, we remove stack trace lines that are internal to `@netlify/build` or to Node.js. 
Node 15 introduces a new syntax for internal Node.js stack trace line, starting with `node:`. This PR fixes it, and refactors this code a little.
> Fix stack trace cleaning for Node 15

- .eslintrc.js
This fixes some linting which does not work when targeting Node `8.3.0` since those global variables have been added by Node `11.0.0` and `12.0.0`.
> Fix Node globals linting

- packages/functions-utils/README.md
This adds the `name` property now returned by `utils.functions.listFunctions()` to its `README.md`.
> Add new `name` property in `functions-utils` `README.md`

- .eslintrc.js
- package-lock.json
- package.json
This upgrades `eslint-config-node` and simplifies the linting configuration thanks to it.
> Use new `eslint-config-node`

- packages/build/package-lock.json
- packages/build/package.json
- packages/build/tests/core/tests.js
- packages/build/tests/env/tests.js
- packages/build/tests/error/tests.js
- packages/build/tests/helpers/server.js
- packages/build/tests/status/tests.js
- packages/config/tests/api/tests.js
We use a mock HTTP server in automated tests.
Note: we unfortunately cannot use `nock` or similar library because they do not work across processes (since they rely on modifying global variables), which is why we have our own test helper.
This PR improves it to allow mocking several endpoints at once in a single test. Previously, only one endpoint could be mocked at a time.
> Improve mock HTTP server

- packages/build/tests/error/tests.js
This is a small refactoring of the tests related to build cancellation. This does not modify them.
> Simplify tests related to build cancellation

- packages/build/src/commands/get.js
- packages/build/src/core/dry.js
- packages/build/src/core/main.js
We need to count the number of "commands" (build command or plugin) run for two reasons:
- To print some arrow symbol in dry runs
- To send to telemetry
Those two use cases are slightly different, because dry runs to not take into account that some commands might not end up being run during build (for example if they errored).
This PR refactors the logic to make the distinction between those use cases clearer, by moving code. It does not modify behavior.
> Refactor `commandsCount`

- renovate.json5
This improves the Renovate config so new Netlify packages are creating PRs right away.
> Improve renovate config

- packages/config/src/api/site_info.js
Noticed this while doing some refactoring on the CLI (PR coming soon). When the passed `siteId` argument is `undefined` the return value is `{ id: undefined }` which makes it harder to check using `isEmpty` utility methods.
> We can also keep the current behavior if this was intended (to distinguish between an error and `undefined` argument).
This PR fixes the behavior to match the result when an error occurs.
Keep the code as is and check `siteInfo.id === undefined || isEmpty(siteInfo)`
**Checklist**
> fix(config): return empty object on undefined site id

- packages/build/src/plugins/list.js
- packages/build/src/plugins/resolve.js
This moves an internal function to accommodate with some upcoming PRs.
This does not change behavior.
> Move `logPluginsList()`

- packages/build/src/install/missing.js
- packages/build/src/plugins/resolve.js
This moves some internal logic related to `autoPluginsDir` to accommodate with an upcoming PR.
This does not change behavior.
> Move `autoPluginsDir` logic

- packages/build/src/plugins/resolve.js
- packages/build/src/utils/resolve.js
This refactors how `require.resolve()` is called. This does not change behavior.
> Add `tryResolvePath()`

- packages/build/src/plugins/resolve.js
This is a small refactoring of the `loadedFrom` attribute related to plugins build caching. This does not change behavior.
> Small refactoring of `loadedFrom` attribute

- packages/build/src/plugins/resolve.js
This refactors some logic related to local plugins installation.
This does not change behavior.
> Refactor local plugins installation

- packages/build/src/plugins/list.js
This adds a 10 seconds timeout when fetching the plugins list.
After that timeout, we fallback to using the plugins list from the last time Netlify Build was released in production, which can be a few days old. We also print a warning message.
> Add HTTP request timeout when fetching the plugins list

- packages/build/src/utils/resolve.js
Follow-up on #2101.
`require.resolve()` is showing other instances of odd behavior. This time, it throws instead of returning an invalid file path.
This PR switches to using the `resolve()` external package first, and `require.resolve()` as a fallback instead. `require.resolve()` is hard to debug (since its code is inside the `node` binary) and seems to have a couple of issues.
> Fix `resolve` bug

- packages/build/tests/error/tests.js
A test is randomly failing and I'm having issues pinpointing the timing-related race condition here. This PR skips the test for the time being.
> Skip a randomly failing test

- packages/build/src/core/constants.js
A small follow up on https://github.com/netlify/build/pull/2175 to show `\` instead of `/` when printing the log message on Windows.
> fix(windows): show windows path separator in netlify dir warning message

- CONTRIBUTING.md
- package.json
- packages/build/package.json
- packages/cache-utils/package.json
- packages/config/package.json
- packages/functions-utils/package.json
- packages/git-utils/package.json
- packages/run-utils/package.json
This adds a `prepublish` npm script to automate the release process even further.
I have tried it locally both on Unix and Windows.
> Add `prepublish` npm scripts

- CONTRIBUTING.md
Adding a simple note to our `CONTRIBUTING.md` around releasing build and config.
> chore(docs): adding a note  on releasing config and build

- CONTRIBUTING.md
Fix inconsistencies in capitalization of noun Renovate.
There are no other issues that I'm fixing with this.
Fix typo.
Not applicable.
**Checklist**
> chore(docs): capitalize all instances of noun Renovate

- packages/build/src/error/monitor/normalize.js
Bugsnag [is currently reporting](https://app.bugsnag.com/netlify/netlify-build/errors?filters[event.since][0][type]=eq&filters[event.since][0][value]=all&filters[app.release_stage][0][type]=ne&filters[app.release_stage][0][value]=require&filters[event.severity][0][type]=eq&filters[event.severity][0][value]=error&filters[event.severity][1][type]=eq&filters[event.severity][1][value]=warning&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[metaData.location.loadedFrom][0][type]=ne&filters[metaData.location.loadedFrom][0][value]=local&filters[error.has_issue][0][type]=eq&filters[error.has_issue][0][value]=false&filters[search][0][type]=eq&filters[search][0][value]=upload&sort=last_seen) every new instance of deploy upload errors separately. This PR groups them …
> fix: improve Bugsnag reporting of upload errors

- packages/build/package.json
- packages/cache-utils/package.json
- packages/config/package.json
- packages/functions-utils/package.json
- packages/git-utils/package.json
- packages/run-utils/package.json
npm 7 changed the way globbing patterns are interpreted in `files` in `package.json`. This is undocumented, so I'm not sure whether this is a bug or not. This results in all `*~` files (Vim temporary files) to be published to npm, which can double the package size. 
This PR fixes this. I ran `npm pack --dry` before and after to ensure no files were being omitted.
> fix: fix `files` in `package.json` with `npm@7`

- packages/build/tests/plugins/tests.js
This fixes a typo in a test.
The field in `plugins.json` is named `package` not `packageName`.
> chore: fix typo in test

- packages/build/src/install/missing.js
- packages/build/src/plugins/resolve.js
Part of https://github.com/netlify/next-on-netlify-enterprise/issues/16
This refactors some code related to how we install UI plugins when they are "missing" (i.e. either not cached yet, or cached with a version that does not match the latest in `plugins.json`). This does not change the logic, only moves code around. This refactoring should help with some upcoming related PRs.
> chore: refactor missing plugins logic

- .eslintrc.js
The `import/no-extraneous-dependencies` ESLint rule is currently failing with npm 7 monorepos due to a bug.
https://github.com/benmosher/eslint-plugin-import/issues/1986
> chore: fix `import/no-extraneous-dependencies` ESLint rule

- packages/build/src/log/messages/plugins.js
- packages/build/src/plugins/expected_version.js
- packages/build/src/plugins/list.js
- packages/build/tests/plugins/tests.js
Part of https://github.com/netlify/next-on-netlify-enterprise/issues/16
This allows the `version` field in `plugins.json` to an an object instead of a string. Using a string is still supported.
This enables specifying several supported versions per plugin.
More upcoming PRs will add more logic to that field, so that our system can choose between different versions of each plugin.
> feat: allow `version` in `plugins.json` to be an object

- packages/build/src/log/messages/plugins.js
- packages/build/src/plugins/compatibility.js
- packages/build/src/plugins/expected_version.js
- packages/build/src/plugins/list.js
- packages/build/tests/plugins/tests.js
This adds a `compatibility` field to plugin so they can declare several versions.
This does not add any conditions yet, only the bare field.
> feat: add `plugin.compatibility` field

- packages/build/src/plugins/list.js
- packages/build/tests/plugins/tests.js
Part of https://github.com/netlify/next-on-netlify-enterprise/issues/16
This makes the `compatibility` field an array of object:
```js
{
"package": "netlify-plugin-example",
"version": "2.0.1"
"compatibility": [
{ "version": "1.0.5", nodeVersion: "<14" },
{ "version": "0.3.8", nodeVersion: "<12" }
]
}
```
instead of an object of objects:
```js
{
"package": "netlify-plugin-example",
"version": "2.0.1"
"compatibility": {
"1.0.5": { nodeVersion: "<14" },
"0.3.8": { nodeVersion: "<12" }
}
}
```
I believe this format might be a little cleaner, and more explicit about the priority order.
> feat: turn `compatibility` field into an array

- packages/build/src/plugins/list.js
Part of https://github.com/netlify/next-on-netlify-enterprise/issues/16
There is no need to sort `compatibility` because its order is validated at PR-time (see https://github.com/netlify/plugins/pull/226).
> feat: do not sort `compatibility` field

- packages/build/src/log/messages/core_commands.js
With this PR, Build delegates the responsibility of printing esbuild errors/warnings to `zip-it-and-ship-it` (depends on https://github.com/netlify/zip-it-and-ship-it/pull/357). This hugely simplifies the logic of handling the errors, which helps in situations like https://github.com/netlify/cli/issues/1838#issuecomment-790481394.
I've tried to add custom logic for truncating error messages, but unfortunately esbuild seems to have a bug where it misreports the line/column of the error. I think that using the default error/warning logging from esbuild is the best course of action for now.
Depends on https://github.com/netlify/zip-it-and-ship-it/pull/357
**Checklist**
Please add a …
> fix: stop printing output from esbuild

- packages/build/src/core/config.js
- packages/config/src/main.js
- packages/config/src/options/main.js
This renames the `apiHost` option in `@netlify/config` to `host` in order to maintain backward compatibility.
The `apiHost` option in `@netlify/build` is kept as is since no `host` option existed there before. If you think this should be renamed for naming consistency, please let me know.
> fix: fix `host` option in `@netlify/config`

- packages/config/src/main.js
This is a small refactoring of how options are retrieved in `@netlify/config`, making them more explicit.
This does not change behavior.
> chore: small refactoring of `@netlify/config` options retrieval

- package-lock.json
- packages/build/package.json
- packages/build/src/core/constants.js
- packages/cache-utils/package.json
- packages/cache-utils/src/dir.js
- packages/cache-utils/src/list.js
- packages/cache-utils/src/main.js
- packages/cache-utils/src/path.js
- packages/cache-utils/tests/dir.js
- packages/cache-utils/tests/helpers/main.js
- renovate.json5
Part of https://github.com/netlify/build/issues/2369
This removes some logic used to retrieve the cache directory that is not used anymore:
- The buildbot now uses the `--cache-dir=/opt/build/cache` CLI flag
- CLI and programmatic builds now rely on the default value `{buildDir}/.netlify/cache/`
The OS-specific and mode-specific can now be safely removed. This allows simplifying the logic.
> chore: simplify cache directory logic

- packages/build/src/plugins/expected_version.js
- packages/build/src/plugins/resolve.js
Part of #2403.
This refactors how `plugin.expectedVersion` and `isMissing` are computed. This does not change any behavior, just makes it clearer.
> chore: refactor `plugin.expectedVersion`

- package.json
Wanted to know what you folks think of running `npm ci` instead of `npm install` on prepublish. This forces the `node_modules` dir to be recreated according to the lockfile (only), running tests against the exact dependency tree we expect. I've been tricked more than once, by checking out master, forgetting to run npm ci, and having the tests fail during a release because I've got an outdated dep locally installed for example (or some weird node_modules inconsistency).
> chore(prepublish): use npm ci instead of npm install on prepublish

- packages/build/src/core/lingering.js
Part of #1966.
This improves the `ps` command call:
- `u` is not needed since we only need the command names + arguments
- `o command` allows printing only command names, since that's the only thing we want to `grep` 
- thanks to `o command`, the warning message now print only the command names + arguments, since the other columns are just confusing to users and not helpful
- `h` removes the top header row, which allows simplifying some of the logic
> feat: improve lingering processes list

- packages/build/src/core/lingering.js
When there are no lingering processes, the build currently fails. This is because `grep` (with default options) returns an exit code `1` when there are no matches.
This is since #2475, which was not released to production.
This was caught while testing in the buildbot PR. Automated tests are currently partial for this feature, due to #1888. This will be fixed in follow-up PRs.
> fix: do not fail when there are no lingering processes

- packages/build/src/log/logger.js
- packages/build/src/log/messages/core.js
- packages/build/src/log/messages/core_commands.js
- packages/build/src/log/messages/plugins.js
- packages/build/src/log/theme.js
Fixes #2389.
This uses a yellow/orange color for warnings, to distinguish them from errors (red).
Example:
> feat: distinguish between warnings and errors in build logs

- packages/build/src/core/lingering.js
This fixes an empty list of lingering processes being shown in build logs.
Example: https://app.netlify.com/sites/mick/deploys/605e1f6baff2cb000778c50c#L283
That bug was not released to production.
> fix: do not show an empty list of lingering processes

- renovate.json5
We cannot upgrade `read-pkg-up` since it drops support for Node 8 and 10.
> chore: add `read-pkg-up` to list of dependencies which cannot be upgraded

- packages/build/src/core/lingering.js
Part of #1966
This adds some comments to explain why specific lingering commands are ignored.
> chore: add comments on the list of ignored lingering commands

- packages/build/package.json
- packages/build/src/core/lingering.js
- packages/build/tests/core/tests.js
Part of #1966.
This makes the lingering processes logic work on Windows.
`ps-list` uses the following commands internally on Unix: `ps wwxo pid,comm,args,ppid,%cpu,%mem`
- `ww` and removing `h` are only formatting options
- the `a` is removed, which is good since we don't want to print lingering processes owned by a different user
- the extra columns are not used by our code
- the `command` column is now `args`, which is an alias
I.e. the behavior should be the same (I manually tested it in production)
> feat: make lingering processes logic work on Windows

- packages/build/src/error/type.js
This adds some documentation about adding new error types in Bugsnag, for contributors.
> chore: add documentation about adding new error types in Bugsnag

- packages/build/tests/install/tests.js
Part of https://github.com/netlify/build/issues/2512
Two Yarn-related tests are currently failing on Node <14.
This PR skips them until we fix the underlying problem.
> fix: disable 2 Yarn-related tests on Node <14

- packages/config/src/context.js
- packages/config/src/origin.js
Part of #1169.
This refactors how `commandOrigin` is added when using `context.{context}.command`.
This refactoring does not change any behavior, but will help with some upcoming PRs.
> feat: refactor how `origin` is added to context-specific configs

- packages/config/src/context.js
- packages/config/src/main.js
- packages/config/src/merge_normalize.js
- packages/config/src/validate/main.js
Part of #1169.
This refactors the config validation and normalization logic. This does not change behavior except that it now ensures that that logic applies not only to the main `config` object, but also to `inlineConfig` and `defaultConfig` (UI config).
This is part of a larger refactoring needed for plugins-specific config.
> fix: improve config normalization logic

- packages/config/src/context.js
- packages/config/src/main.js
- packages/config/src/merge.js
- packages/config/src/merge_normalize.js
- packages/config/src/origin.js
Part of #1169.
This refactors/simplifies how `config.build.commandOrigin` and `config.plugins[*].origin` are set in `@netlify/config`. This does not change behavior, except that it allows `origin` to be set in context-specific config.
> feat: refactor configuration property origins

- packages/config/src/merge.js
Part of #1169.
This is a small refactoring of how `config.plugins` gets merged together between `defaultConfig`, `config` and `inlineConfig`. This does not change behavior.
> feat: refactors how plugins configurations are currently merged

- packages/config/src/context.js
- packages/config/src/files.js
- packages/config/src/main.js
- packages/config/src/merge.js
- packages/config/src/normalize.js
- packages/config/src/utils/merge.js
Part of #1169.
This refactors the logic that merges configuration objects.
This does not change it, just refactors it.
This makes it clearer that this logic is only intended to merge configuration objects. This also removes the usage of a variadic argument and enforces that the arguments are defined.
> feat: refactor configuration merge logic

- package-lock.json
- packages/build/package.json
- packages/build/src/log/messages/core.js
A warning message is including a link as Markdown. However, we don't support Markdown using `console.log()` :man_facepalming: 
Instead, this PR switches it to an OSC hyperlink.
This properly works. [Example build logs](https://app.netlify.com/sites/mick/deploys/607090e64d1fe20007f2403b#L224)
> fix: warning message link

- renovate.json5
Those dependencies now need Node 12
> chore: add p-reduce and path-key to `renovate.json5`

- packages/build/tests/helpers/common.js
Spaces do not currently work when used in CLI flags in tests. This PR fixes this.
> chore: allow spaces in CLI flags in tests

- package-lock.json
- packages/build/package.json
This fixes tests failing due to not upgrading the new major release of `@netlify/config`.
> fix: `@netlify/config` major release

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
- .github/workflows/fossa.yml
- .github/workflows/release-please.yml
- .github/workflows/workflow.yml
- README.md
- codecov.yml
- packages/cache-utils/README.md
- packages/functions-utils/README.md
- packages/git-utils/README.md
- packages/run-utils/README.md
Aligns this repo with our other repos
I haven't done the renaming yet - I'll do it + merge the PR at the same time
> We also have other references to `master` in our codebase:
https://github.com/netlify/build/blob/5be097a578c0e1b1459901724a075708a4cae59f/packages/config/src/options/branch.js#L30
https://github.com/netlify/build/blob/5be097a578c0e1b1459901724a075708a4cae59f/packages/git-utils/src/refs.js#L34
We should think about on how to address those separately
> chore: rename default branch from master to main

- packages/build/src/log/messages/plugins.js
Part of #2578.
This refactors the logic related to some warning message printed on incompatible or outdated plugins. This does not change the behavior.
> feat: refactor incompatible/outdated plugins warnings

- package-lock.json
- packages/build/package.json
- packages/build/src/error/monitor/start.js
- packages/build/src/plugins/child/lazy.js
The latest release of `memoize-one` introduced a breaking change for the `cjs` exports - https://github.com/alexreardon/memoize-one/releases/tag/v5.2.0 - this PR addresses those.
Fixes #2642
> fix(deps): memoize-one cjs exports breaking changes

- packages/git-utils/src/refs.js
This ensures `utils.git` works for repositories with a `main` branch (as opposed to `master`).
This only impacts local builds.
`main` has priority over `master`, but this should not be a breaking change unless a repository has both branches, which seems unlikely. Note: if neither is present, `HEAD` is used instead.
> fix: fix `utils.git` for repositories with `main` branch

- packages/config/README.md
- packages/config/src/options/branch.js
`@netlify/config` uses the git branch to apply branch-specific context configuration.
In production, this is [passed by the buildbot](https://github.com/netlify/buildbot/blob/b47b671c7e5601877c51968241eb899bf590a815/bot/configuration.go#L124).
In local builds, we use the `--branch` CLI flag. If undefined, we use the branch of `HEAD`. If this is also undefined, this means the user has done a `git checkout` outside of a branch, which is very unlikely. In that unlikely scenario, we use `master`. This PR adds an additional check for a `main` branch, if it exists, before falling back to `master`.
> fix: support `main` branch in `@netlify/config`

- package-lock.json
- packages/build/package.json
- packages/build/src/error/monitor/start.js
- packages/build/src/plugins/child/lazy.js
Addresses https://github.com/alexreardon/memoize-one/releases/tag/v5.2.1 and its latest changes to the exports.
> fix(deps): memoize-one breaking change in exports

- renovate.json5
Do not upgrade modules that use ES modules.
> chore: do not upgrade modules using ES modules

- packages/build/src/plugins/pinned_version.js
This PR ensures `api.updatePlugin` is never called in production, since that new API endpoint currently has a bug which makes it return `404`.
> chore: revert updatePlugin PR

- packages/build/src/plugins/pinned_version.js
The previous PR used the wrong conventional commit prefix, which prevented `release-please` from creating a release PR.
> fix: use the proper conventional commit in PR title

- packages/build/src/plugins/pinned_version.js
This is a small improvement over https://github.com/netlify/build/pull/2693, which ensures the fix works even if `siteId` is `test`.
I do not think `siteId` can be `test` in production since I'd assume it is always a UUID, but this is just in case.
> fix: improve temporary fix for the `updatePlugin` bug

- packages/build/src/plugins/pinned_version.js
Fixes https://github.com/netlify/build/issues/2700
The `packageName` request to `updatePlugin` should be URI-encoded. The `js-client` does not currently do this by default. (see https://github.com/netlify/js-client/issues/404)
> fix: percent-encode the `package` parameter of the `updatePlugin` endpoint

- packages/build/src/plugins/compatibility.js
- packages/build/src/plugins/expected_version.js
Fixes #2752.
We currently used two different functions to retrieve `expectedVersion` and `compatibleVersion`. Those are the same except for whether `pinnedVersion` is defined. Therefore we can merge them without changing the logic.
> fix: simplify version pinning logic

- packages/build/src/plugins/list.js
As a first step to fix #2788, this PR adds the `version` property in `plugins.json` as a first item in the `compatibility` array.
Once this is done and released, I will update the `plugins.json` to change the few plugins in `plugins.json` with a `compatibility` array so they include the latest version. I will then add some validation in the automated tests in `netlify/plugins`.
Once this is done, this PR can be reverted.
> feat: change shape of `compatibility` field

- packages/build/src/log/messages/plugins.js
- packages/build/src/plugins/compatibility.js
- packages/build/src/plugins/expected_version.js
- packages/build/src/plugins/list.js
- packages/build/tests/plugins/tests.js
This fixes #2788.
Now that the `compatibility` field is either `undefined` or includes the latest version as the first item, some of the logic can be simplified, which this PR implements.
> feat: simplify version pinning logic

- packages/build/src/commands/plugin.js
- packages/build/src/commands/run_command.js
- packages/build/src/core/main.js
- packages/build/src/plugins/child/load.js
- packages/build/src/plugins/child/run.js
- packages/build/src/plugins/load.js
Part of #1193 
At the moment, we pass `netlifyConfig` from the parent process to the plugin process only once, when the plugin starts. In order to make `netlifyConfig` mutable and ensure mutations propagate between plugins, we need to pass the latest `netlifyConfig` at the beginning of each plugin event handler instead. This PR implements this.
> feat: pass `netlifyConfig` to each event handler

- packages/build/src/commands/plugin.js
- packages/build/src/commands/return.js
- packages/build/src/commands/run_command.js
- packages/build/src/commands/run_commands.js
- packages/build/src/core/main.js
- packages/build/src/plugins/child/run.js
Part of #1193.
This PR propagates any mutation on `netlifyConfig` to: 
- The next handlers of the same plugin
- The next plugins
- The return value of `@netlify/build` so it can be used by the `netlify build` and `netlify deploy --build` CLI commands
This cannot be tested yet (except for ensuring the current tests are still passing) since all `netlifyConfig` properties are currently read-only.
> feat: pass mutated `netlifyConfig` everywhere

- CONTRIBUTING.md
With https://github.com/netlify/js-client/releases/tag/v7.0.0, `zip-it-and-ship-it` is no longer a dependency of `js-client`. 🎉
> chore: update package dependency graph in README

- packages/build/src/commands/core_command.js
- packages/build/src/commands/run_command.js
- packages/build/src/commands/run_commands.js
- packages/build/src/core/feature_flags.js
- packages/build/src/core/main.js
- packages/build/src/plugins_core/functions/index.js
This PR enables the zip-it-and-ship-it configuration properties for the experimental handler changes introduced in https://github.com/netlify/zip-it-and-ship-it/pull/474. These properties will be enabled when a `NETLIFY_EXPERIMENTAL_FUNCTION_HANDLER_V2` environment variable is set to `true`. We may be replacing this with a LD feature flag in a subsequent PR.
As part of this work, the `featureFlags` object is being passed down the chain so that it reaches core commands.
> feat: add support for experimental ZISI v2 handler

- packages/build/src/plugins_core/functions/index.js
#2895 introduced support for zip-it-and-ship-it's experimental new handler format, but the `basePath` property is being incorrectly supplied as part of the functions configuration API (i.e. the `config` property), where in reality it's a top-level property accepted by `zipFunction` and `zipFunctions`.
This PR fixes that.
> fix: correct usage of ZISI's basePath property

- packages/config/src/files.js
- packages/config/src/log/messages.js
Part of both #1193 and #2075
This refactors the logic related to the warning message printed in repositories with a `base` directory but no `publish` directory. This does not change behavior. This refactoring is needed due to some upcoming changes.
> fix: refactor warning message related to monorepo `publish` default value

- packages/config/src/base.js
- packages/config/src/build_dir.js
- packages/config/src/files.js
- packages/config/src/main.js
Part of #1193.
This refactors some logic related to the `base` directory. This does not change any behavior.
This is needed for an upcoming PR related to `netlifyConfig.redirects`.
> feat: refactor some logic related to the `base` directory

- packages/build/src/plugins/node_version.js
- packages/build/src/plugins/resolve.js
The Node.js warning message logic uses `expectedVersion`. However, that variable is set later in the code logic. This fixes it.
> fix: do not print warning messages for plugins from the directory

- package-lock.json
- packages/build/package.json
- packages/functions-utils/package.json
Pin version of `zip-it-and-ship-it` to version 4.4.2, rolling back support for dynamic imports in esbuild.
> fix: pin zip-it-and-ship-it to version 4.4.2

- packages/build/src/plugins/child/mutations.js
- packages/build/src/plugins/child/run.js
Part of https://github.com/netlify/build/issues/3051
This adds a `configMutations` internal variable which keeps track of all `netlifyConfig.*` mutations.
> feat: add `configMutations` internal variable

- packages/build/src/core/config.js
Part of #1193.
When `netlifyConfig` is modified, we print the updated value when in debug mode. Therefore, `@netlify/config` should not print any logs, to avoid duplicated logs. Also, this will prevent config warnings from being logged several times.
Automated tests always use `buffer: true`, which is why this does not show up in test snapshots.
> feat: reduce verbose logs when changing `netlifyConfig`

- packages/build/src/plugins_core/deploy/buildbot_client.js
- packages/build/tests/plugins/tests.js
This addresses the comment from @vbrown608 in https://github.com/netlify/buildbot/issues/1445#issuecomment-874426915
This moves the deploy payload property `values.deployDir` to a top-level `deployDir` property instead.
> feat: fix the payload sent during deploy to the buildbot

- packages/build/src/commands/update_config.js
- packages/build/src/log/messages/config.js
- packages/build/src/log/messages/plugins.js
- packages/build/src/plugins/child/track.js
Part of https://github.com/netlify/build/issues/3166
This moves the logic which logs configuration mutations from the plugin child process to the parent process instead.
> feat: move configMutations logging logic

- packages/build/src/commands/update_config.js
- packages/build/src/plugins/child/track.js
Part of https://github.com/netlify/build/issues/3166
This moves the validation logic related to `configMutations` from the plugin child process to the main parent process instead.
> feat: move configMutations validation logic

- packages/build/tests/helpers/normalize.js
- packages/build/tests/status/tests.js
This PR adds snapshots normalization for prereleases.
This should fix the prerelease flow for `netlify/build` see https://github.com/netlify/build/runs/3075585703?check_suite_focus=true
> test(snapshots): normalize prerelease

- .github/workflows/release-please.yml
- .release-please-manifest.json
- CONTRIBUTING.md
- package.json
- release-please-config.json
More information [here](https://github.com/googleapis/release-please/blob/b452f2a7929f67142664883894182fa892ef0dd7/docs/manifest-releaser.md).
Instead of a PR per package, this should aggregate all releases into a single PR and publish the relevant ones in the correct order.
Fixes https://github.com/netlify/team-dev/issues/28
`release-please` manifest driven release
Keep using a release PR per package
**Checklist**
> chore: switch to manifest releaser

- .github/workflows/release-please.yml
Follow up on https://github.com/netlify/build/pull/3352
See https://github.com/netlify/local-functions-proxy/pull/46 and https://github.com/google-github-actions/release-please-action/issues/317
It seems there's a single case where `release_created` is set to `true`, but we should use `releases_created`:
https://github.com/google-github-actions/release-please-action/blob/d3d5b411d22e25052bb20e73a0ec1b156d67d944/index.js#L48
> chore: use releases_created instead of release_created

- packages/build/src/plugins/list.js
Part of https://github.com/netlify/pod-workflow/issues/157
This updates the version of `plugins.json` to match the new URL format.
> fix: update `plugins.json` version

- packages/build/src/plugins/compatibility.js
- packages/build/src/plugins/list.js
Part of https://github.com/netlify/pod-workflow/issues/260
This allows adding new properties to `compatibility`.
The fix is only partial until https://github.com/netlify/pod-workflow/issues/157 is fixed too.
> feat: allow adding new properties to `compatibility`

- packages/build/src/plugins_core/deploy/buildbot_client.js
- packages/build/src/plugins_core/deploy/index.js
- packages/build/tests/plugins/fixtures/deploy_dir_path/base/netlify.toml
- packages/build/tests/plugins/fixtures/deploy_dir_path/netlify.toml
- packages/build/tests/plugins/tests.js
Part of https://github.com/netlify/buildbot/issues/1445
This fixes the `deployDir` parameter sent to the buildbot during deploys.
At the moment, it is a path relative to the build directory. It should be relative to the repository root instead for consistency with the other file paths in the buildbot.
> fix: `deployDir` parameter sent to buildbot during deploys

- packages/build/src/commands/run_commands.js
- packages/build/src/core/main.js
- packages/build/tests/core/fixtures/plugin_mutations/manifest.yml
- packages/build/tests/core/fixtures/plugin_mutations/netlify.toml
- packages/build/tests/core/fixtures/plugin_mutations/plugin.js
- packages/build/tests/core/tests.js
- packages/config/src/mutations/update.js
- packages/config/tests/mutate/tests.js
Return `configMutations` when running `build` programmatically, so those can be used to sync the configuration before deploy.
Related to https://github.com/netlify/cli/pull/2920
Return `configMutations` when calling `netlify/build` programmatically
Duplicating the code in `netlify/config`
**Checklist**
> feat(build): return config mutations

- packages/build/src/commands/update_config.js
Part of https://github.com/netlify/build/issues/1193
This removes some dead code.
Modifying configuration property array individual element is now possible, so this validation never triggers.
> chore: remove dead code

- packages/config/src/simplify.js
`build.environment` is a plain object. However, when logged, it is converted to an array of keys, for security reasons.
This PR fixes some function which should assume that property to be either a plain object or an array. Otherwise, changing `build.environment` is not persisted to `netlify.toml` at the end of the build.
> fix: persist `build.environment` changes to `netlify.toml`

- .github/workflows/workflow.yml
This prevents Codecov outages from making our CI pipeline fail.
> chore: fix codecov GitHub action

- package-lock.json
- packages/build/package.json
- packages/build/src/commands/update_config.js
- packages/build/src/plugins/child/diff.js
- packages/config/package.json
- packages/config/src/headers.js
- packages/config/src/redirects.js
Background in https://github.com/netlify/build/pull/3407#discussion_r686733420
This removes the `fast-deep-equal` dependency.
> chore: remove `fast-deep-equal`

- package-lock.json
- packages/build/package.json
- renovate.json5
Follow up of #3321, we can now bump clean-stack to 3.x. see - https://github.com/sindresorhus/clean-stack/releases
**Checklist**
- [ x I have read the [contribution guidelines](../blob/main/CONTRIBUTING.md).
> fix(deps): bump clean-stack to 3.x

- packages/build/src/core/config.js
Follow-up on #3426 
When either modifying `netlifyConfig` in plugins or creating a `_headers`/`_redirects` in the build command or in plugins, `@netlify/config` is called again. #3426 ensured that warning messages from `@netlify/config` were logged then. However, we should not print debug logs on each `@netlify/config` call because it becomes _very_ verbose and not very useful since the resolved configuration is already printed. This PR fixes this.
> fix: avoid debug mode to be too verbose

- packages/config/src/headers.js
- packages/config/src/redirects.js
This removes the headers/redirects duplicate filtering introduced by #3424 now that it has been moved to:
- `netlify-headers-parser` (https://github.com/netlify/netlify-headers-parser/pull/8, https://github.com/netlify/build/pull/3435)
- `netlify-redirect-parser` (https://github.com/netlify/netlify-redirect-parser/pull/312, https://github.com/netlify/build/pull/3436)
> feat: remove headers/redirects duplicate filtering

- renovate.json5
Follow up from #3321. This follows a similar approach to the one we're using in - https://github.com/netlify/renovate-config/blob/351b228622126c6713272544cfa3303f572b6ba6/default.json#L28 - where instead of blocking major updates from renovate we specifically list the major versions we won't support (making it easier for our future selves to change this file).
I've went through each dependency changelog and I believe this should be correct. That being said renovate/our tests will tell us if we're wrong 👀 
The idea will be to keep track of which PRs from renovate fail and follow up with the required changes.
**Checklist**
> chore(renovate): move/remove dependency update locks on renovate's config

- packages/build/src/plugins/node_version.js
Clean up from #3321. Use the `engines.node` entry for the plugin node version support - https://github.com/netlify/build/blob/main/packages/build/package.json#L127 - instead of an hardcoded env var.
**Checklist**
> fix: rely on `package.engines.node` for plugin version support instead of a hardcoded var

- packages/build/src/utils/resolve.js
Follow up from #3321. Removing a check around the `require.resolve` usage.
**Checklist**
> fix(utils): remove condition around `require.resolve` invocation

- packages/config/src/headers.js
- packages/config/src/redirects.js
This removes some dead code since those arguments are assigned a default value by the underlying libraries.
https://github.com/netlify/netlify-headers-parser/blob/3b16ec1c8a186f876a5ac0ab25201275185fbde6/src/all.js#L9
https://github.com/netlify/netlify-redirect-parser/blob/dff2e0f28191d869fd774a5f37155ebc9e3bafe8/src/all.js#L9
> chore: remove some dead code

- package-lock.json
- packages/cache-utils/package.json
- packages/cache-utils/src/fs.js
- packages/cache-utils/tests/has.js
- packages/cache-utils/tests/helpers/main.js
- renovate.json5
This PR is a consequence of #3487. After chatting with @ehmicky seems like we've been misusing the `ignoreJunk` property on `globby` (which doesn't exist) as a way to reproduce part of the logic from `cpy`, where junk files are disregarded. This PR attempts to fix that logic and add test cases to validate that we don't store nor list junk files and empty dirs as saved.
**Checklist**
> fix(cache-utils): don't cache junk files nor list them as cached

- packages/build/tests/helpers/temp.js
- packages/build/tests/plugins/tests.js
This is a small improvement of the integration test for the `--functionsDistDir` flag.
The current test only check that the flag can be passed and is being logged.
This adds:
- Ensuring the directory is created
- Ensuring the directory is used for bundling
> chore: improve `functionsDistDir` test

- package.json
`release-please` is updating `.release-please-manifest.json` in a way that's incompatible with Prettier. This ends up breaking `npm run format` in CI. This PR fixes it.
> chore: do not prettify `.release-please-manifest.json`

- packages/git-utils/src/commits.js
Fixes https://github.com/netlify/build/issues/3622
`utils.git` retrieves all previous commits and returns information about them as an array of objects. It does this by using `git log --pretty` and parsing its output. 
The current implementation is quite naive and does not properly handle unescaped characters. This PR fixes this.
Please note `utils.git`'s code is only executed when a site uses a plugin that uses `utils.git`, thanks to [some lazy loading code](https://github.com/netlify/build/blob/main/packages/build/src/plugins/child/lazy.js) we have. This should dramatically reduce the risk associated with this PR, considering almost no plugins uses `utils.git`.
> fix: `utils.git` crashes when commit messages or authors have uncommon characters

- packages/build/tests/core/tests.js
Some tests are failing due to some VSCode extensions not supporting Node.js 8. This PR fixes this.
> chore: fix some test to use a more recent Node.js version

- .github/workflows/workflow.yml
- package.json
Addressing the Node 10 CI problems, the fact that we're relying on an `npm install` means our dependencies won't be consistent.
> fix(ci): node 10 npm setup process

- .github/workflows/workflow.yml
- packages/build/src/core/feature_flags.js
- packages/build/src/plugins_core/functions/index.js
With https://github.com/netlify/zip-it-and-ship-it/pull/603, we want the value of the `processDynamicNodeImports` config property to be `true`. As it stands, the value will start to be `false` once we remove the `zisiEsbuildDynamicImports` LaunchDarkly flag.
This PR stops listening to the flag entirely and stops passing a `processDynamicNodeImports` configuration property to zip-it-and-ship-it.
**Checklist**
> fix: remove zisiEsbuildDynamicImports feature flag

- .github/workflows/workflow.yml
Fixes https://github.com/netlify/build/issues/3655
This adds some CI tests that do not pin dependencies versions.
Note: once merged, I will update the repository branch protection settings to match the new GitHub actions matrix. This is why some CI tests appear to be stalled in this PR.
> chore: add CI tests with unpinned dependencies versions

- packages/build/src/plugins_core/functions/error.js
When a function references a Node module that cannot be found in the project, we process that error and attempt to provide a more useful message to the user. As part of this logic, we check for `functionsSrc` without asserting whether it's defined, which can happen when using the internal functions directory.
This PR addresses that.
Closes https://github.com/netlify/build/issues/3533.
**Checklist**
> fix: check for functionsSrc in "module not found" error

- packages/build/src/plugins/node_version.js
- packages/build/src/plugins/resolve.js
Somewhat part of https://github.com/netlify/build/issues/3651
At the moment, plugins installed in the UI or `netlify.toml` (but not in `package.json`) usually use the same Node.js version as `@netlify/build`. In buildbot, this is `12.18.0`. In local or programmatic builds, this is the machine/system's Node.js version.
For local or programmatic builds, there is an exception: when the `--node-path` flag is passed, it is used instead. However, this is rather unnecessary considering the `--node-path` flag is not currently used in local builds.
Therefore, this PR makes all plugins (except local or installed in `package.json`) always use the same Node.js version as `@netlify/build`. This is in line with our overall goal towards simplifying the Node.js version run by plugins and fix native …
> fix: simplify plugin's Node.js version in local builds

- packages/build/test-d/config/functions.ts
- packages/build/types/config/functions.d.ts
- packages/build/types/options/netlify_plugin_build_util.d.ts
Corrects the types for `netlifyConfig.functions` and `utils.failBuild` etc. 
`directory` is not included in the functions config, and `included_files` applies to all bundlers. `nft` is another valid bundler name.
The `failBuild` etc functions throw, so should return `never`
> fix: updates to plugin options types

- packages/build/test-d/config/inputs.ts
- packages/build/types/config/inputs.d.ts
- packages/build/types/netlify_event_handler.d.ts
- packages/build/types/netlify_plugin_options.d.ts
Fixes https://github.com/netlify/build/issues/3838
Allows users of `@netlify/build` TypeScript definitions to use `interface`s as their inputs:
```ts
interface InputsInterface {
someProp: string
}
const testSpecificInputsInterface: OnPreBuild<InputsInterface> = function ({ inputs }) {
expectType<string>(inputs.someProp)
expectError(inputs.otherTestVar)
}
```
and not just `type`s - which already work today due to them having implicit index signatures.
This is preferable since `interface`s are more prevalent than `type`s, and are the [suggested go-to](https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections) over `type`s - but more importantly - `interface`s are the go-to for the community at large, so there's no reason not to let people use it, let …
> fix: allow `interface`s to be used as Plugins generics inputs

- packages/build/src/plugins_core/functions/feature_flags.js
- packages/build/tests/core/tests.js
Set the `nftTranspile` zip-it-and-ship-it flag when the `buildbot_nft_transpile_esm` LaunchDarkly flag is set.
> feat: add `buildbot_nft_transpile_esm` feature flag

- packages/build/package.json
- packages/build/src/core/bin.js
- packages/build/src/core/main.js
- packages/build/src/plugins/child/main.js
- packages/build/src/utils/polyfills.js
- packages/cache-utils/package.json
- packages/cache-utils/src/main.js
- packages/cache-utils/src/utils/polyfills.js
- packages/config/package.json
- packages/config/src/bin/main.js
- packages/config/src/main.js
- packages/config/src/utils/polyfills.js
Part of https://github.com/netlify/build/issues/3741
Now that Node.js 10 support has been dropped, we can remove the `array.flat()` polyfill (`array-flat-polyfill`).
---
> fix: remove `array-flat-polyfill`

- packages/build/test-d/config/netlify_config.ts
- packages/build/types/config/netlify_config.d.ts
Fixes the types for redirect conditions. The values are capitalized, and `Cookie` was missing.
---
> fix: correct redirect conditions type

- .eslintrc.js
- packages/build/src/core/feature_flags.js
- packages/build/src/plugins_core/functions/feature_flags.js
- packages/build/tests/core/tests.js
- packages/build/tests/telemetry/tests.js
This PR is divided into two parts. Firstly, we pass a `parseISC` feature flag to zip-it-and-ship-it when the `zisi_parse_isc` LaunchDarkly flag is defined. This is the usual process of adding a new feature flag, because there is some translation happening between LaunchDarkly flags and zip-it-and-ship-it flags.
This process is getting a bit cumbersome though, as @ehmicky rightly pointed out a while ago. For this reason, this PR also starts passing all feature flags to zip-it-and-ship-it.
This means we'll need to start adopting a new convention for feature flag naming in zip-it-and-ship-it (i.e. using snake case 🐍  instead of camel case 🐫 ), and probably using a zip-it-and-ship-it prefix (i.e. `zisi_some_flag` as opposed to `buildbot_some_flag`).
We'll keep the existing flags as they are …
> feat: pass additional feature flags to zip-it-and-ship-it

- package.json
- packages/build/src/plugins/child/utils.js
Plugin utilities are currently loaded lazily. 
However, this has created some bugs in the past. More importantly, this does not work with pure ES modules. This is because `import()` is async while `require()` is not. Utilities are loaded on behalf of plugin authors which makes using async code difficult.
This PR switches to loading plugin `utils` like any other regular dependency, which solves those problems.
---
> fix: load plugin utilities directly

- .eslintrc.js
- package.json
- packages/build/src/plugins/child/run.js
- packages/build/src/plugins/child/utils.js
- packages/run-utils/package.json
- packages/run-utils/src/main.js
- packages/run-utils/tests/fixtures/run.js
- packages/run-utils/tests/main.mjs
This switches `run-utils` from CommonJS to pure ES modules.
---
> chore!: use pure ES modules with `run-utils`

- .eslintrc.js
- packages/build/src/plugins/child/utils.js
- packages/git-utils/package.json
- packages/git-utils/src/commits.js
- packages/git-utils/src/diff.js
- packages/git-utils/src/exec.js
- packages/git-utils/src/main.js
- packages/git-utils/src/match.js
- packages/git-utils/src/refs.js
- packages/git-utils/src/stats.js
- packages/git-utils/tests/main.mjs
This switches `git-utils` from CommonJS to pure ES modules.
---
> chore!: use pure ES modules with `git-utils`

- packages/build/src/core/constants.js
- packages/build/src/error/monitor/start.js
- packages/build/src/log/messages/core.js
- packages/build/src/log/old_version.js
- packages/build/src/plugins/compatibility.js
- packages/build/src/plugins/expected_version.js
- packages/build/src/plugins/node_version.js
- packages/build/src/plugins/options.js
- packages/build/src/telemetry/main.js
- packages/build/src/utils/json.js
- packages/build/tests/core/tests.js
- packages/build/tests/edge_handlers/tests.js
JSON imports are not available yet with pure ES modules without using experimental flags. As part of the ES modules migration, this PR refactors them so they are compatible. 
---
> fix: use ESM-compatible JSON imports

- packages/config/src/api/client.js
- packages/config/src/headers.js
- packages/config/src/main.js
- packages/config/src/redirects.js
Now that `@netlify/config` uses ES modules, we can change some dynamic imports into static ones.
---
> fix: use static imports with `@netlify/config`

- packages/build/src/core/feature_flags.js
- packages/build/src/plugins_core/functions/index.js
- packages/build/tests/core/tests.js
Removes the `buildbot_scheduled_functions` feature flag.
> feat: remove `buildbot_scheduled_functions` feature flag

- .github/workflows/release-please.yml
This PR reverts https://github.com/netlify/build/pull/3994 which inadvertently updated the release please action from v2 to v3.
v3 has some breaking changes to `manifest` releaser (which we are using in this monorepo), so we'll need to update manually.
> chore(ci-release): use v2 of release please action

- packages/build/src/plugins_core/functions/index.js
- packages/build/tests/core/tests.js
Passes the `zipGo` configuration option to zip-it-and-ship-it (added in https://github.com/netlify/zip-it-and-ship-it/pull/955) when running locally.
> feat: pass `zipGo` property to ZISI

- package-lock.json
- packages/build/package.json
- renovate.json5
Part of https://github.com/netlify/build/issues/4134
`ts-node@10.5.0` is making some of our tests fail. This PR pins its version until we fix the underlying bug.
---
> fix: pin `ts-node` version

- packages/build/tests/helpers/tcp_server.js
- packages/build/tests/log/fixtures/truncate_headers/manifest.yml
- packages/build/tests/log/fixtures/truncate_headers/netlify.toml
- packages/build/tests/log/fixtures/truncate_headers/plugin.js
- packages/build/tests/log/fixtures/truncate_redirects/manifest.yml
- packages/build/tests/log/fixtures/truncate_redirects/netlify.toml
- packages/build/tests/log/fixtures/truncate_redirects/plugin.js
- packages/build/tests/log/tests.js
- packages/build/tests/mutate_save/fixtures/many_headers/manifest.yml
- packages/build/tests/mutate_save/fixtures/many_headers/netlify.toml
- packages/build/tests/mutate_save/fixtures/many_headers/plugin.js
- packages/build/tests/mutate_save/fixtures/many_redirects/manifest.yml
- packages/build/tests/mutate_save/fixtures/many_redirects/netlify.toml
- packages/build/tests/mutate_save/fixtures/many_redirects/plugin.js
- packages/build/tests/mutate_save/tests.js
Related to https://github.com/netlify/build/issues/4163 and Monday's incident.
This adds regression tests to ensure sites with many redirects or headers are not truncated before deploy.
This also adds some tests to ensure sites with many redirects or headers are truncated in logs (not deploys). Those tests are marked as `skip` for the moment since we have reverted truncating them in logs for the moment.
This PR only adds tests, it does not change any production logic.
---
> chore: add regression tests for sites with many redirects or headers

- packages/build/tests/log/tests.js
- packages/config/src/log/cleanup.js
Fixes https://github.com/netlify/build/issues/4163
This PR re-enables https://github.com/netlify/build/pull/4172, but without the bug.
Also, regression tests have now been added to make sure re-enabling this PR is now safe.
---
> fix: truncate headers/redirects in logs

- packages/build/src/plugins/error.js
Follow-up on https://github.com/netlify/build/pull/4227
This handles `error.name` when it is not writable.
---
> fix: non-writable `error.message` inside plugins

- packages/config/src/env/envelope.js
This PR fixes a bug introduced in #4329, which impacted any Collaborators on CLI 10.6.3 using sites that have opted in to the new environment variable experience. Collaborators aren't allowed to access a team's shared environment variables. When they ran commands like `netlify dev` or `netlify env:list`, the account-level fetch would 403 with the error swallowed. This prevented even the site-level fetch from returning, which made it look like the site had no environment variables set on the site level. 
Now, if something goes wrong (i.e. insufficient permissions) with the account-level (or even site-level) fetch, an empty object will be returned instead of throwing a user error (which ended up being swallowed and caused the command to silently fail). 
Fixes …
> fix: return an empty object rather than throwing swallowed error in envelope fetch

- packages/build/src/plugins/compatibility.js
Update compatibility logic to coerced versions to valid semver (e.g 4.17.1-runtime.7 -> 4.17.1).
---
> fix: Update semver logic

- packages/build/src/plugins/compatibility.js
- packages/build/tests/plugins_list/tests.js
Builds on top of https://github.com/netlify/build/pull/4459, changing the semver matching to use the `includePrerelease` option. Also adds a test.
> fix: improve prerelease matching in plugin list

- .gitignore
- package-lock.json
- packages/build/package.json
- packages/build/src/plugins_core/edge_functions/index.js
- packages/build/src/plugins_core/edge_functions/lib/internal_manifest.js
- packages/build/tests/edge_functions/fixtures/functions_internal/.netlify/edge-functions/function-1.ts
- packages/build/tests/edge_functions/fixtures/functions_internal/.netlify/edge-functions/manifest.json
- packages/build/tests/edge_functions/fixtures/functions_internal/import-map.json
- packages/build/tests/edge_functions/fixtures/functions_internal/util.ts
- packages/build/tests/edge_functions/tests.js
This PR makes use of https://github.com/netlify/edge-bundler/pull/109 to add support for import maps in edge functions when generating ESZIP bundles.
It sets the `baseURL` property of each import map to the path of the import map file.
Supersedes https://github.com/netlify/build/pull/4507.
> feat: add support for edge functions import maps with ESZIP

- packages/build-info/test/__snapshots__/bin.test.ts.snap
- packages/build-info/test/bin.test.ts
- packages/build-info/vitest.config.ts
Fixes a test that timed out due to ts-node loader taking longer to compile on ci.
Tried to use `ts-node-esm` binary directly same result.
The only significant improvement was to run directly the compiled code.
Big downside – you need to run build first.
---
> test: fix tests that timeouts due to ts-node

- package-lock.json
- packages/build-info/package.json
- packages/build/package.json
- packages/config/package.json
buildbot has an older version of yargs in its package-lock. Older versions do not play nice with ESM and produce this error:
https://github.com/yargs/yargs/pull/2151
---
> fix: enforce yargs version 17.6.0 as prior version do not support ESM

- package-lock.json
- packages/build-info/package.json
Pins the version of `framework-info` to 9.4.0
There's now a dependency on logic that exists within this version in `buildbot` and needs to be the new minimum version.
As a result of this not being the correct version, the following is what is being output in build logs for version detection:
> fix: pin framework-info package to 9.4.0

- .circleci/config.yml
See https://github.com/netlify/build/commit/3914825b496f287e5b8ebe0ece819dc903134518#r90127545 and https://netlify.slack.com/archives/C02T8ASK2E9/p1668618894172729?thread_ts=1668604366.231059&cid=C02T8ASK2E9. The lockfile update job in CircleCI needs to take place as its own workflow since it's separate from the overall `release-please` workflow.
---
> chore(ci): make the update lockfile step for releases its own workflow

- packages/build/src/plugins_core/edge_functions/index.js
- packages/build/tests/edge_functions/tests.js
When bundling edge functions, we upload the contents of the `.netlify/edge-functions-dist` directory. For CI builds, this directory will be created fresh each time, but for local deploys it may actually contain files left over from a previous build. In those situations, we might be unnecessarily uploading old bundles.
This PR wipes that directory before we start the bundling process.
> fix: clear edge functions dist directory before build

- packages/build-info/src/detect-build-system.ts
- packages/build-info/src/get-build-info.ts
- packages/build-info/tests/detect-build-systems.test.ts
- packages/build-info/tests/get-build-info.test.ts
Removes `detectBuildSystems`  from `listFrameworks` `try...catch` block so that it executes even when `listFrameworks` errors out.
---
> fix: separate detectBuildsystems and listFrameworks

- .github/workflows/pre-release.yml
- .github/workflows/workflow.yml
Also changes the codecov label for nodejs to be "<node-major-version>" (right now "14" and "18") instead of "*" and "14.16.0"
> chore: migrate from deprecated set-output command

- package-lock.json
- packages/build/package.json
- packages/build/src/core/main.ts
- packages/build/src/error/report.ts
- packages/build/src/report/statsd.ts
- packages/build/src/time/report.ts
- packages/build/tests/error_reporting/tests.js
- packages/build/tests/time/tests.js
This replaces `statsd-client` with the recommended replacement `hot-shots` ([link](https://github.com/brightcove/hot-shots)). I tried to do the exact same thing as before, the inline comments should describe what the exact logic is when and how to send metrics.
This is a prerequisite for #4798
> fix: replace statsd-client with hot-shots

- packages/build/src/plugins_core/functions/index.ts
- packages/build/tests/time/fixtures/functions_nft/functions/function_one.js
- packages/build/tests/time/fixtures/functions_nft/functions/function_two.js
- packages/build/tests/time/fixtures/functions_nft/netlify.toml
- packages/build/tests/time/tests.js
In order to get more insights into which bundlers are actually used in builds, it would be good to have all bundlers in the metrics.
Currently, we only add  `bundler:esbuild` or `bundler:zisi` to the metric. This PR ensures that we send also `bundler:nft`.
The detection of the bundler is now based on the return value of `zip-it-and-ship-it` and not on the config and because of this it might happen that one build has multiple functions with different bundlers and we now send all bundlers one build uses. 
So in the metric UI this is shown as follows when doing the default grouping: 
but the indexing is still only for three values:
> feat: send all bundlers to metric

- packages/framework-info/src/frameworks/solid-start.json
The default port for Solid Start has been updated to 5173, the new default port for vite
Fixes #4844
This was required because running `ntl dev` with no netlify.toml caused Solid Start's dev server running in the Netlify CLI to hang because it was waiting on port 3000 previously.
The steps to replicate the issue are in #4844 as well as setting it to 5173, showing it working.
---
> fix: update Solid Start default port

- packages/build/src/plugins_core/functions/zisi.js
- packages/build/tests/core/tests.js
I actually did not pass internalSrcFolder to prefilling the generator field did not work :p 
---
> fix: pass internalSrcFolder to zisi

- packages/build-info/src/file-system.test.ts
- packages/build-info/src/file-system.ts
Fixes a bug when joining an empty string with a value in the platform-independent join functionality like `join('', 'package.json')` resulted in `/package.json` instead of `package.json`.
---
> fix(build-info): fixes a bug in the platform independent join function

- packages/build-info/src/build-systems/turbo.ts
- packages/build-info/src/frameworks/next.test.ts
- packages/build-info/src/settings/get-build-settings.test.ts
Fixes https://github.com/netlify/build/issues/5040.
According to https://turbo.build/repo/docs/reference/command-line-reference/run#--scope, `--filter` is the direct replacement for `--scope`.
---
> fix: use turbo --filter instead of deprecated --scope

- packages/config/src/api/site_info.js
- packages/config/src/main.js
Related to: https://github.com/netlify/pod-dev-foundations/issues/519 , https://github.com/netlify/cli/pull/5792
Adds the `siteFeatureFlagPrefix` to be sent through to the api with `feature_flags`, so that the API returns feature_flags in the `getSite` call.
---
> feat: pass through siteFeatureFlagPrefix to API

- packages/build-info/src/file-system.ts
This is needed as it is not supported in old safari versions and therefore breaking the react-ui. https://caniuse.com/js-regexp-lookbehind
This is needed as it caused an incident in the UI: https://github.com/netlify/netlify-react-ui/pull/17576
Fixes https://github.com/netlify/netlify-react-ui/issues/17640
the negative look behinds inside the `yaml` dependency should not be a problem as they are wrapped in a try-catch:
As `@netlify/build-info` is used inside the react-ui, we need to support old safari versions, and therefore we cannot use a negative look behind.
---
we can discuss the changes and get feedback from everyone that should be involved. If you\`re fixing …
> fix: remove RegEx negative lookbehind in file system

- package-lock.json
- packages/build/package.json
- packages/build/src/core/build.ts
- packages/build/src/core/normalize_flags.ts
- packages/build/src/log/messages/config.js
- packages/build/src/tracing/main.ts
Related with - https://github.com/netlify/buildbot/issues/2689. This addresses a couple of issues I've seen running this in production. I've left comments on the most relevant changes but the main problems I've spotted were noisy logs and the fact that the port wasn't being correctly set.
---
> fix(tracing): handle buildbot tracing integration problems

- package-lock.json
- packages/build-info/package.json
Version 8 only supports Node.js 16 and up.
> fix: downgrade dot-prop to support Node.js 14

- packages/build/src/plugins_core/secrets_scanning/utils.ts
We always want to ignore .git folders and the previous attempt only ignored them if the omit paths env var was also passed.
---
> fix: omit the git path even if no other omit paths provided

- packages/build/src/steps/run_core_steps.ts
Part of https://github.com/netlify/pod-dev-foundations/issues/574, and follow-up to https://github.com/netlify/build/pull/5221.
I wanted to add a unit test, but the only log we could test for is printed to `stderr` by edge-bundler. We were able to test on that via `runWithBinary` in https://github.com/netlify/build/pull/5221, but this doesn't work for `run_core_steps`. Tested it manually, though, which worked!
> fix: forward edgeFunctionsBootstrapURL via run_core_steps

- packages/build/src/log/messages/config.js
As Eduardo noted in https://netlify.slack.com/archives/C05556LEX28/p1691754020445069, we should hide this internal field from logs.
> fix: hide edgeFunctionsBootstrapURL

- packages/build/src/install/main.js
- packages/build/src/install/missing.js
- packages/build/src/plugins/resolve.js
Related netlify/pillar-support#699
---
Add _several_ excessive gates to prevent `addExact` being called when no integrations are supplied. This is seemingly causing a few build issues, may be npm version related
> fix: prevent addExact running when no integrations supplied

- packages/build/types/config/functions.d.ts
See https://github.com/netlify/next-runtime/pull/2302#discussion_r1335753300 - we're missing the `deno_import_map` field in our types for `functions`.
---
> fix: document deno_import_map in function types

- package-lock.json
- packages/build/package.json
- packages/build/src/log/logger.ts
- packages/build/src/plugins_core/edge_functions/index.ts
Providing the user-facing logger will fix behaviour where we're `--json` is passed to `netlify build` and we're destroying the JSON by `console.log`-ing from within edge-bundler.
> fix: update edge-bundler and provide user-facing logger

- packages/build/src/core/main.ts
- packages/build/src/tracing/main.ts
Fixes COM-45. This is the quickest way for us to have framework data in our traces.
---
> fix(tracing): add `framework` data

- packages/build/src/error/type.js
- packages/build/tests/secrets_scanning/tests.js
Secret detection should produce an user error n ot a system one
---
> fix(secret-scanning): secret detection should produce an user error

- packages/build/src/steps/error.js
- packages/build/src/tracing/main.ts
- packages/build/tests/tracing/tests.js
Fixes https://linear.app/netlify/issue/COM-91/leverage-error-types-in-netlifybuild
> feat: leverage errors types for tracing

- packages/build-info/src/frameworks/angular.test.ts
- packages/build-info/src/frameworks/angular.ts
With Angular v17, the publish directory changes based on contents of `angular.json`. It's hard to know this from build-info, but thankfully the build plugin deals with all of that! This PR updates the publish directory to `""`, which gives precedence to the value that's defined by the build plugin.
> fix: for angular v17, detect publish directory from `angular.json`

- packages/build/src/error/types.ts
- packages/build/src/tracing/main.ts
- packages/build/tests/error/tests.js
- packages/build/tests/tracing/tests.js
Fix for - COM-129 - https://linear.app/netlify/issue/COM-129/expose-location-information-for-errors-in-netlifybuild
This adds further errorInfo data and adequately namespaces our attributes added to the execption events.
---
> fix(tracing): namespace attributes in build error events and add further data

- packages/build/src/core/build.ts
- packages/build/src/plugins/child/run.js
- packages/build/src/plugins/child/systemLog.js
- packages/build/src/plugins/spawn.ts
- packages/build/src/steps/plugin.js
- packages/build/tests/plugins/fixtures/feature_flags/plugin.js
- packages/build/tests/plugins/fixtures/feature_flags_untrusted/plugin.js
- packages/build/tests/plugins/tests.js
- packages/build/types/netlify_plugin_options.d.ts
System logs are super useful for our internal observability. Giving system logs to (trusted) build plugins isn't straight-forward since plugins are run inside a child process. This PR is an attempt at bridging this, by sharing the system log file descriptor with the child process. This means build plugins will be able to write to system logs like this:
```js
import { appendFileSync } from  "fs"
export const onBuild = function () {
// ...
appendFileSync("/dev/fd/4", "next.js customer using ISC, SSR and XYZ")
// ...
}
```
`/dev/fd/4` is a bit of a magic name - but it works.
There's still some tests failing, but I wanted to share the approach sooner than later, and get your feedback.
> feat: supply system log to trusted plugins via FD

- packages/build/src/core/flags.js
- packages/build/src/core/normalize_flags.ts
- packages/build/src/core/types.ts
- packages/build/src/plugins/spawn.ts
- packages/build/src/tracing/main.ts
- packages/build/tests/tracing/tests.js
Related with COM-110 - https://linear.app/netlify/issue/COM-110/make-opentelemetry-an-optional-dependency-in-build - and a follow up to #5401. This adds support for build to skip its internal tracing initialisation if we detect the preloading had executed.
I've tested this out locally via:
```
node --import ./packages/opentelemetry-sdk-setup/lib/bin.js ./packages/build/lib/core/bin.js --debug --tracing.debug=true --tracing.preloadingEnabled=true --tracing.sampleRate=1 --tracing.apiKey=<some-api-key>  --tracing.httpProtocol=https --tracing.host=api.honeycomb.io --tracing.port=443 --tracing.baggageFilePath=$(pwd)/baggage-mock  ../../github/www-and-blog/
```
The baggage file:
```
somefield=value,foo=bar
```
The resulting trace:
- …
> fix(build): add support for ntl otel sdk setup on preloading

- packages/build/src/error/parse/serialize_status.ts
- packages/build/src/error/types.ts
- packages/build/src/plugins/spawn.ts
- packages/build/src/steps/error.ts
- packages/build/src/steps/plugin.js
- packages/build/tests/error/fixtures/trusted_plugin/netlify.toml
- packages/build/tests/error/fixtures/trusted_plugin/node_modules/@netlify/netlify-plugin-test/index.js
- packages/build/tests/error/fixtures/trusted_plugin/node_modules/@netlify/netlify-plugin-test/manifest.yml
- packages/build/tests/error/fixtures/trusted_plugin/node_modules/@netlify/netlify-plugin-test/package.json
- packages/build/tests/error/fixtures/trusted_plugin/package.json
- packages/build/tests/error/fixtures/trusted_plugin_uncaught/netlify.toml
- packages/build/tests/error/fixtures/trusted_plugin_uncaught/node_modules/@netlify/netlify-plugin-test/index.js
- packages/build/tests/error/fixtures/trusted_plugin_uncaught/node_modules/@netlify/netlify-plugin-test/manifest.yml
- packages/build/tests/error/fixtures/trusted_plugin_uncaught/node_modules/@netlify/netlify-plugin-test/package.json
- packages/build/tests/error/fixtures/trusted_plugin_uncaught/package.json
- packages/build/tests/error/tests.js
Fixes COM-187 - https://linear.app/netlify/issue/COM-187/classify-internal-plugin-errors-for-trusted-netlify-plugins-as-system. Classify unhandled trusted plugin failures as system errors.
---
> fix(build): add trusted plugin error type

- packages/build/src/error/types.ts
- packages/build/tests/error/tests.js
Small quick win, adding plugin version to the error traces we collect from plugin executions.
---
> fix(build): add plugin version to tracing errors

- packages/build-info/src/frameworks/framework.ts
- packages/build-info/src/frameworks/nuxt.test.ts
- packages/build-info/src/frameworks/nuxt.ts
Part of https://linear.app/netlify/issue/COM-184/nuxt-netlify-dev-doesnt-work. Adds a boolean to show that Nuxt needs its `dist` directory cleared, before starting local dev.
See https://github.com/netlify/cli/pull/6242#discussion_r1413924944 for more.
---
> fix(nuxt): clear dist directory before local dev

- packages/build-info/src/frameworks/nuxt.test.ts
- packages/build-info/src/settings/get-build-settings.ts
Follow-up to https://github.com/netlify/build/pull/5430. The way we interact with build-info in the CLI is via getSettings, so we should make that new property available on `Settings`!
> fix: add clearPublishDirectory to getSettings

- packages/build/src/plugins/expected_version.js
- packages/build/tests/plugins/fixtures/ui_auto_install/.netlify/plugins/node_modules/netlify-plugin-test/index.js
- packages/build/tests/plugins/fixtures/ui_auto_install/.netlify/plugins/node_modules/netlify-plugin-test/manifest.yml
- packages/build/tests/plugins/fixtures/ui_auto_install/.netlify/plugins/node_modules/netlify-plugin-test/package.json
- packages/build/tests/plugins/tests.js
In https://github.com/netlify/build/pull/5451, we introduced a regression. We started selecting the wrong Node.js version for UI Plugins. This was reverted in https://github.com/netlify/build/pull/5452.
To prevent this from happening again, here's a test for the version selection.
This PR could've been marked as `chore:`, but I marked it as `fix:` to trigger release-please - https://github.com/netlify/build/pull/5452 didn't do that, but should have.
> fix: test version selection for ui plugin

- packages/build/src/plugins/compatibility.test.ts
- packages/build/src/plugins/plugin_conditions.ts
Fixes https://netlify.slack.com/archives/C05NYMPB75H/p1711630124786829
---
> fix: deal with pre-releases in plugins siteDependency constraints

- packages/build/src/core/feature_flags.ts
- packages/build/src/plugins/compatibility.test.ts
- packages/build/src/plugins/compatibility.ts
- packages/build/src/plugins/expected_version.ts
- packages/build/src/plugins/resolve.js
- packages/build/tests/plugins/tests.js
Updates the logic used to determine the plugin version that should be picked when there is no pinned version for the site. Includes a feature flag that toggles between just logging whenever there's a mismatch between the legacy and new logic and actually applying the new version.
> fix: update logic for plugin selection fallback

- packages/build/src/plugins/compatibility.test.ts
- packages/build/src/plugins/compatibility.ts
- packages/build/src/plugins/expected_version.ts
Small follow-up to #5575. We were incorrectly logging the name of the project package (if set) as the name of the plugin.
> fix: use correct plugin name in system log

- packages/build/src/core/build.ts
We are currently unable to create SLO in honeycomb that target just Next Runtime v5 to capture overall build error rates with it.
We do have individual build steps annotated with plugin name and version that is being executed, but we can't join `exec-build` span with those to extract needed information. This PR adds information about used Build Plugins to `exec-build` by adding 1 span attribute per plugin with name containing plugin name and value being its version to be able to filter `exec-build` by specific plugins (and their versions).
This will allow queries like below to be able to create actual SLO and alerting 
Related to https://linear.app/netlify/issue/FRA-367/update-build-time-metrics
Relevant slack discussion: https://netlify.slack.com/archives/C031MPNJWK1/p1712068846389239
> feat: add used build plugins and their versions to exec-build span

- packages/redirect-parser/src/normalize.js
- packages/redirect-parser/tests/fixtures/netlify_config/with_ratelimit.toml
- packages/redirect-parser/tests/netlify-config-parser.test.ts
Related to ADN-294
Need that extra info to be parsed so custom rate limits work correctly with the CLI. Sorry for the tag @eduardoboucas, but you're the closest person that has been following the project that also knows `build`.
> feat: parse custom rate limit info from redirects

- packages/zip-it-and-ship-it/src/main.ts
Tiny no-op change to check if after #5644 we're still able to release correctly.
> fix: no-op change to test release process after merging ZISI into monorepo

- packages/zip-it-and-ship-it/tests/v2api.test.ts
Migrated over from https://github.com/netlify/zip-it-and-ship-it/pull/1743 after we've merged the repositories.
https://github.com/netlify/serverless-functions-api/pull/231 adds a side-effect that needs to be executed before user code. That's already the case today, but to ensure it stays that way, this PR adds a test for that.
> chore: test import order

- packages/build/src/plugins_core/deploy/index.js
Small follow-up to #5643. In the deploy step, buildbot emits some logs of its own, so we need to flush the header before that to preserve the correct order of things.
> fix: flush output from "Deploy site" step

- packages/config/src/log/logger.js
Follow-up to #5643. The duplicated logger in `@netlify/config` needs to be updated to the new format of holding either an object with `stdout` and `stderr` arrays and an `outputFlusher` (buffered) or an object with an `outputFlusher` (streamed).
> fix: update config logger

- packages/build/src/log/logger.ts
The optional chaining operator is causing some build errors in old versions of Node.js. Replacing it with an explicit assertion.
> fix: remove optional chaining operator

- package-lock.json
- packages/build/package.json
- packages/build/src/plugins/compatibility.ts
- packages/build/src/plugins/expected_version.ts
- packages/build/src/plugins/manifest/main.ts
- packages/build/src/plugins/options.ts
- packages/build/src/plugins/plugin_conditions.ts
- packages/build/src/utils/json.ts
- packages/build/src/utils/package.ts
- packages/framework-info/package.json
- packages/framework-info/src/context.ts
- packages/framework-info/src/core.ts
- packages/framework-info/src/package.ts
- packages/opentelemetry-sdk-setup/package.json
- packages/opentelemetry-sdk-setup/src/sdk-setup.ts
- packages/opentelemetry-sdk-setup/src/util.ts
> fix: revert update of `read-pkg-up`

- packages/build/src/log/logger.ts
- packages/build/src/steps/core_step.ts
- packages/build/src/steps/plugin.js
If `outputFlusher` isn't set, stop changing the `logs` reference that is sent to the logic that calls plugins.
This shouldn't make a difference, but trying to be super defensive about this code path.
> fix: stop changing `logs` if flusher is not set

- packages/build/src/log/output_flusher.ts
- packages/build/src/log/stream.js
- packages/build/src/log/stream.ts
- packages/build/src/plugins/spawn.ts
- packages/build/src/steps/plugin.js
Follow-up to #5643 with a couple of small changes:
- https://github.com/netlify/build/pull/5677/commits/b4f9a10e856ee28865b34a89d0ef6dc7d1da5f4b: passes the output flusher to the `callChild` method, and ensures that we call `unpipe` on the streams that have been wrapped with the transform
- https://github.com/netlify/build/pull/5677/commits/6586800f3426b1b364661b153fdbedd339e2093c: refactored the `stream` to use TypeScript.
> feat: pass output flusher to `callChild`

- packages/config/src/api/site_info.ts
- packages/config/src/error.ts
- packages/config/src/main.ts
- packages/config/tests/api/tests.js
This should help with stuff not breaking
---
> fix: revert b8899e06a31f5615ef41d8a4ab251bcc96717837

- packages/config/src/mutations/apply.js
Leftover from https://github.com/netlify/build/pull/5692.
Apparently, the `dev` needs to be in mutable props as well as it won't be present if netlify.toml doesn't have `build.publish` property.
> fix: [CRE-1203] adds `dev` to config mutable props

- packages/config/src/api/site_info.ts
- packages/config/src/main.ts
This is trying to fix this issue: https://netlify.slack.com/archives/C07686YAY13/p1718181320747959?thread_ts=1718139257.978049&cid=C07686YAY13
---
> fix: re-add siteFeatureFlagPrefix

- packages/zip-it-and-ship-it/src/runtimes/node/in_source_config/index.ts
- packages/zip-it-and-ship-it/src/runtimes/node/index.ts
- packages/zip-it-and-ship-it/tests/fixtures-esm/v2-api-included-files/netlify/functions/function.js
- packages/zip-it-and-ship-it/tests/v2api.test.ts
Follow-up to #5712. When `includedFiles` is defined in-source, it resolves the globs relative to the function file.
> fix: use correct base path for ISC `includedFiles`

- packages/zip-it-and-ship-it/src/manifest.ts
- packages/zip-it-and-ship-it/tests/v2api.test.ts
Follow-up to #5717, adding `excludedRoutes` to the functions manifest.
Part of https://linear.app/netlify/issue/COM-724/excludedpath-in-functions-v2.
> fix: add `excludedRoutes` to functions manifest

- package.json
- packages/build/src/core/build.ts
- packages/build/src/core/config.js
- packages/build/src/steps/core_step.ts
- packages/build/src/steps/plugin.js
- packages/build/src/steps/run_core_steps.ts
- packages/build/src/steps/run_step.ts
- packages/build/src/steps/run_steps.js
- packages/build/src/steps/update_config.js
Needed for: https://linear.app/netlify/issue/CT-738/cli-should-use-framework-detection-and-install-runtime-for-build-and
When a build plugin did config mutations, it did not preserve the previous configuration (cachedConfig). As it read it up freshly from the `netlify.toml`
---
> fix: preserve cached config while mutating config

- packages/zip-it-and-ship-it/src/runtimes/node/parser/exports.ts
- packages/zip-it-and-ship-it/tests/unit/runtimes/node/in_source_config.test.ts
Currently, this works in a function:
```js
export const config = {
path: "/foo"
}
```
... but this doesn't:
```js
export const config = {
"path": "/foo"
}
```
This PR fixes that.
> fix: accept string literal keys in in-source config

- packages/build-info/src/workspaces/get-workspace-packages.test.ts
- packages/build-info/src/workspaces/get-workspace-packages.ts
Fixes the issue where monorepos where not detected properly due to a undocumented feature in pnpm workspace definition.
Fixes https://linear.app/netlify/issue/FRP-774/help-investing-why-monorepo-detection-is-not-working
See https://netlify.slack.com/archives/C01TKAEBP3Q/p1720640110647669
---
> fix: relative path pattern in workspace globs

- packages/edge-bundler/node/config.ts
Deno doesn't support https specifiers or TypeScript in node_modules directories. The `@netlify/edge-bundler` package has code with https specifiers and TypeScript in it.
Take the following directory structure:
```
-my_project
- node_modules
- @netlify/edge-bundler
- package.json
- deno
- config.ts
- package.json
```
When executing `my_project/node_modules/@netlify/edge-bundler/deno/config.ts`, Deno would previously resolve the project root as `my_project/node_modules/@netlify/edge-bundler` due to the package.json in that folder. In Deno 1.45, Deno has gotten smarter though and resolves the project root to `my_project`. This change fixes a lot of previously broken code when executing entrypoints in node_modules directories, but causes an error for `@netlify/edge-bundler`.
To fix this, we …
> fix: disable config discovery when executing "Deno code" in node_modules directory

- packages/config/src/env/main.ts
- packages/config/src/main.ts
leverage the internal config inside the getEnv as well, the internal config is set through the cached config by the CLI
Needed for: https://linear.app/netlify/issue/CT-738/cli-should-use-framework-detection-and-install-runtime-for-build-and
This is needed in addition to: https://github.com/netlify/build/pull/5761
---
> fix: leverage the internal config inside the getEnv as well

- packages/cache-utils/package.json
`@netlify/cache-utils` does not ship with its own .d.ts file even though NPM says it does. I checked the module and the package.json seems to list the file, but I believe it might not be uploaded to NPM as the `files` array in `package.json` excludes that path. This PR adds the path to the file in the `files` array which should fix this.
> fix: missing type-def

- packages/config/src/api/site_info.ts
I thought after Eduardo's comment in my other PR that me renaming the PR title would fix that I used `chore` but alas it did not. Thus this pr
---
> feat: use v2 endpoint that has siteid for extensions

- packages/config/src/api/site_info.ts
- packages/config/tests/api/tests.js
Fixes FRP-1269 - https://linear.app/netlify/issue/FRP-1269/information-request-is-the-account-id-available-for-build-plugins.
By default, when running in offline/buildbot mode netlify/config doesn't issue any requests to the get site endpoint. This means that until now the resulting `@netlify/config` didn't have anything else besides the `siteId` under the `siteInfo` object. This change will make sure we also return the `account_id` in accordance with the `getSite` operation - https://open-api.netlify.com/#tag/site/operation/getSite - if `@netlify/config` has been provided with an `account-id` through cli param.
The most important outcome of this change is that it will allow plugins to access `account_id` at execution time in buildbot through the …
> feat(config): return account id from config in offline mode

- packages/zip-it-and-ship-it/src/feature_flags.ts
- packages/zip-it-and-ship-it/src/runtimes/node/utils/entry_file.ts
- packages/zip-it-and-ship-it/src/runtimes/node/utils/zip.ts
- packages/zip-it-and-ship-it/tests/v2api.test.ts
Places a file at the root of the Lambda containing the version of the bootstrap layer. Behind a feature flag.
Part of https://linear.app/netlify/issue/RUN-858/spike-on-the-mechanism-for-extracting-the-metadata-needed-within-the.
> feat: write a file with the bootstrap version

- .circleci/config.yml
Fixes https://linear.app/netlify/issue/FRP-770/lack-of-runtime-integration-tests-for-the-build-pipeline
Depends on: https://github.com/netlify/run/pull/2
This adds the netlify e2e test pipeline to the build repository using remlink to mock out the npm packages (hot-swapping) on a Pull Request. 
This deploys sites with the modified (hot-swapped dependencies) and tests against them. The tests are git cloned from the `netlify/run` repository main branch using the private CircleCI orb.
---
something that\`s on fire 🔥 (e.g. incident related), you can skip this …
> ci: add e2e testing pipeline to the reopsitory

- packages/build-info/src/frameworks/framework.ts
- packages/build-info/src/frameworks/hydrogen.test.ts
- packages/build-info/src/frameworks/hydrogen.ts
- packages/build-info/src/frameworks/remix.test.ts
- packages/build-info/src/frameworks/remix.ts
- packages/build-info/src/frameworks/vite.ts
We noticed recently that the framework detection wasn't working correctly for all Remix sites. This leads to poor DX but it also affects our reporting that informs framework usage on the platform.
So, this has gotten pretty complex 😓:
- Remix sites can either use Vite or the Remix Classic Compiler
- These use different config files, different dev and build config, but almost identical npm dependencies (plus `vite` in the Remix Vite case)
- Hydrogen (v2) uses Remix and, as of a few months ago, it supports Remix Vite in addition to the Remix Classic Compiler (it only supported this previously)
- Netlify's Remix packages were renamed in late 2023, but the Remix detection code only listed the old names
- Luckily, this still happened to work because it also listed the right config file, but …
> fix(build-info): fix detection of Remix and Hydrogen sites

- packages/build-info/src/frameworks/framework.test.ts
- packages/build-info/src/frameworks/framework.ts
- packages/build-info/src/frameworks/hydrogen.ts
- packages/build-info/src/frameworks/remix.test.ts
- packages/build-info/src/frameworks/remix.ts
- packages/build-info/src/get-framework.test.ts
- packages/build-info/src/get-framework.ts
Fixes https://linear.app/netlify/issue/FRB-1324/fix-failing-test-related-to-remix-framework-detection-in-cli
Because of the change in https://github.com/netlify/build/pull/5820 we now have scenarios where forcing framework via `netlify.toml#dev.framework` that is not honored by framework's detection, would print quite confusing error:
> Invalid framework "remix". It should be one of: analog, angular, assemble, astro, blitz, brunch, cecil, create-react-app, docpad, docusaurus, eleventy, ember, expo, gatsby, gridsome, grunt, gulp, harp, hexo, hugo, hydrogen, jekyll, metalsmith, middleman, next, nuxt, observable, parcel, phenomic, quasar, qwik, react-static, redwoodjs, remix, roots, sapper, solid-js, solid-start, stencil, svelte, svelte-kit, vite, …
> fix: honor forced framework for Remix and Hydrogen

- packages/build/src/plugins/ipc.js
- packages/build/tests/plugins/fixtures/process_send_object/manifest.yml
- packages/build/tests/plugins/fixtures/process_send_object/netlify.toml
- packages/build/tests/plugins/fixtures/process_send_object/plugin.js
- packages/build/tests/plugins/tests.js
Spawned processes might return a random data, while `ipc.js`, when filters messages, expects it to be in array format. 
When process sends non-array object, it produces the uncaught error and stops the build.
I've discovered this when started `netlify dev` with `plugin-visual-editor` on the site with astro and sanity. Plugin-visual-editor launches `stackbit dev`, which imports a `content-engine`, which calls `process.send(/* OBJECT */)` and crashes the build.
---
your code follows …
> fix: reading data from spawned process

- packages/build-info/src/runtime/erlang.test.ts
- packages/build-info/src/runtime/erlang.ts
- packages/build-info/src/runtime/index.ts
Rebar is a very common Erlang build tool (see: https://github.com/erlang/rebar3)
Using the rebar config files to detect some erlang usage in Netlify
---
> chore: add basic erlang detection via rebar

- packages/zip-it-and-ship-it/src/manifest.ts
- packages/zip-it-and-ship-it/src/runtimes/node/index.ts
- packages/zip-it-and-ship-it/src/runtimes/node/utils/zip.ts
- packages/zip-it-and-ship-it/src/utils/format_result.ts
- packages/zip-it-and-ship-it/tests/v2api.test.ts
Part of https://linear.app/netlify/issue/RUN-1060/add-the-boostrap-layer-version-to-the-proxy-log-line.
> feat: add `bootstrapVersion` field to manifest

- packages/build/tests/install/tests.js
This removes a test focus I accidentally committed in #5885.
I'll follow this up with an ESLint rule that catches focused tests. I'm htiting some `.eslintrc*`/`eslint.config.js` issues adding it, so putting this PR up while I get it working.
> test(build): remove test focus

- packages/build/src/steps/plugin.js
> feat: keep logging pipe for trusted plugins

- packages/build/src/plugins_core/pre_dev_cleanup/index.ts
We print a log line when we clean up internal directories in Netlify Dev. This information is not at all useful or actionable by users, so it's just adding noise.
This PR transforms it into a system log line, so it's only shown when the `--debug` flag is used.
> fix: turn log line into system log

- packages/build/src/plugins/spawn.ts
- packages/edge-bundler/node/server/util.ts
See for underlying problem that so far doesn't seem fixed https://github.com/nodejs/node/issues/51766 . That started showing up on our test runs when Github Actions switched to Node 22 (it was running on 20 before)
---
> fix: process kill errors on windows with node 21+

- packages/config/src/api/site_info.ts
- packages/config/src/case.ts
- packages/config/tests/api/tests.js
Cleaning up feature flag now that it's been turned on for months now :)
---
> chore: remove released feature flag for extensions/ future state

- packages/build-info/src/runtime/bun.test.ts
- packages/build-info/src/runtime/bun.ts
Fixes FRB-1355
Feature is not released yet so we can wait to merge if we'd like, but it doesn't hurt to get ahead
See: https://github.com/oven-sh/bun/issues/11863
---
> fix: detect `bun.lock` files in addition to `bun.lockb` files

- packages/zip-it-and-ship-it/src/runtimes/node/utils/node_runtime.ts
Related to FRB-1505
Adds node v22 to the allowed runtime versions
If a user is using v22 via `.nvmrc`, once this is released their runtime version will match
Also supports the future default version being bumped from v18 to v22
---
> feat: add node 22 to supported runtime versions list

- .github/workflows/workflow.yml
- packages/edge-bundler/node/bridge.ts
- The new noble image uses the latest deno version
- The removed comment is out of date, because the linked ticket mentions a fix was made in 1.46.0
- We are bumping the low end of the version because we rely on a fix for `AbortSignal` made in 1.39.0
TODO:
---
> fix: update DENO_VERSION_RANGE

- packages/functions-utils/tests/main.test.ts
This test started failing on Windows in the last day ([example](https://github.com/netlify/build/actions/runs/12319508347/job/34386720595?pr=5944)). We're not quite sure what's going on but the async import with `?one` fails.
We _think_ it's because of the bump to node 22.12.0 (we automatically pull in the latest node version in CI). The most recent successful runs were using 22.11.0. 🤷🏼
> test: rewrite test to work around Windows bug

- packages/config/docs/main.md
I need to fix whatever's doing this in my editor...
> docs: fix weird stuff my IDE did in some Markdown

- packages/build-info/src/settings/get-build-settings.test.ts
Fixes FRB-1557
The arrays from build-info can sometimes be returned in different orders, but `toEqual` compares the order of results. As a workaround, some tests were sorting the results prior to asserting on them, but one of the tests was missed causing it to be flaky.
Instead I've made the all the test assertions order agnostic, and removed sorting steps from the tests
> test: make test assertions order agnostic

- packages/js-client/src/index.ts
- packages/js-client/src/types.ts
Add type definitions for dynamic client methods by defining the `NetlifyAPI` class as an interface that inherits mapped types from `@netlify/open-api`.
Not having types is annoying, but lets try not to break things.
**Using return types from `@netlify/open-api`:**
**Support both snake_case and camelCase params:**
**Support combined path and query params:**
---
> feat(js-client): add type definitions

- packages/js-client/src/types.ts
This PR improves the developer experience by addressing issues with parameter typing in the API client:
- Methods with no parameters (e.g., `getCurrentUser`) incorrectly required passing something like `getCurrentUser(undefined)`.
- Methods where all parameters are optional (e.g., `listSites`) required passing an empty object, even though no parameters were necessary.
These issues are resolved by conditionally setting the params type to either `void` or `void | Params<{...}>`, depending on the method's parameter requirements.
- Added `AreAllOptional` type to check if all keys in a type are optional.
- Added `IsPathAndQueryOptional` type to check if all parameters for a method are optional.
- Renamed `CombinedCaseParams` to `Params` for better readability in IDEs.
- Updated params type:
- …
> fix(js-client): Update method params type to be optional when all param keys are optional

- packages/js-client/src/types.ts
All dynamic operation methods can have a second arg `opts` to pass any additional properties to `node-fetch` `RequestInit`. This change adds the type definition for the `opts` argument.
Also allow passing `undefined` for `params` argument for methods that don't accept any `params` but still might want to pass `opts`.
example:
```ts
const user = await client.getCurrentUser(undefined, {
headers: {
'X-Some-Header': 'custom value',
},
})
```
---
**A picture of a cute …
> fix(js-client): add type definitions for operation method `opts` argument

- packages/build-info/src/node/get-build-info.test.ts
Fixes FRB-1563
Some runs we return the build settings in a different order. To resolve here I've opted to sort the settings before checking the snapshot.
---
> test: sort setting before comparing to snapshot

- packages/build/src/core/feature_flags.ts
- packages/build/src/plugins_core/edge_functions/index.ts
- packages/build/src/plugins_core/functions/index.ts
- packages/build/src/plugins_core/functions/utils.js
- packages/build/tests/edge_functions/tests.js
- packages/build/tests/functions/tests.js
> fix: remove references to fully rolled out netlify_build_frameworks_api feature flag

- package-lock.json
- packages/build/package.json
- packages/build/src/plugins/resolve.js
- packages/build/tests/plugins/fixtures/monorepo/apps/pinned/package.json
- packages/build/tests/plugins/fixtures/monorepo/apps/unpinned/netlify.toml
- packages/build/tests/plugins/fixtures/monorepo/apps/unpinned/node_modules/netlify-plugin-test/index.js
- packages/build/tests/plugins/fixtures/monorepo/apps/unpinned/node_modules/netlify-plugin-test/manifest.yml
- packages/build/tests/plugins/fixtures/monorepo/apps/unpinned/node_modules/netlify-plugin-test/package.json
- packages/build/tests/plugins/fixtures/monorepo/apps/unpinned/package.json
- packages/build/tests/plugins/fixtures/monorepo/node_modules/netlify-plugin-test/index.js
- packages/build/tests/plugins/fixtures/monorepo/node_modules/netlify-plugin-test/manifest.yml
- packages/build/tests/plugins/fixtures/monorepo/node_modules/netlify-plugin-test/package.json
- packages/build/tests/plugins/fixtures/monorepo/node_modules/unpinned
- packages/build/tests/plugins/fixtures/monorepo/package.json
- packages/build/tests/plugins/tests.js
Patch the system to support multiple version of plugins (e.g. next-runtime) in a monorepo context
Bonus: Package version bump for resolve
Fixes FRB-1641
---
> fix: multiple plugin versions in a monorepo setup

- packages/build/tests/functions/tests.js
- packages/zip-it-and-ship-it/src/feature_flags.ts
- packages/zip-it-and-ship-it/src/runtimes/node/utils/zip.ts
- packages/zip-it-and-ship-it/src/zip.ts
- packages/zip-it-and-ship-it/tests/symlinked_included_files.test.ts
- packages/zip-it-and-ship-it/tests/telemetry.test.ts
- packages/zip-it-and-ship-it/tests/v2api.test.ts
We have found that locally deployed functions do not always pass a bootstrap_version to our API. To ensure this is included, we are unconditionally creating amanifest.json, which is where this value is drawn from.
This PR also removes the zisi_add_metadata_file flag, which has been switched on in production for a while.
---
> feat: remove references to removed flag and always produce manfiest

- .github/workflows/workflow.yml
- package-lock.json
- packages/testing/package.json
- packages/testing/src/fixture.ts
There are a few issues on `main` at the moment, so they all need to be fixed in a single PR.
cherry-pick of https://github.com/netlify/build/pull/6121
The full test suites run in <1m, so this isn't worth the complexity and risk, and we speculate there might be something not quite right with this setup that causes latent errors to be obscured on PRs and later revealed on `main`.
`packages/testing` is not configured in `release-please-config.json`, so release PRs don't bump monorepo packages in that package (and vice versa)
This led to really confusing test failures introduced after https://github.com/netlify/build/pull/6107 was merged to `main`.
We'll fix the problematic setup in a later PR. This just fixes the immediate test errors.
> chore: fix various CI issues

- packages/config/src/api/integrations.ts
- packages/config/src/api/site_info.ts
- packages/config/src/integrations.ts
- packages/config/src/main.ts
This ensures that we align our extension API with the right environment.
We use the netlify api host to check if we are on production or staging. This determines the extension api url.
---
> fix: use staging url for extensions on staging

- packages/build-info/src/settings/netlify-toml.ts
- packages/zip-it-and-ship-it/src/main.ts
You can see it here: https://github.com/netlify/build/blob/8dc142a491c2e9db50bffba8d5d8cc0a790bbd22/packages/config/src/functions_config.js#L57. Unfortunately this repo still has a bunch of `.js` so it wasn't caught.
Also, I noticed an unrelated copy-pasted type that I cleaned up.
> fix(types): add missing `schedule` to functions config type

- packages/config/src/api/site_info.ts
- packages/config/src/integrations.ts
- packages/config/src/main.ts
- packages/config/src/types/options.ts
- packages/config/tests/api/tests.js
This tests if the extension api is set properly for staging.
---
> test: add test for staging extension api

- package-lock.json
- packages/js-client/package.json
- packages/js-client/src/methods/response.js
- packages/js-client/src/omit.test.ts
- packages/js-client/src/omit.ts
- packages/js-client/src/operations.js
Something about this module is off. It works with some runtimes/bundlers but not others. It seems to have issues with [webpack](https://github.com/benjycui/omit.js/issues/10) and with [bun](https://github.com/netlify/build/issues/5613).
I just inlined it. It's tiny anyway.
Fixes #5613.
> fix: remove problematic `omit.js` dependency

- package-lock.json
- packages/testing/package.json
See https://github.com/netlify/build/pull/6188.
The `packages/testing` package has dev dependencies on `packages/build` and `packages/config`, but these also have (undeclared) dev dependencies on `packages/testing` 🔂.
Since our release-please configuration does not include `packages/testing` at all (there's nothing to release; it's a "local package" only), major bumps to either of its dependencies does not bump its "local" dependencies, which results in `packages/testing` no longer pulling in their local versions and instead pulls in a duplicated previous published version from the NPM registry.
This in turn results in `@netlify/config` and/or `@netlify/build` not actually testing their own source, since they use `packages/testing` to test themselves...
This is a confusing mess, and …
> chore(deps): avoid `packages/testing`'s local deps getting out of sync after major releases

- packages/build-info/src/frameworks/solid-js.ts
- packages/build-info/src/frameworks/tanstack-router.ts
- packages/build-info/src/frameworks/tanstack-start.test.ts
- packages/build-info/src/frameworks/tanstack-start.ts
https://github.com/TanStack/router/pull/3563 renamed `@tanstack/start` to `@tanstack/react-start` and https://github.com/TanStack/router/pull/3522 introduced the `@tanstack/solid-start` variant
We need to keep the old name for backwards compatibility
> fix: detect new TanStack Start package names

- packages/zip-it-and-ship-it/src/feature_flags.ts
- packages/zip-it-and-ship-it/src/runtimes/node/utils/entry_file.ts
depends on https://github.com/netlify/serverless-functions-api/pull/385
this gives us the ability to catch any errors which may arise when importing the function's code, and also allows us to prepare more within the bootstrapping phase before the functions code is executed - such as populating process.env or any bootstrapping that may require information provided by Proxy for the invocation
> feat(zip-it-and-ship-it): feature flag ability to dynamically import funcion inside request handler

- packages/zip-it-and-ship-it/src/feature_flags.ts
- packages/zip-it-and-ship-it/src/runtimes/node/utils/entry_file.ts
we need to rename the flag because of previous versions of zip-it-and-ship-it which are used in old cli installs contain a buggy version of serverless-functions-api which does not work correctly with some typescript projects. renaming the flag means only future versions of zip-it-and-ship-it will be optied into the new entrypoint, and we know that future versions of zip-it-and-ship-it are using a fixed version of serverless-functions-api
> fix: opt into new entrypoint only if using fixed version of serverless-functions-api

- packages/config/src/utils/extensions/auto-install-extensions.ts
Need to log more info to see what is going on in buildbot
---
> fix(config): add more logging for `auto_install_required_extensions` feature flag

- packages/build/src/plugins_core/secrets_scanning/secret_prefixes.ts
- packages/build/src/plugins_core/secrets_scanning/utils.ts
- packages/build/tests/utils_secretscanning/tests.js
Fixes https://linear.app/netlify/issue/WRFL-2579/false-positives-with-env-var-names-esp-with-secret
This string is commonly bundled into apps using react proptypes, let's make sure we ignore
---
> feat: safelist common string in react proptypes from secret detection

- packages/config/src/main.ts
- packages/config/src/utils/extensions/auto-install-extensions.ts
Removes check for 'accounts' because it is not available in buildbot context.
---
> fix(config): auto install required extensions in buildbot

- package-lock.json
- packages/js-client/README.md
- packages/js-client/package.json
- packages/js-client/src/types.ts
Now that we use node >18 we can drop the node-fetch polyfill from the package
Part of FRB-1833
---
> fix: remove node-fetch from js-client package

- packages/cache-utils/README.md
https://netlify.slack.com/archives/C01TKAEBP3Q/p1748030448793099
existing description seems contradicting, this hopefully removes confusion.
Change made on checking `restore` function behavior that local (`src`) dir will be deleted if cached directory exists: https://github.com/netlify/build/blob/6cb919d7254fe7eff87eb7b52417773ba63c030d/packages/cache-utils/src/main.ts#L47-L74
---
**A picture of a cute animal (not mandatory, …
> docs: update description of `@netlify/cache-utils` restore function

- package-lock.json
- packages/build-info/package.json
- packages/build/package.json
- packages/build/src/plugins_core/blobs_upload/index.ts
- packages/build/src/plugins_core/dev_blobs_upload/index.ts
- packages/cache-utils/package.json
- packages/config/package.json
- packages/edge-bundler/package.json
- packages/git-utils/package.json
- packages/headers-parser/package.json
- packages/js-client/package.json
- packages/nock-udp/package.json
- packages/opentelemetry-sdk-setup/package.json
- packages/opentelemetry-utils/package.json
- packages/redirect-parser/package.json
- packages/run-utils/package.json
- packages/testing/package.json
- Update node/types to v18
- Convert buffers into blobs before calling blobStore.set (fix a type issue)
---
> fix: upgrade @types/node to v18

- package-lock.json
- packages/js-client/package.json
- packages/js-client/src/index.test.ts
- packages/js-client/src/methods/response.js
Replace micro-api-client package with direct class references
---
> chore: remove deprecated micro-api-client

- packages/build/src/plugins_core/pre_dev_cleanup/index.ts
Remove special handling for remix and hydrogen in pre-dev-cleanup step
(see discussion in https://github.com/netlify/build/pull/6446#pullrequestreview-2914173107)
---
> fix: no frameworks special case for pre-dev-cleanup

- packages/config/src/utils/extensions/auto-install-extensions.ts
- packages/config/tests/extensions/tests.js
This replaces an old feature flag with a new one. We will keep the old feature flag but turn it off. There was a bug introduced in `netlify/config@22.2.0` and also fixed. But the netlify CLI has not been patched, and it _cannot_ be patched (see linear).
---
> fix: use auto_install_required_extensions_v2 instead of auto_install_required_extensions

- packages/build/src/core/build.ts
Flag is not rolled out, as such the related code is unused
https://app.devcycle.com/o/org_dhCAK5hN1u5tXdf9/p/shared/features/641c5a96441ea2c1b68a8f1f/manage-feature
---
> chore: remove unused code behind feature flag

- packages/build-info/package.json
When you run `npm i` on the main branch, the lockfile will be updated.
We don't want the update to keep popping up, so I'm fixing the root cause (a mismatch of versions between the lockfile and the package.json)
https://github.com/netlify/build/blob/main/package-lock.json#L4600-L4602
---
> chore: match version of @playwright/test to version in lockfile

- renovate.json
The ignore path wasn't done correctly, the correct way to ignore would have been `**/fixtures/**`
Evidence is that since the change we've had https://github.com/netlify/build/pull/6516 pop up which is making a change within the fixtures directory.
Follow-up to https://github.com/netlify/build/pull/6512
---
> chore: remove ignore paths to match renovate syntax

- package-lock.json
- packages/build-info/package.json
- packages/opentelemetry-sdk-setup/package.json
- packages/opentelemetry-utils/package.json
The `vite` dependency appears to only be used in the seemingly unused `build:logos` command, so I'm removing both
---
> chore: remove unused build:logos command and related dependency

- packages/build/src/index.ts
- packages/zip-it-and-ship-it/src/main.ts
- packages/zip-it-and-ship-it/src/paths.ts
- packages/zip-it-and-ship-it/src/zip.ts
- packages/zip-it-and-ship-it/tests/helpers/main.ts
- packages/zip-it-and-ship-it/tests/list_functions.test.ts
Updates the signature of `listFunctions` so it accepts the same object of mixed paths introduced in #6524.
🐔
> feat: accept mixed paths in `listFunctions`

- packages/edge-bundler/node/validation/manifest/__snapshots__/index.test.ts.snap
- packages/edge-bundler/node/validation/manifest/index.test.ts
- packages/edge-bundler/node/validation/manifest/schema.ts
Updates the edge functions manifest validation logic to include the new `headers` property introduced in https://github.com/netlify/build/pull/6501.
> feat: add `headers` to edge functions manifest validation

- packages/edge-bundler/node/config.test.ts
- packages/edge-bundler/node/declaration.ts
- packages/edge-bundler/node/manifest.test.ts
- packages/edge-bundler/node/validation/manifest/__snapshots__/index.test.ts.snap
- packages/edge-bundler/node/validation/manifest/index.test.ts
- packages/edge-bundler/node/validation/manifest/schema.ts
Follow-up to https://github.com/netlify/build/pull/6542. The right property name is `matcher`, not `style`.
> fix: rename edge functions manifest property

- package-lock.json
- packages/git-utils/package.json
- packages/git-utils/src/exec.ts
Replace path-exists with native fs.existsSync in @netlify/git-utils
As stated in the package's README so we don't need this
> NOTE: fs.existsSync has been un-deprecated in Node.js since 6.8.0. If you only need to check synchronously, this module is not needed.
P.S. it was the lowest-hanging fruit, I'm prepin a bigger PR on the weekend :)
---
Here's my friend's …
> fix: replaced path-exists with existsSync

- packages/build-info/src/node/get-build-info.test.ts
- packages/build/tests/telemetry/tests.js
1. `telemetry › tests › Telemetry calls timeout by default` (b48b211)
Example: https://github.com/netlify/build/actions/runs/16308326200/job/46058890684
2. `get-build-info > should retrieve the build info for providing a rootDir and the same projectDir` (44a2f151e)
Example: https://github.com/netlify/build/actions/runs/16307931875/job/46057797041
---
> test: resolve flaky telemetry and build info tests

- package-lock.json
- packages/zip-it-and-ship-it/package.json
> chore(deps): upgrade @vercel/nft to 0.30.0

- packages/edge-bundler/node/validation/manifest/__snapshots__/index.test.ts.snap
- packages/edge-bundler/node/validation/manifest/index.test.ts
- packages/edge-bundler/node/validation/manifest/schema.ts
`regexPattern` is only when we want to receive a full URL path, which is not the case when matching edge function header values.
> fix: use correct type when validating EF header regex

- packages/edge-bundler/node/formats/tarball.ts
We will start to use .tar.gz instead of .tar - smaller files for the win ☺️ (we can't yet use br or zstd for this unfortunately, only gzip is possible)
> fix: use gzip compression for the tarball generation

- packages/edge-bundler/deno/config.ts
- packages/edge-bundler/node/formats/tarball.ts
Instead of us manually keeping this in sync, let's have it done automatically?
> fix: use stable edge functions bootstrap package for globalThis.Netlify

- packages/build-info/src/frameworks/tanstack-start.test.ts
- packages/build-info/src/frameworks/tanstack-start.ts
The `alpha` branch of the TanStack Start React/Solid packages builds the client into `dist/client` (previously `dist`), so this updates the default Netlify publish dir to `dist/client` when detecting TanStack Start projects.
We don't yet know what version this will land in — I've used the next minor (1.132) as a placeholder for now.
This also adds a missing test for the Solid package and improves the test descriptions.
> fix: support post-nitro TanStack Start versions
